### Imports

In [1]:
import json
import os
import pandas as pd

from utils_MS import *

# %load_ext autotime

In [2]:
# def run(params):

### Parameters

In [3]:
""" try:
    dir = os.path.dirname(os.path.abspath(__file__))
except:
    dir = os.getcwd()
print(dir) """

' try:\n    dir = os.path.dirname(os.path.abspath(__file__))\nexcept:\n    dir = os.getcwd()\nprint(dir) '

In [4]:
dict_dataset = {
    1: ["Mentos_2_process_NormalizationFiltered_format", ["Orange"]], # new mentos,  for Metabolomics
    2: ["deybis_filter_september_2br_3ar_format", ["SecoAmazonas"]],
    3: ["deybis_filter_december_2br_3ar_format", ["SecoAmazonas"]],
    4: ["deybis_filter_september_2br_10ar_format", ["SecoAmazonas"]],
    5: ["deybis_filter_december_2br_10ar_format", ["SecoAmazonas"]], # for Metabolomics
    6: ["deybis_filter_september_min_2br_3ar_format", ["SecoAmazonas"]],
    7: ["deybis_filter_december_min_2br_3ar_format", ["SecoAmazonas"]],
    8: ["vanessa_december_2br_3ar_format", ["SecoAmazonas"]],
    9: ["Pablo_2br_14ar_format", ["AR"]],
    10: ["Pablo_2br_nar_format", ["AR"]],
    11: ["Pablo_2br_3ar_pn_42_format", ["AR"]],
    12: ["Pablo_2br_6ar_format", ["AR"]],
    13: ["Pablo_2br_3ar_p_42_format", ["AR"]],
    14: ["Pablo_2br_3ar_p_43_format", ["AR"]],
    15: ["Pablo_2br_3ar_p_44_format", ["AR"]],
    
    16: ["Pablo_2br_4ar_p_42_format", ["AR"]],
    17: ["Pablo_2br_4ar_p_43_format", ["AR"]],
    18: ["Pablo_2br_4ar_p_44_format", ["AR"]],
    19: ["Pablo_2br_8ar_p_42_format", ["AR"]],
	20: ["Pablo_2br_8ar_p_43_format", ["AR"]],
	21: ["Pablo_2br_8ar_p_44_format", ["AR"]],
	22: ["Pablo_2br_16ar_p_42_format", ["AR"]],
	23: ["Pablo_2br_16ar_p_43_format", ["AR"]],
	24: ["Pablo_2br_16ar_p_44_format", ["AR"]],
	25: ["Pablo_2br_mid_ar_p_42_format", ["AR"]],
	26: ["Pablo_2br_mid_ar_p_43_format", ["AR"]],
	27: ["Pablo_2br_mid_ar_p_44_format", ["AR"]],
	
	28: ["Pablo_2br_mid_sk_ar_p_42_format", ["AR"]],
	29: ["Pablo_2br_mid_sk_ar_p_43_format", ["AR"]],
	30: ["Pablo_2br_mid_sk_ar_p_44_format", ["AR"]],

	31: ["Pablo_new_2br_mid_ar_p_42_format", ["AR"]],
	32: ["Pablo_new_2br_mid_ar_p_43_format", ["AR"]],
	33: ["Pablo_new_2br_mid_ar_p_44_format", ["AR"]],
	
	34: ["Pablo_new_2br_N_ar_p_42_format", ["AR"]],
	35: ["Pablo_new_2br_N_ar_p_43_format", ["AR"]],
	36: ["Pablo_new_2br_N_ar_p_44_format", ["AR"]],

	37: ["Pablo_new_N_br_M_ar_p_42_format", ["AR"]],

	40: ["Vanessa_september_2br_10ar_format", ["SecoCusco"]],
}
dataset = dict_dataset[40] # change
dataset

['Vanessa_september_2br_10ar_format', ['SecoCusco']]

In [5]:
params = {
    "exp": "exp117", # Change
    "methods": ["t-gae"], # ["vgae-base", "argva-base", "vgae-line", "dgi-tran", "t-gae"],
    "data_variations": ["none"],
    "apply_transformation": True, # True or False
    "controls": dataset[1],
    "dimension": 128,
    "threshold_corr": 0.6,
    "threshold_log2": 0,
    "alpha": 0.05,
    "iterations": 1,
    "raw_data_file": dataset[0],
    "groups_id_no": ["Blank", "QC", "Std"],
    "sensitivity": False, # False: f1 (selectivity), True: f1 (selectivity), f2 (sensitivity)
    "obs": "",
    "seeds": [41, 42, 43, 44, 45, 46],
    
    "from": "python",
    "cuda": 1,
    "epochs": 500,
    "lr": 0.0001,
    "weight_decay": 5e-4,
    "patience": 20,
    "contamination": 0.1, # float in (0., 0.5)
    "n_jobs": 1, # -1 all
}

In [6]:
""" dir_path = "experiments/output"
res = sorted(os.listdir(dir_path))
n = len(res)
exp = "exp{}".format(n) """

exp = str(params["exp"])
exp

'exp117'

### Load dataset

In [7]:
# load dataset groups
if params["from"] == "python":
    df_raw = pd.read_csv("experiments/raw_data/{}.csv".format(params["raw_data_file"]), delimiter="|")
elif params["from"] == "drf":
    df_raw = pd.read_csv("{}".format(params["raw_data_file"]), delimiter="|") # from DRF
df_raw

,Alignment ID,Average Rt,Average Mz,Metabolite name,SecoAmazonas_1.1,SecoAmazonas_1.2,SecoAmazonas_1.3,SecoAmazonas_1.4,SecoAmazonas_1.5,SecoAmazonas_1.6,...,FrescoCusco_2.1,FrescoCusco_2.2,FrescoCusco_2.3,FrescoCusco_2.4,FrescoCusco_2.5,FrescoCusco_2.6,FrescoCusco_2.7,FrescoCusco_2.8,FrescoCusco_2.9,FrescoCusco_2.10
0,1,1.952,105.11092,NaN,8.279686e+05,7.976282e+05,9.726544e+05,1.032048e+06,1.131032e+06,1.141804e+06,...,2.410977e+06,2.844829e+06,2.260268e+06,2.221500e+06,2.399903e+06,2.444102e+06,2.149616e+06,2.219489e+06,2.446344e+06,2.310932e+06
1,2,9.737,106.06562,4-Vinylpyridine,2.565234e+06,2.752108e+06,1.763920e+06,2.124292e+06,1.730249e+06,1.842250e+06,...,2.631396e+06,2.633133e+06,1.097991e+06,3.459665e+06,1.714735e+06,5.108190e+06,3.075278e+06,2.943736e+06,2.255637e+06,2.139805e+06
2,3,11.881,106.06564,4-Vinylpyridine,5.420550e+06,4.386931e+06,3.960462e+06,3.405477e+06,6.724399e+06,4.544965e+06,...,4.813479e+06,5.131341e+06,5.106660e+06,4.622267e+06,6.236970e+06,5.259589e+06,4.695161e+06,4.913602e+06,4.379733e+06,3.992778e+06
3,4,11.635,106.06565,4-Vinylpyridine,2.347483e+06,7.154813e+05,1.169290e+06,1.103570e+06,4.259335e+06,4.456952e+06,...,3.452708e+06,2.774363e+06,9.078110e+05,1.061224e+06,4.728125e+06,6.628555e+06,3.019679e+06,2.160066e+06,2.127168e+06,1.579057e+06
4,5,13.412,106.06566,4-Vinylpyridine,2.840774e+06,3.178033e+06,2.614106e+06,2.392947e+06,4.668711e+06,3.407529e+06,...,4.294443e+06,3.754734e+06,2.923485e+06,2.929934e+06,2.693117e+06,3.168948e+06,3.312139e+06,3.418169e+06,3.492057e+06,3.353203e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1565,1566,2.020,738.15232,"4-amino-3-[[4-[4-[(2,4-diaminophenyl)diazenyl]...",1.779022e+04,1.718780e+04,6.386372e+03,5.824022e+03,6.450907e+03,7.167227e+03,...,2.343769e+04,2.852373e+04,3.984938e+04,4.482734e+04,9.181052e+04,1.004559e+05,3.695133e+04,4.148523e+04,3.805223e+04,3.489162e+04
1566,1567,6.266,739.18831,NaN,2.543316e+04,2.549013e+04,1.337529e+04,1.225071e+04,1.440067e+04,1.474776e+04,...,2.927516e+04,4.861673e+04,1.507018e+05,1.679731e+05,1.559491e+05,1.636592e+05,1.095599e+05,1.084921e+05,1.184369e+05,1.221423e+05
1567,1568,11.874,742.29184,NaN,2.481784e+06,1.960026e+06,2.876839e+06,3.085348e+06,2.626023e+06,2.923478e+06,...,2.511130e+06,3.536727e+06,2.352989e+06,2.335388e+06,3.237431e+06,2.926510e+06,2.823264e+06,2.943291e+06,2.789757e+06,2.653494e+06
1568,1569,16.132,743.36655,NaN,4.158460e+05,4.454981e+05,3.226384e+05,3.037055e+05,4.858122e+05,4.585723e+05,...,4.610230e+05,5.029163e+05,3.580115e+05,3.916965e+05,4.780022e+05,4.485697e+05,4.015281e+05,4.463161e+05,4.666817e+05,4.536518e+05
1569,1570,1.885,744.84547,NaN,1.307245e+05,8.807384e+04,7.894191e+04,8.163231e+04,1.461182e+05,1.404841e+05,...,2.978117e+05,2.178198e+05,1.028492e+05,9.081814e+04,1.672097e+05,1.702252e+05,1.537964e+05,1.200893e+05,1.649866e+05,1.577565e+05

### Format dataset

In [8]:
# apply transformation
columns_data = list(df_raw.columns)[4:]
if not params["apply_transformation"]:
    print("transformation")
    for column in columns_data:
        df_raw[column] = df_raw[column].apply(lambda x: 10**x)
df_raw

,Alignment ID,Average Rt,Average Mz,Metabolite name,SecoAmazonas_1.1,SecoAmazonas_1.2,SecoAmazonas_1.3,SecoAmazonas_1.4,SecoAmazonas_1.5,SecoAmazonas_1.6,...,FrescoCusco_2.1,FrescoCusco_2.2,FrescoCusco_2.3,FrescoCusco_2.4,FrescoCusco_2.5,FrescoCusco_2.6,FrescoCusco_2.7,FrescoCusco_2.8,FrescoCusco_2.9,FrescoCusco_2.10
0,1,1.952,105.11092,NaN,8.279686e+05,7.976282e+05,9.726544e+05,1.032048e+06,1.131032e+06,1.141804e+06,...,2.410977e+06,2.844829e+06,2.260268e+06,2.221500e+06,2.399903e+06,2.444102e+06,2.149616e+06,2.219489e+06,2.446344e+06,2.310932e+06
1,2,9.737,106.06562,4-Vinylpyridine,2.565234e+06,2.752108e+06,1.763920e+06,2.124292e+06,1.730249e+06,1.842250e+06,...,2.631396e+06,2.633133e+06,1.097991e+06,3.459665e+06,1.714735e+06,5.108190e+06,3.075278e+06,2.943736e+06,2.255637e+06,2.139805e+06
2,3,11.881,106.06564,4-Vinylpyridine,5.420550e+06,4.386931e+06,3.960462e+06,3.405477e+06,6.724399e+06,4.544965e+06,...,4.813479e+06,5.131341e+06,5.106660e+06,4.622267e+06,6.236970e+06,5.259589e+06,4.695161e+06,4.913602e+06,4.379733e+06,3.992778e+06
3,4,11.635,106.06565,4-Vinylpyridine,2.347483e+06,7.154813e+05,1.169290e+06,1.103570e+06,4.259335e+06,4.456952e+06,...,3.452708e+06,2.774363e+06,9.078110e+05,1.061224e+06,4.728125e+06,6.628555e+06,3.019679e+06,2.160066e+06,2.127168e+06,1.579057e+06
4,5,13.412,106.06566,4-Vinylpyridine,2.840774e+06,3.178033e+06,2.614106e+06,2.392947e+06,4.668711e+06,3.407529e+06,...,4.294443e+06,3.754734e+06,2.923485e+06,2.929934e+06,2.693117e+06,3.168948e+06,3.312139e+06,3.418169e+06,3.492057e+06,3.353203e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1565,1566,2.020,738.15232,"4-amino-3-[[4-[4-[(2,4-diaminophenyl)diazenyl]...",1.779022e+04,1.718780e+04,6.386372e+03,5.824022e+03,6.450907e+03,7.167227e+03,...,2.343769e+04,2.852373e+04,3.984938e+04,4.482734e+04,9.181052e+04,1.004559e+05,3.695133e+04,4.148523e+04,3.805223e+04,3.489162e+04
1566,1567,6.266,739.18831,NaN,2.543316e+04,2.549013e+04,1.337529e+04,1.225071e+04,1.440067e+04,1.474776e+04,...,2.927516e+04,4.861673e+04,1.507018e+05,1.679731e+05,1.559491e+05,1.636592e+05,1.095599e+05,1.084921e+05,1.184369e+05,1.221423e+05
1567,1568,11.874,742.29184,NaN,2.481784e+06,1.960026e+06,2.876839e+06,3.085348e+06,2.626023e+06,2.923478e+06,...,2.511130e+06,3.536727e+06,2.352989e+06,2.335388e+06,3.237431e+06,2.926510e+06,2.823264e+06,2.943291e+06,2.789757e+06,2.653494e+06
1568,1569,16.132,743.36655,NaN,4.158460e+05,4.454981e+05,3.226384e+05,3.037055e+05,4.858122e+05,4.585723e+05,...,4.610230e+05,5.029163e+05,3.580115e+05,3.916965e+05,4.780022e+05,4.485697e+05,4.015281e+05,4.463161e+05,4.666817e+05,4.536518e+05
1569,1570,1.885,744.84547,NaN,1.307245e+05,8.807384e+04,7.894191e+04,8.163231e+04,1.461182e+05,1.404841e+05,...,2.978117e+05,2.178198e+05,1.028492e+05,9.081814e+04,1.672097e+05,1.702252e+05,1.537964e+05,1.200893e+05,1.649866e+05,1.577565e+05

In [9]:
# concat
df_join_raw = pd.concat([
    df_raw.iloc[:, :]], axis=1)
df_join_raw.set_index("Alignment ID", inplace=True)
df_join_raw

,Average Rt,Average Mz,Metabolite name,SecoAmazonas_1.1,SecoAmazonas_1.2,SecoAmazonas_1.3,SecoAmazonas_1.4,SecoAmazonas_1.5,SecoAmazonas_1.6,SecoAmazonas_1.7,...,FrescoCusco_2.1,FrescoCusco_2.2,FrescoCusco_2.3,FrescoCusco_2.4,FrescoCusco_2.5,FrescoCusco_2.6,FrescoCusco_2.7,FrescoCusco_2.8,FrescoCusco_2.9,FrescoCusco_2.10
Alignment ID,,,,,,,,,,,,,,,,,,,,,
1,1.952,105.11092,NaN,8.279686e+05,7.976282e+05,9.726544e+05,1.032048e+06,1.131032e+06,1.141804e+06,9.885037e+05,...,2.410977e+06,2.844829e+06,2.260268e+06,2.221500e+06,2.399903e+06,2.444102e+06,2.149616e+06,2.219489e+06,2.446344e+06,2.310932e+06
2,9.737,106.06562,4-Vinylpyridine,2.565234e+06,2.752108e+06,1.763920e+06,2.124292e+06,1.730249e+06,1.842250e+06,3.110836e+06,...,2.631396e+06,2.633133e+06,1.097991e+06,3.459665e+06,1.714735e+06,5.108190e+06,3.075278e+06,2.943736e+06,2.255637e+06,2.139805e+06
3,11.881,106.06564,4-Vinylpyridine,5.420550e+06,4.386931e+06,3.960462e+06,3.405477e+06,6.724399e+06,4.544965e+06,5.063095e+06,...,4.813479e+06,5.131341e+06,5.106660e+06,4.622267e+06,6.236970e+06,5.259589e+06,4.695161e+06,4.913602e+06,4.379733e+06,3.992778e+06
4,11.635,106.06565,4-Vinylpyridine,2.347483e+06,7.154813e+05,1.169290e+06,1.103570e+06,4.259335e+06,4.456952e+06,2.675080e+06,...,3.452708e+06,2.774363e+06,9.078110e+05,1.061224e+06,4.728125e+06,6.628555e+06,3.019679e+06,2.160066e+06,2.127168e+06,1.579057e+06
5,13.412,106.06566,4-Vinylpyridine,2.840774e+06,3.178033e+06,2.614106e+06,2.392947e+06,4.668711e+06,3.407529e+06,3.455154e+06,...,4.294443e+06,3.754734e+06,2.923485e+06,2.929934e+06,2.693117e+06,3.168948e+06,3.312139e+06,3.418169e+06,3.492057e+06,3.353203e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1566,2.020,738.15232,"4-amino-3-[[4-[4-[(2,4-diaminophenyl)diazenyl]...",1.779022e+04,1.718780e+04,6.386372e+03,5.824022e+03,6.450907e+03,7.167227e+03,7.767716e+03,...,2.343769e+04,2.852373e+04,3.984938e+04,4.482734e+04,9.181052e+04,1.004559e+05,3.695133e+04,4.148523e+04,3.805223e+04,3.489162e+04
1567,6.266,739.18831,NaN,2.543316e+04,2.549013e+04,1.337529e+04,1.225071e+04,1.440067e+04,1.474776e+04,1.609699e+04,...,2.927516e+04,4.861673e+04,1.507018e+05,1.679731e+05,1.559491e+05,1.636592e+05,1.095599e+05,1.084921e+05,1.184369e+05,1.221423e+05
1568,11.874,742.29184,NaN,2.481784e+06,1.960026e+06,2.876839e+06,3.085348e+06,2.626023e+06,2.923478e+06,2.854038e+06,...,2.511130e+06,3.536727e+06,2.352989e+06,2.335388e+06,3.237431e+06,2.926510e+06,2.823264e+06,2.943291e+06,2.789757e+06,2.653494e+06
1569,16.132,743.36655,NaN,4.158460e+05,4.454981e+05,3.226384e+05,3.037055e+05,4.858122e+05,4.585723e+05,4.311488e+05,...,4.610230e+05,5.029163e+05,3.580115e+05,3.916965e+05,4.780022e+05,4.485697e+05,4.015281e+05,4.463161e+05,4.666817e+05,4.536518e+05
1570,1.885,744.84547,NaN,1.307245e+05,8.807384e+04,7.894191e+04,8.163231e+04,1.461182e+05,1.404841e+05,1.314746e+05,...,2.978117e+05,2.178198e+05,1.028492e+05,9.081814e+04,1.672097e+05,1.702252e+05,1.537964e+05,1.200893e+05,1.649866e+05,1.577565e+05

In [10]:
# split
df_join_raw = df_join_raw.rename_axis(None)
# df_join_raw = df_join_raw.iloc[:, 2:]
df_join_raw

,Average Rt,Average Mz,Metabolite name,SecoAmazonas_1.1,SecoAmazonas_1.2,SecoAmazonas_1.3,SecoAmazonas_1.4,SecoAmazonas_1.5,SecoAmazonas_1.6,SecoAmazonas_1.7,...,FrescoCusco_2.1,FrescoCusco_2.2,FrescoCusco_2.3,FrescoCusco_2.4,FrescoCusco_2.5,FrescoCusco_2.6,FrescoCusco_2.7,FrescoCusco_2.8,FrescoCusco_2.9,FrescoCusco_2.10
1,1.952,105.11092,NaN,8.279686e+05,7.976282e+05,9.726544e+05,1.032048e+06,1.131032e+06,1.141804e+06,9.885037e+05,...,2.410977e+06,2.844829e+06,2.260268e+06,2.221500e+06,2.399903e+06,2.444102e+06,2.149616e+06,2.219489e+06,2.446344e+06,2.310932e+06
2,9.737,106.06562,4-Vinylpyridine,2.565234e+06,2.752108e+06,1.763920e+06,2.124292e+06,1.730249e+06,1.842250e+06,3.110836e+06,...,2.631396e+06,2.633133e+06,1.097991e+06,3.459665e+06,1.714735e+06,5.108190e+06,3.075278e+06,2.943736e+06,2.255637e+06,2.139805e+06
3,11.881,106.06564,4-Vinylpyridine,5.420550e+06,4.386931e+06,3.960462e+06,3.405477e+06,6.724399e+06,4.544965e+06,5.063095e+06,...,4.813479e+06,5.131341e+06,5.106660e+06,4.622267e+06,6.236970e+06,5.259589e+06,4.695161e+06,4.913602e+06,4.379733e+06,3.992778e+06
4,11.635,106.06565,4-Vinylpyridine,2.347483e+06,7.154813e+05,1.169290e+06,1.103570e+06,4.259335e+06,4.456952e+06,2.675080e+06,...,3.452708e+06,2.774363e+06,9.078110e+05,1.061224e+06,4.728125e+06,6.628555e+06,3.019679e+06,2.160066e+06,2.127168e+06,1.579057e+06
5,13.412,106.06566,4-Vinylpyridine,2.840774e+06,3.178033e+06,2.614106e+06,2.392947e+06,4.668711e+06,3.407529e+06,3.455154e+06,...,4.294443e+06,3.754734e+06,2.923485e+06,2.929934e+06,2.693117e+06,3.168948e+06,3.312139e+06,3.418169e+06,3.492057e+06,3.353203e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1566,2.020,738.15232,"4-amino-3-[[4-[4-[(2,4-diaminophenyl)diazenyl]...",1.779022e+04,1.718780e+04,6.386372e+03,5.824022e+03,6.450907e+03,7.167227e+03,7.767716e+03,...,2.343769e+04,2.852373e+04,3.984938e+04,4.482734e+04,9.181052e+04,1.004559e+05,3.695133e+04,4.148523e+04,3.805223e+04,3.489162e+04
1567,6.266,739.18831,NaN,2.543316e+04,2.549013e+04,1.337529e+04,1.225071e+04,1.440067e+04,1.474776e+04,1.609699e+04,...,2.927516e+04,4.861673e+04,1.507018e+05,1.679731e+05,1.559491e+05,1.636592e+05,1.095599e+05,1.084921e+05,1.184369e+05,1.221423e+05
1568,11.874,742.29184,NaN,2.481784e+06,1.960026e+06,2.876839e+06,3.085348e+06,2.626023e+06,2.923478e+06,2.854038e+06,...,2.511130e+06,3.536727e+06,2.352989e+06,2.335388e+06,3.237431e+06,2.926510e+06,2.823264e+06,2.943291e+06,2.789757e+06,2.653494e+06
1569,16.132,743.36655,NaN,4.158460e+05,4.454981e+05,3.226384e+05,3.037055e+05,4.858122e+05,4.585723e+05,4.311488e+05,...,4.610230e+05,5.029163e+05,3.580115e+05,3.916965e+05,4.780022e+05,4.485697e+05,4.015281e+05,4.463161e+05,4.666817e+05,4.536518e+05
1570,1.885,744.84547,NaN,1.307245e+05,8.807384e+04,7.894191e+04,8.163231e+04,1.461182e+05,1.404841e+05,1.314746e+05,...,2.978117e+05,2.178198e+05,1.028492e+05,9.081814e+04,1.672097e+05,1.702252e+05,1.537964e+05,1.200893e+05,1.649866e+05,1.577565e+05

In [11]:
# get groups name
groups_id_no = params["groups_id_no"]
groups_id = []
for item in df_join_raw.iloc[:, 3:].columns.values:
    group_id = item.split("_")[0]
    if group_id not in groups_id and group_id not in groups_id_no:
        groups_id.append(group_id)
groups_id

['SecoAmazonas',
 'SecoSanMartin',
 'SecoCusco',
 'FrescoAmazonas',
 'FrescoSanMartin',
 'FrescoCusco']

In [12]:
# delete no sample columns
""" columns_delete = [columna for columna in df_join_raw.columns if columna.split("_")[0] in columns_no_sample]
df_join_raw.drop(columns_delete, axis=1, inplace=True)
df_join_raw """

' columns_delete = [columna for columna in df_join_raw.columns if columna.split("_")[0] in columns_no_sample]\ndf_join_raw.drop(columns_delete, axis=1, inplace=True)\ndf_join_raw '

In [13]:
# get subgroups names

""" def get_subgroups_id(df_join_raw, groups, by_group=False):
    dict_groups_id = {}
    for group in groups:
        # get group
        if by_group:
            dict_groups_id[group] = ["1"]
        else:
            columns = list(df_join_raw.filter(like=group).columns)
            subgroups = [item.split("{}_".format(group))[1].split(".")[0] for item in columns]
            subgroups = np.unique(subgroups)
            dict_groups_id[group] = subgroups.tolist()
    return dict_groups_id """

subgroups_id = get_subgroups_id(df_join_raw, groups_id)
subgroups_id

{'SecoAmazonas': ['1', '2'],
 'SecoSanMartin': ['1', '2'],
 'SecoCusco': ['1', '2'],
 'FrescoAmazonas': ['1', '2'],
 'FrescoSanMartin': ['1', '2'],
 'FrescoCusco': ['1', '2']}

In [14]:
# count analtical repetitions
# df_join_raw.filter(like="AA_1.")

In [15]:
# check distribution

In [16]:
""" x = df_join_raw.iloc[2, 3:]
print(x.min(), x.max(), x.mean())
x.hist(bins=200) """

' x = df_join_raw.iloc[2, 3:]\nprint(x.min(), x.max(), x.mean())\nx.hist(bins=200) '

In [17]:
# f_join_raw.iloc[:, 5].hist(bins=100)

In [18]:
params["controls"], groups_id

(['SecoCusco'],
 ['SecoAmazonas',
  'SecoSanMartin',
  'SecoCusco',
  'FrescoAmazonas',
  'FrescoSanMartin',
  'FrescoCusco'])

In [19]:
# get groups combination
groups = []
controls = params["controls"]

groups = []
for control in controls:
    for group_id in groups_id:
        if control != group_id:
            groups.append([control, group_id])
print(groups)

[['SecoCusco', 'SecoAmazonas'], ['SecoCusco', 'SecoSanMartin'], ['SecoCusco', 'FrescoAmazonas'], ['SecoCusco', 'FrescoSanMartin'], ['SecoCusco', 'FrescoCusco']]

### Create folders

In [20]:
# create experiments folder
try: 
    os.mkdir("experiments/output/{}".format(exp))
    os.mkdir("experiments/output/{}/correlations".format(exp))
    os.mkdir("experiments/output/{}/preprocessing".format(exp))
    os.mkdir("experiments/output/{}/preprocessing/edges".format(exp))
    os.mkdir("experiments/output/{}/preprocessing/graphs_data".format(exp))
    os.mkdir("experiments/output/{}/loss".format(exp))
    os.mkdir("experiments/output/{}/node_embeddings".format(exp))
    os.mkdir("experiments/output/{}/common_nodes".format(exp))
    os.mkdir("experiments/output/{}/filter_raw".format(exp))
    os.mkdir("experiments/output/{}/plots".format(exp))
except OSError as error: 
    print(error)

### Save dataset and parameters

In [21]:
# save dataset
df_join_raw.to_csv("experiments/input/{}_raw.csv".format(exp), index=True)

# save parameters
parameters = {
    "exp": exp,
    "methods": params["methods"],
    "data_variations": params["data_variations"],
    "apply_transformation": params["apply_transformation"],
    "controls": params["controls"],
    "dimension": params["dimension"],
    "threshold_corr": params["threshold_corr"],
    "threshold_log2": params["threshold_log2"],
    "alpha": params["alpha"],
    "iterations": params["iterations"],
    "raw_data_file": params["raw_data_file"],
    "groups_id": groups_id,
    "subgroups_id": subgroups_id,
    "groups": groups,
    "groups_id_no": params["groups_id_no"],
    "sensitivity": params["sensitivity"],
    
    "from": params["from"],
    "cuda": params["cuda"],
    "epochs": params["epochs"],
    "lr": params["lr"],
    "weight_decay": params["weight_decay"],
    "patience": params["patience"],
    "contamination": params["contamination"],
    "n_jobs": params["n_jobs"],

    "seeds": params["seeds"],
    "obs": params["obs"]
}

with open("experiments/output/{}/parameters.json".format(exp), "w") as outfile:
    json.dump(parameters, outfile, indent=4)

/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/outdated/utils.py:14: OutdatedPackageWarning: The package pingouin is out of date. Your version is 0.5.3, the latest is 0.7.0.
Set the environment variable OUTDATED_IGNORE=1 to disable these warnings.
  return warn(

In [22]:
experiments = {
    "exp": exp
}

with open("exp.json".format(experiments), "w") as outfile:
    json.dump(experiments, outfile, indent=4)

In [23]:
# return exp