### Imports

In [1]:
import json
import os
import pandas as pd

from utils_MS import *

# %load_ext autotime

/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/outdated/utils.py:14: OutdatedPackageWarning: The package pingouin is out of date. Your version is 0.5.3, the latest is 0.6.1.
Set the environment variable OUTDATED_IGNORE=1 to disable these warnings.
  return warn(

In [2]:
# def run(params):

### Parameters

In [3]:
""" try:
    dir = os.path.dirname(os.path.abspath(__file__))
except:
    dir = os.getcwd()
print(dir) """

' try:\n    dir = os.path.dirname(os.path.abspath(__file__))\nexcept:\n    dir = os.getcwd()\nprint(dir) '

In [4]:
dict_dataset = {
    1: ["Mentos_2_process_NormalizationFiltered_format", ["Orange"]], # new mentos,  for Metabolomics
    2: ["deybis_filter_september_2br_3ar_format", ["SecoAmazonas"]],
    3: ["deybis_filter_december_2br_3ar_format", ["SecoAmazonas"]],
    4: ["deybis_filter_september_2br_10ar_format", ["SecoAmazonas"]],
    5: ["deybis_filter_december_2br_10ar_format", ["SecoAmazonas"]], # for Metabolomics
    6: ["deybis_filter_september_min_2br_3ar_format", ["SecoAmazonas"]],
    7: ["deybis_filter_december_min_2br_3ar_format", ["SecoAmazonas"]],
    8: ["vanessa_december_2br_3ar_format", ["SecoAmazonas"]],
    9: ["Pablo_2br_nar_format", ["AR"]],
    10: ["Pablo_2br_14ar_format", ["AR"]],
}
dataset = dict_dataset[10] # change
dataset

['Pablo_2br_14ar_format', ['AR']]

In [5]:
params = {
    "exp": "exp11", # Change
    "methods": ["t-gae"], # ["vgae-base", "argva-base", "vgae-line", "dgi-tran", "t-gae"],
    "data_variations": ["none"],
    "has_transformation": True, # True or False
    "controls": dataset[1],
    "dimension": 64,
    "threshold_corr": 0.5,
    "threshold_log2": 0,
    "alpha": 0.05,
    "iterations": 1,
    "raw_data_file": dataset[0],
    "groups_id_no": ["Blank", "QC", "Std"],
    "sensitivity": False, # False: f1 (selectivity), True: f1 (selectivity), f2 (sensitivity)
    "obs": "",
    "seeds": [41, 42, 43, 44, 45, 46],
    
    "from": "python",
    "cuda": 0,
    "epochs": 100,
    "lr": 0.0001,
    "weight_decay": 1e-4,
    "patience": 10,
    "contamination": 0.1, # float in (0., 0.5)
    "n_jobs": 1, # -1 all
}

In [6]:
""" dir_path = "experiments/output"
res = sorted(os.listdir(dir_path))
n = len(res)
exp = "exp{}".format(n) """

exp = str(params["exp"])
exp

'exp11'

### Load dataset

In [7]:
# load dataset groups
if params["from"] == "python":
    df_raw = pd.read_csv("experiments/raw_data/{}.csv".format(params["raw_data_file"]), delimiter="|")
elif params["from"] == "drf":
    df_raw = pd.read_csv("{}".format(params["raw_data_file"]), delimiter="|") # from DRF
df_raw

,Alignment ID,Average Rt,Average Mz,Metabolite name,AR_1.1,AR_1.2,AR_1.3,AR_1.4,AR_1.5,AR_1.6,...,PD_2.5,PD_2.6,PD_2.7,PD_2.8,PD_2.9,PD_2.10,PD_2.11,PD_2.12,PD_2.13,PD_2.14
0,0,1,69.99951,Unknown,0.57533,-2.21576,-1.87702,-1.51884,-1.39884,-1.29892,...,0.98788,-0.84910,-0.00751,0.45284,0.43153,-0.04444,0.46331,0.02780,-1.09413,-1.07540
1,1,1,70.04025,Unknown,2.51970,0.52452,0.86264,1.22016,1.33995,1.43969,...,3.04923,2.96805,2.60501,3.06450,3.04323,2.56814,3.07496,2.64025,4.43489,2.05710
2,2,1,70.04151,Unknown,0.58098,-0.48955,-0.21483,0.07565,0.17297,0.25400,...,1.67929,1.93973,1.11480,1.48813,1.47085,1.08484,1.49663,1.14343,0.52253,1.85662
3,3,1,70.04908,Unknown,2.57051,-0.10795,0.21509,0.55668,0.67112,0.76641,...,2.38948,1.70959,1.86469,2.30371,2.28339,1.82946,2.31369,1.89836,0.67806,0.69874
4,4,1,70.06267,Unknown,1.15787,-0.15137,0.12754,0.29794,0.42245,0.52127,...,2.60041,1.39557,1.36967,1.75502,1.73727,1.33853,1.76374,1.39940,1.12760,2.77683
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5439,5439,1,732.79951,Unknown,2.21477,-0.58849,-0.38930,-0.17867,-0.10810,4.23613,...,0.97794,0.89484,0.53114,0.81967,0.80618,0.50653,0.82628,0.55450,0.10928,0.17849
5440,5440,1,748.76437,Unknown,0.72580,-1.43132,-1.05285,-0.65267,-0.51859,-0.40695,...,1.16682,1.08808,0.89559,1.39809,1.37400,0.85432,1.40992,0.93504,0.20434,0.27869
5441,5441,1,794.79590,Unknown,1.65124,-1.20428,-0.80051,-0.37358,-0.23053,-0.11143,...,1.03778,0.97033,1.21288,1.75795,1.73195,1.16780,1.77073,1.25592,0.32484,0.38565
5442,5442,1,800.81295,Unknown,1.51148,-1.03648,-0.60768,-0.15429,-0.00238,0.12410,...,1.34152,1.28640,1.55386,2.12317,2.09588,1.50710,2.13658,1.59856,0.75971,0.81518
5443,5443,1,860.74167,Unknown,1.94236,-1.79295,-1.44649,6.03212,-1.08016,-0.95742,...,0.54552,0.46021,0.26878,0.75559,0.73328,0.22915,0.76655,0.30656,-0.34353,-0.27863

### Format dataset

In [8]:
# has transformation
columns_data = list(df_raw.columns)[4:]
if params["has_transformation"]:
    print("transformation")
    for column in columns_data:
        df_raw[column] = df_raw[column].apply(lambda x: 10**x)
df_raw

transformation

,Alignment ID,Average Rt,Average Mz,Metabolite name,AR_1.1,AR_1.2,AR_1.3,AR_1.4,AR_1.5,AR_1.6,...,PD_2.5,PD_2.6,PD_2.7,PD_2.8,PD_2.9,PD_2.10,PD_2.11,PD_2.12,PD_2.13,PD_2.14
0,0,1,69.99951,Unknown,3.761231,0.006085,0.013273,3.028029e-02,0.039917,0.050244,...,9.724785,0.141547,0.982856,2.836874,2.701034,0.902734,2.906096,1.066105,0.080514,0.084062
1,1,1,70.04025,Unknown,330.902463,3.345954,7.288531,1.660198e+01,21.875098,27.522634,...,1120.030889,929.073344,402.726307,1160.112216,1104.663489,369.947418,1188.392767,436.767183,27220.117777,114.051237
2,2,1,70.04151,Unknown,3.810483,0.323929,0.609776,1.190282e+00,1.489258,1.794734,...,47.784825,87.042228,13.025668,30.770177,29.569910,12.157380,31.378343,13.913295,3.330658,71.881975
3,3,1,70.04908,Unknown,371.971786,0.779920,1.640930,3.603131e+00,4.689429,5.839962,...,245.177154,51.237744,73.230163,201.238003,192.039249,67.524286,205.915956,79.133432,4.764968,4.997353
4,4,1,70.06267,Unknown,14.383680,0.705716,1.341343,1.985821e+00,2.645148,3.321009,...,398.483185,24.863943,23.424482,56.887913,54.609726,21.803690,58.041683,25.084185,13.415288,598.177399
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5439,5439,1,732.79951,Unknown,163.972116,0.257935,0.408037,6.627199e-01,0.779651,17223.840695,...,9.504735,7.849464,3.397348,6.601916,6.400000,3.210185,6.703166,3.585089,1.286116,1.508308
5440,5440,1,748.76437,Unknown,5.318633,0.037041,0.088542,2.225000e-01,0.302977,0.391787,...,14.683176,12.248418,7.863031,25.008636,23.659197,7.150230,25.699223,8.610731,1.600811,1.899722
5441,5441,1,794.79590,Unknown,44.796079,0.062477,0.158303,4.230776e-01,0.588125,0.773695,...,10.908876,9.339637,16.326008,57.273009,53.944851,14.716346,58.983427,18.026856,2.112711,2.430245
5442,5442,1,800.81295,Unknown,32.469829,0.091943,0.246786,7.009871e-01,0.994535,1.330761,...,21.954321,19.337485,35.798102,132.791415,124.703890,32.144006,136.955665,39.678934,5.750558,6.534013
5443,5443,1,860.74167,Unknown,87.570938,0.016108,0.035769,1.076763e+06,0.083146,0.110301,...,3.511721,2.885426,1.856864,5.696263,5.411031,1.694923,5.841845,2.025629,0.453388,0.526466

In [9]:
# concat
df_join_raw = pd.concat([
    df_raw.iloc[:, :]], axis=1)
df_join_raw.set_index("Alignment ID", inplace=True)
df_join_raw

,Average Rt,Average Mz,Metabolite name,AR_1.1,AR_1.2,AR_1.3,AR_1.4,AR_1.5,AR_1.6,AR_1.7,...,PD_2.5,PD_2.6,PD_2.7,PD_2.8,PD_2.9,PD_2.10,PD_2.11,PD_2.12,PD_2.13,PD_2.14
Alignment ID,,,,,,,,,,,,,,,,,,,,,
0,1,69.99951,Unknown,3.761231,0.006085,0.013273,3.028029e-02,0.039917,0.050244,0.061227,...,9.724785,0.141547,0.982856,2.836874,2.701034,0.902734,2.906096,1.066105,0.080514,0.084062
1,1,70.04025,Unknown,330.902463,3.345954,7.288531,1.660198e+01,21.875098,27.522634,33.526638,...,1120.030889,929.073344,402.726307,1160.112216,1104.663489,369.947418,1188.392767,436.767183,27220.117777,114.051237
2,1,70.04151,Unknown,3.810483,0.323929,0.609776,1.190282e+00,1.489258,1.794734,2.106832,...,47.784825,87.042228,13.025668,30.770177,29.569910,12.157380,31.378343,13.913295,3.330658,71.881975
3,1,70.04908,Unknown,371.971786,0.779920,1.640930,3.603131e+00,4.689429,5.839962,7.051638,...,245.177154,51.237744,73.230163,201.238003,192.039249,67.524286,205.915956,79.133432,4.764968,4.997353
4,1,70.06267,Unknown,14.383680,0.705716,1.341343,1.985821e+00,2.645148,3.321009,4.013655,...,398.483185,24.863943,23.424482,56.887913,54.609726,21.803690,58.041683,25.084185,13.415288,598.177399
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5439,1,732.79951,Unknown,163.972116,0.257935,0.408037,6.627199e-01,0.779651,17223.840695,0.892606,...,9.504735,7.849464,3.397348,6.601916,6.400000,3.210185,6.703166,3.585089,1.286116,1.508308
5440,1,748.76437,Unknown,5.318633,0.037041,0.088542,2.225000e-01,0.302977,0.391787,0.488619,...,14.683176,12.248418,7.863031,25.008636,23.659197,7.150230,25.699223,8.610731,1.600811,1.899722
5441,1,794.79590,Unknown,44.796079,0.062477,0.158303,4.230776e-01,0.588125,0.773695,0.979264,...,10.908876,9.339637,16.326008,57.273009,53.944851,14.716346,58.983427,18.026856,2.112711,2.430245
5442,1,800.81295,Unknown,32.469829,0.091943,0.246786,7.009871e-01,0.994535,1.330761,1.709149,...,21.954321,19.337485,35.798102,132.791415,124.703890,32.144006,136.955665,39.678934,5.750558,6.534013
5443,1,860.74167,Unknown,87.570938,0.016108,0.035769,1.076763e+06,0.083146,0.110301,0.139566,...,3.511721,2.885426,1.856864,5.696263,5.411031,1.694923,5.841845,2.025629,0.453388,0.526466

In [10]:
# split
df_join_raw = df_join_raw.rename_axis(None)
# df_join_raw = df_join_raw.iloc[:, 2:]
df_join_raw

,Average Rt,Average Mz,Metabolite name,AR_1.1,AR_1.2,AR_1.3,AR_1.4,AR_1.5,AR_1.6,AR_1.7,...,PD_2.5,PD_2.6,PD_2.7,PD_2.8,PD_2.9,PD_2.10,PD_2.11,PD_2.12,PD_2.13,PD_2.14
0,1,69.99951,Unknown,3.761231,0.006085,0.013273,3.028029e-02,0.039917,0.050244,0.061227,...,9.724785,0.141547,0.982856,2.836874,2.701034,0.902734,2.906096,1.066105,0.080514,0.084062
1,1,70.04025,Unknown,330.902463,3.345954,7.288531,1.660198e+01,21.875098,27.522634,33.526638,...,1120.030889,929.073344,402.726307,1160.112216,1104.663489,369.947418,1188.392767,436.767183,27220.117777,114.051237
2,1,70.04151,Unknown,3.810483,0.323929,0.609776,1.190282e+00,1.489258,1.794734,2.106832,...,47.784825,87.042228,13.025668,30.770177,29.569910,12.157380,31.378343,13.913295,3.330658,71.881975
3,1,70.04908,Unknown,371.971786,0.779920,1.640930,3.603131e+00,4.689429,5.839962,7.051638,...,245.177154,51.237744,73.230163,201.238003,192.039249,67.524286,205.915956,79.133432,4.764968,4.997353
4,1,70.06267,Unknown,14.383680,0.705716,1.341343,1.985821e+00,2.645148,3.321009,4.013655,...,398.483185,24.863943,23.424482,56.887913,54.609726,21.803690,58.041683,25.084185,13.415288,598.177399
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5439,1,732.79951,Unknown,163.972116,0.257935,0.408037,6.627199e-01,0.779651,17223.840695,0.892606,...,9.504735,7.849464,3.397348,6.601916,6.400000,3.210185,6.703166,3.585089,1.286116,1.508308
5440,1,748.76437,Unknown,5.318633,0.037041,0.088542,2.225000e-01,0.302977,0.391787,0.488619,...,14.683176,12.248418,7.863031,25.008636,23.659197,7.150230,25.699223,8.610731,1.600811,1.899722
5441,1,794.79590,Unknown,44.796079,0.062477,0.158303,4.230776e-01,0.588125,0.773695,0.979264,...,10.908876,9.339637,16.326008,57.273009,53.944851,14.716346,58.983427,18.026856,2.112711,2.430245
5442,1,800.81295,Unknown,32.469829,0.091943,0.246786,7.009871e-01,0.994535,1.330761,1.709149,...,21.954321,19.337485,35.798102,132.791415,124.703890,32.144006,136.955665,39.678934,5.750558,6.534013
5443,1,860.74167,Unknown,87.570938,0.016108,0.035769,1.076763e+06,0.083146,0.110301,0.139566,...,3.511721,2.885426,1.856864,5.696263,5.411031,1.694923,5.841845,2.025629,0.453388,0.526466

In [11]:
# get groups name
groups_id_no = params["groups_id_no"]
groups_id = []
for item in df_join_raw.iloc[:, 3:].columns.values:
    group_id = item.split("_")[0]
    if group_id not in groups_id and group_id not in groups_id_no:
        groups_id.append(group_id)
groups_id

['AR', 'CRS', 'OSA', 'LPRD', 'SGB', 'LSNB', 'RCC', 'BC', 'BPH', 'PCa', 'PD']

In [12]:
# delete no sample columns
""" columns_delete = [columna for columna in df_join_raw.columns if columna.split("_")[0] in columns_no_sample]
df_join_raw.drop(columns_delete, axis=1, inplace=True)
df_join_raw """

' columns_delete = [columna for columna in df_join_raw.columns if columna.split("_")[0] in columns_no_sample]\ndf_join_raw.drop(columns_delete, axis=1, inplace=True)\ndf_join_raw '

In [13]:
# get subgroups names

""" def get_subgroups_id(df_join_raw, groups, by_group=False):
    dict_groups_id = {}
    for group in groups:
        # get group
        if by_group:
            dict_groups_id[group] = ["1"]
        else:
            columns = list(df_join_raw.filter(like=group).columns)
            subgroups = [item.split("{}_".format(group))[1].split(".")[0] for item in columns]
            subgroups = np.unique(subgroups)
            dict_groups_id[group] = subgroups.tolist()
    return dict_groups_id """

subgroups_id = get_subgroups_id(df_join_raw, groups_id)
subgroups_id

{'AR': ['1', '2'],
 'CRS': ['1', '2'],
 'OSA': ['1', '2'],
 'LPRD': ['1', '2'],
 'SGB': ['1', '2'],
 'LSNB': ['1', '2'],
 'RCC': ['1', '2'],
 'BC': ['1', '2'],
 'BPH': ['1', '2'],
 'PCa': ['1', '2'],
 'PD': ['1', '2']}

In [14]:
# count analtical repetitions
# df_join_raw.filter(like="AA_1.")

In [15]:
# check distribution

In [16]:
""" x = df_join_raw.iloc[2, 3:]
print(x.min(), x.max(), x.mean())
x.hist(bins=200) """

' x = df_join_raw.iloc[2, 3:]\nprint(x.min(), x.max(), x.mean())\nx.hist(bins=200) '

In [17]:
# f_join_raw.iloc[:, 5].hist(bins=100)

In [18]:
params["controls"], groups_id

(['AR'],
 ['AR', 'CRS', 'OSA', 'LPRD', 'SGB', 'LSNB', 'RCC', 'BC', 'BPH', 'PCa', 'PD'])

In [19]:
# get groups combination
groups = []
controls = params["controls"]

groups = []
for control in controls:
    for group_id in groups_id:
        if control != group_id:
            groups.append([control, group_id])
print(groups)

[['AR', 'CRS'], ['AR', 'OSA'], ['AR', 'LPRD'], ['AR', 'SGB'], ['AR', 'LSNB'], ['AR', 'RCC'], ['AR', 'BC'], ['AR', 'BPH'], ['AR', 'PCa'], ['AR', 'PD']]

### Create folders

In [20]:
# create experiments folder
try: 
    os.mkdir("experiments/output/{}".format(exp))
    os.mkdir("experiments/output/{}/correlations".format(exp))
    os.mkdir("experiments/output/{}/preprocessing".format(exp))
    os.mkdir("experiments/output/{}/preprocessing/edges".format(exp))
    os.mkdir("experiments/output/{}/preprocessing/graphs_data".format(exp))
    os.mkdir("experiments/output/{}/loss".format(exp))
    os.mkdir("experiments/output/{}/node_embeddings".format(exp))
    os.mkdir("experiments/output/{}/common_nodes".format(exp))
    os.mkdir("experiments/output/{}/filter_raw".format(exp))
    os.mkdir("experiments/output/{}/plots".format(exp))
except OSError as error: 
    print(error)

### Save dataset and parameters

In [21]:
# save dataset
df_join_raw.to_csv("experiments/input/{}_raw.csv".format(exp), index=True)

# save parameters
parameters = {
    "exp": exp,
    "methods": params["methods"],
    "data_variations": params["data_variations"],
    "has_transformation": params["has_transformation"],
    "controls": params["controls"],
    "dimension": params["dimension"],
    "threshold_corr": params["threshold_corr"],
    "threshold_log2": params["threshold_log2"],
    "alpha": params["alpha"],
    "iterations": params["iterations"],
    "raw_data_file": params["raw_data_file"],
    "groups_id": groups_id,
    "subgroups_id": subgroups_id,
    "groups": groups,
    "groups_id_no": params["groups_id_no"],
    "sensitivity": params["sensitivity"],
    
    "from": params["from"],
    "cuda": params["cuda"],
    "epochs": params["epochs"],
    "lr": params["lr"],
    "weight_decay": params["weight_decay"],
    "patience": params["patience"],
    "contamination": params["contamination"],
    "n_jobs": params["n_jobs"],

    "seeds": params["seeds"],
    "obs": params["obs"]
}

with open("experiments/output/{}/parameters.json".format(exp), "w") as outfile:
    json.dump(parameters, outfile, indent=4)

In [22]:
experiments = {
    "exp": exp
}

with open("exp.json".format(experiments), "w") as outfile:
    json.dump(experiments, outfile, indent=4)

In [23]:
# return exp