### Imports

In [1]:
import json
import os
import pandas as pd

from utils_MS import *

# %load_ext autotime

/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/outdated/utils.py:14: OutdatedPackageWarning: The package pingouin is out of date. Your version is 0.5.3, the latest is 0.6.1.
Set the environment variable OUTDATED_IGNORE=1 to disable these warnings.
  return warn(

In [2]:
# def run(params):

### Parameters

In [3]:
""" try:
    dir = os.path.dirname(os.path.abspath(__file__))
except:
    dir = os.getcwd()
print(dir) """

' try:\n    dir = os.path.dirname(os.path.abspath(__file__))\nexcept:\n    dir = os.getcwd()\nprint(dir) '

In [4]:
dict_dataset = {
    1: ["Mentos_2_process_NormalizationFiltered_format", ["Orange"]], # new mentos,  for Metabolomics
    2: ["deybis_filter_september_2br_3ar_format", ["SecoAmazonas"]],
    3: ["deybis_filter_december_2br_3ar_format", ["SecoAmazonas"]],
    4: ["deybis_filter_september_2br_10ar_format", ["SecoAmazonas"]],
    5: ["deybis_filter_december_2br_10ar_format", ["SecoAmazonas"]], # for Metabolomics
    6: ["deybis_filter_september_min_2br_3ar_format", ["SecoAmazonas"]],
    7: ["deybis_filter_december_min_2br_3ar_format", ["SecoAmazonas"]],
    8: ["vanessa_december_2br_3ar_format", ["SecoAmazonas"]],
    9: ["Pablo_2br_14ar_format", ["AR"]],
    10: ["Pablo_2br_nar_format", ["AR"]],
    11: ["Pablo_2br_3ar_pn_42_format", ["AR"]],
    12: ["Pablo_2br_6ar_format", ["AR"]],
    13: ["Pablo_2br_3ar_p_42_format", ["AR"]],
    14: ["Pablo_2br_3ar_p_43_format", ["AR"]],
    15: ["Pablo_2br_3ar_p_44_format", ["AR"]],
    
    16: ["Pablo_2br_4ar_p_42_format", ["AR"]],
    17: ["Pablo_2br_4ar_p_43_format", ["AR"]],
    18: ["Pablo_2br_4ar_p_44_format", ["AR"]],
    19: ["Pablo_2br_8ar_p_42_format", ["AR"]],
	20: ["Pablo_2br_8ar_p_43_format", ["AR"]],
	21: ["Pablo_2br_8ar_p_44_format", ["AR"]],
	22: ["Pablo_2br_16ar_p_42_format", ["AR"]],
	23: ["Pablo_2br_16ar_p_43_format", ["AR"]],
	24: ["Pablo_2br_16ar_p_44_format", ["AR"]],
	25: ["Pablo_2br_mid_ar_p_42_format", ["AR"]],
	26: ["Pablo_2br_mid_ar_p_43_format", ["AR"]],
	27: ["Pablo_2br_mid_ar_p_44_format", ["AR"]],
	
	28: ["Pablo_2br_mid_sk_ar_p_42_format", ["AR"]],
	29: ["Pablo_2br_mid_sk_ar_p_43_format", ["AR"]],
	30: ["Pablo_2br_mid_sk_ar_p_44_format", ["AR"]],

	31: ["Pablo_new_2br_mid_ar_p_42_format", ["AR"]],
	32: ["Pablo_new_2br_mid_ar_p_43_format", ["AR"]],
	33: ["Pablo_new_2br_mid_ar_p_44_format", ["AR"]],
}
dataset = dict_dataset[31] # change
dataset

['Pablo_new_2br_mid_ar_p_42_format', ['AR']]

In [5]:
params = {
    "exp": "exp30", # Change
    "methods": ["t-gae"], # ["vgae-base", "argva-base", "vgae-line", "dgi-tran", "t-gae"],
    "data_variations": ["none"],
    "apply_transformation": False, # True or False
    "controls": dataset[1],
    "dimension": 64,
    "threshold_corr": 0.5,
    "threshold_log2": 0,
    "alpha": 0.05,
    "iterations": 1,
    "raw_data_file": dataset[0],
    "groups_id_no": ["Blank", "QC", "Std"],
    "sensitivity": False, # False: f1 (selectivity), True: f1 (selectivity), f2 (sensitivity)
    "obs": "",
    "seeds": [41, 42, 43, 44, 45, 46],
    
    "from": "python",
    "cuda": 0,
    "epochs": 500,
    "lr": 0.0001,
    "weight_decay": 1e-4,
    "patience": 10,
    "contamination": 0.1, # float in (0., 0.5)
    "n_jobs": 1, # -1 all
}

In [6]:
""" dir_path = "experiments/output"
res = sorted(os.listdir(dir_path))
n = len(res)
exp = "exp{}".format(n) """

exp = str(params["exp"])
exp

'exp30'

### Load dataset

In [7]:
# load dataset groups
if params["from"] == "python":
    df_raw = pd.read_csv("experiments/raw_data/{}.csv".format(params["raw_data_file"]), delimiter="|")
elif params["from"] == "drf":
    df_raw = pd.read_csv("{}".format(params["raw_data_file"]), delimiter="|") # from DRF
df_raw

,Alignment ID,Average Rt,Average Mz,Metabolite name,AR_1.1,AR_1.2,AR_1.3,AR_1.4,AR_1.5,AR_1.6,...,SKD_2.43,SKD_2.44,SKD_2.45,SKD_2.46,SKD_2.47,SKD_2.48,SKD_2.49,SKD_2.50,SKD_2.51,SKD_2.52
0,0,1.0,69.99951,Unknown,0.786205,0.836262,-0.975441,0.067434,-0.905178,0.458622,...,-0.906900,0.153942,0.230629,-0.554414,-0.477171,0.569892,-0.270328,-0.399430,-0.774251,0.137557
1,1,1.0,70.04025,Unknown,2.395434,2.572471,2.052794,2.617854,2.349623,2.501793,...,4.318123,1.830162,3.076034,2.600924,2.340488,2.455378,2.681824,3.990780,3.177152,2.460345
2,2,1.0,70.04151,Unknown,0.564810,1.888370,0.508263,1.088222,0.559000,1.711682,...,0.433149,1.329261,1.390541,0.725222,0.795335,1.667876,0.967726,0.861459,0.543210,1.315610
3,3,1.0,70.04908,Unknown,2.422679,2.258813,0.723078,1.880941,0.761319,2.569422,...,0.713647,1.878832,2.196732,1.111966,1.202515,2.758957,1.278797,1.290291,0.863953,1.861841
4,4,1.0,70.06267,Unknown,2.540917,1.170215,1.034535,1.659528,1.117443,2.654963,...,0.537261,1.570875,1.906110,0.870221,0.949140,2.417065,1.161074,1.024230,0.659277,1.554191
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5439,5439,1.0,732.79951,Unknown,0.506804,0.612721,0.196713,0.892378,0.475693,0.581129,...,0.017447,0.489837,0.594974,2.769619,0.122163,0.785278,0.310181,0.159557,2.217542,0.478689
5440,5440,1.0,748.76437,Unknown,0.628861,0.752324,0.284480,0.916754,0.590267,0.713625,...,0.189223,0.536927,0.717695,2.766869,0.254884,0.873304,0.465820,0.275240,1.985389,0.530473
5441,5441,1.0,794.79590,Unknown,1.839395,2.536197,2.495466,1.151250,0.635577,0.725910,...,2.326771,0.613551,0.719249,3.312826,2.469927,2.195082,2.051681,3.012239,2.383752,0.606691
5442,5442,1.0,800.81295,Unknown,2.041230,3.524770,1.454439,1.478938,1.043713,1.113634,...,2.322362,0.940685,0.965685,3.382798,0.657666,1.127591,0.712799,2.344157,2.588098,0.935822
5443,5443,1.0,860.74167,Unknown,0.058853,0.167473,-0.256118,0.344954,0.021154,0.131962,...,-0.501485,0.054474,0.219582,1.633410,-0.363146,0.434337,-0.115758,-0.326829,-0.476964,0.042163

### Format dataset

In [8]:
# apply transformation
columns_data = list(df_raw.columns)[4:]
if params["apply_transformation"]:
    print("transformation")
    for column in columns_data:
        df_raw[column] = df_raw[column].apply(lambda x: 10**x)
df_raw

,Alignment ID,Average Rt,Average Mz,Metabolite name,AR_1.1,AR_1.2,AR_1.3,AR_1.4,AR_1.5,AR_1.6,...,SKD_2.43,SKD_2.44,SKD_2.45,SKD_2.46,SKD_2.47,SKD_2.48,SKD_2.49,SKD_2.50,SKD_2.51,SKD_2.52
0,0,1.0,69.99951,Unknown,0.786205,0.836262,-0.975441,0.067434,-0.905178,0.458622,...,-0.906900,0.153942,0.230629,-0.554414,-0.477171,0.569892,-0.270328,-0.399430,-0.774251,0.137557
1,1,1.0,70.04025,Unknown,2.395434,2.572471,2.052794,2.617854,2.349623,2.501793,...,4.318123,1.830162,3.076034,2.600924,2.340488,2.455378,2.681824,3.990780,3.177152,2.460345
2,2,1.0,70.04151,Unknown,0.564810,1.888370,0.508263,1.088222,0.559000,1.711682,...,0.433149,1.329261,1.390541,0.725222,0.795335,1.667876,0.967726,0.861459,0.543210,1.315610
3,3,1.0,70.04908,Unknown,2.422679,2.258813,0.723078,1.880941,0.761319,2.569422,...,0.713647,1.878832,2.196732,1.111966,1.202515,2.758957,1.278797,1.290291,0.863953,1.861841
4,4,1.0,70.06267,Unknown,2.540917,1.170215,1.034535,1.659528,1.117443,2.654963,...,0.537261,1.570875,1.906110,0.870221,0.949140,2.417065,1.161074,1.024230,0.659277,1.554191
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5439,5439,1.0,732.79951,Unknown,0.506804,0.612721,0.196713,0.892378,0.475693,0.581129,...,0.017447,0.489837,0.594974,2.769619,0.122163,0.785278,0.310181,0.159557,2.217542,0.478689
5440,5440,1.0,748.76437,Unknown,0.628861,0.752324,0.284480,0.916754,0.590267,0.713625,...,0.189223,0.536927,0.717695,2.766869,0.254884,0.873304,0.465820,0.275240,1.985389,0.530473
5441,5441,1.0,794.79590,Unknown,1.839395,2.536197,2.495466,1.151250,0.635577,0.725910,...,2.326771,0.613551,0.719249,3.312826,2.469927,2.195082,2.051681,3.012239,2.383752,0.606691
5442,5442,1.0,800.81295,Unknown,2.041230,3.524770,1.454439,1.478938,1.043713,1.113634,...,2.322362,0.940685,0.965685,3.382798,0.657666,1.127591,0.712799,2.344157,2.588098,0.935822
5443,5443,1.0,860.74167,Unknown,0.058853,0.167473,-0.256118,0.344954,0.021154,0.131962,...,-0.501485,0.054474,0.219582,1.633410,-0.363146,0.434337,-0.115758,-0.326829,-0.476964,0.042163

In [9]:
# concat
df_join_raw = pd.concat([
    df_raw.iloc[:, :]], axis=1)
df_join_raw.set_index("Alignment ID", inplace=True)
df_join_raw

,Average Rt,Average Mz,Metabolite name,AR_1.1,AR_1.2,AR_1.3,AR_1.4,AR_1.5,AR_1.6,AR_1.7,...,SKD_2.43,SKD_2.44,SKD_2.45,SKD_2.46,SKD_2.47,SKD_2.48,SKD_2.49,SKD_2.50,SKD_2.51,SKD_2.52
Alignment ID,,,,,,,,,,,,,,,,,,,,,
0,1.0,69.99951,Unknown,0.786205,0.836262,-0.975441,0.067434,-0.905178,0.458622,-0.756562,...,-0.906900,0.153942,0.230629,-0.554414,-0.477171,0.569892,-0.270328,-0.399430,-0.774251,0.137557
1,1.0,70.04025,Unknown,2.395434,2.572471,2.052794,2.617854,2.349623,2.501793,2.941043,...,4.318123,1.830162,3.076034,2.600924,2.340488,2.455378,2.681824,3.990780,3.177152,2.460345
2,1.0,70.04151,Unknown,0.564810,1.888370,0.508263,1.088222,0.559000,1.711682,0.639700,...,0.433149,1.329261,1.390541,0.725222,0.795335,1.667876,0.967726,0.861459,0.543210,1.315610
3,1.0,70.04908,Unknown,2.422679,2.258813,0.723078,1.880941,0.761319,2.569422,0.801526,...,0.713647,1.878832,2.196732,1.111966,1.202515,2.758957,1.278797,1.290291,0.863953,1.861841
4,1.0,70.06267,Unknown,2.540917,1.170215,1.034535,1.659528,1.117443,2.654963,1.274813,...,0.537261,1.570875,1.906110,0.870221,0.949140,2.417065,1.161074,1.024230,0.659277,1.554191
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5439,1.0,732.79951,Unknown,0.506804,0.612721,0.196713,0.892378,0.475693,0.581129,0.890705,...,0.017447,0.489837,0.594974,2.769619,0.122163,0.785278,0.310181,0.159557,2.217542,0.478689
5440,1.0,748.76437,Unknown,0.628861,0.752324,0.284480,0.916754,0.590267,0.713625,1.069844,...,0.189223,0.536927,0.717695,2.766869,0.254884,0.873304,0.465820,0.275240,1.985389,0.530473
5441,1.0,794.79590,Unknown,1.839395,2.536197,2.495466,1.151250,0.635577,0.725910,0.968171,...,2.326771,0.613551,0.719249,3.312826,2.469927,2.195082,2.051681,3.012239,2.383752,0.606691
5442,1.0,800.81295,Unknown,2.041230,3.524770,1.454439,1.478938,1.043713,1.113634,1.284358,...,2.322362,0.940685,0.965685,3.382798,0.657666,1.127591,0.712799,2.344157,2.588098,0.935822
5443,1.0,860.74167,Unknown,0.058853,0.167473,-0.256118,0.344954,0.021154,0.131962,0.460754,...,-0.501485,0.054474,0.219582,1.633410,-0.363146,0.434337,-0.115758,-0.326829,-0.476964,0.042163

In [10]:
# split
df_join_raw = df_join_raw.rename_axis(None)
# df_join_raw = df_join_raw.iloc[:, 2:]
df_join_raw

,Average Rt,Average Mz,Metabolite name,AR_1.1,AR_1.2,AR_1.3,AR_1.4,AR_1.5,AR_1.6,AR_1.7,...,SKD_2.43,SKD_2.44,SKD_2.45,SKD_2.46,SKD_2.47,SKD_2.48,SKD_2.49,SKD_2.50,SKD_2.51,SKD_2.52
0,1.0,69.99951,Unknown,0.786205,0.836262,-0.975441,0.067434,-0.905178,0.458622,-0.756562,...,-0.906900,0.153942,0.230629,-0.554414,-0.477171,0.569892,-0.270328,-0.399430,-0.774251,0.137557
1,1.0,70.04025,Unknown,2.395434,2.572471,2.052794,2.617854,2.349623,2.501793,2.941043,...,4.318123,1.830162,3.076034,2.600924,2.340488,2.455378,2.681824,3.990780,3.177152,2.460345
2,1.0,70.04151,Unknown,0.564810,1.888370,0.508263,1.088222,0.559000,1.711682,0.639700,...,0.433149,1.329261,1.390541,0.725222,0.795335,1.667876,0.967726,0.861459,0.543210,1.315610
3,1.0,70.04908,Unknown,2.422679,2.258813,0.723078,1.880941,0.761319,2.569422,0.801526,...,0.713647,1.878832,2.196732,1.111966,1.202515,2.758957,1.278797,1.290291,0.863953,1.861841
4,1.0,70.06267,Unknown,2.540917,1.170215,1.034535,1.659528,1.117443,2.654963,1.274813,...,0.537261,1.570875,1.906110,0.870221,0.949140,2.417065,1.161074,1.024230,0.659277,1.554191
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5439,1.0,732.79951,Unknown,0.506804,0.612721,0.196713,0.892378,0.475693,0.581129,0.890705,...,0.017447,0.489837,0.594974,2.769619,0.122163,0.785278,0.310181,0.159557,2.217542,0.478689
5440,1.0,748.76437,Unknown,0.628861,0.752324,0.284480,0.916754,0.590267,0.713625,1.069844,...,0.189223,0.536927,0.717695,2.766869,0.254884,0.873304,0.465820,0.275240,1.985389,0.530473
5441,1.0,794.79590,Unknown,1.839395,2.536197,2.495466,1.151250,0.635577,0.725910,0.968171,...,2.326771,0.613551,0.719249,3.312826,2.469927,2.195082,2.051681,3.012239,2.383752,0.606691
5442,1.0,800.81295,Unknown,2.041230,3.524770,1.454439,1.478938,1.043713,1.113634,1.284358,...,2.322362,0.940685,0.965685,3.382798,0.657666,1.127591,0.712799,2.344157,2.588098,0.935822
5443,1.0,860.74167,Unknown,0.058853,0.167473,-0.256118,0.344954,0.021154,0.131962,0.460754,...,-0.501485,0.054474,0.219582,1.633410,-0.363146,0.434337,-0.115758,-0.326829,-0.476964,0.042163

In [11]:
# get groups name
groups_id_no = params["groups_id_no"]
groups_id = []
for item in df_join_raw.iloc[:, 3:].columns.values:
    group_id = item.split("_")[0]
    if group_id not in groups_id and group_id not in groups_id_no:
        groups_id.append(group_id)
groups_id

['AR',
 'BC',
 'BPH',
 'CKD-Mild',
 'CKD-Moderate',
 'CKD-Severe',
 'CKD5-HD',
 'CKD5-PD',
 'CRS',
 'Health',
 'LPRD',
 'LSNB',
 'OSA',
 'PCa',
 'PD',
 'RCC',
 'SGB',
 'SKD']

In [12]:
# delete no sample columns
""" columns_delete = [columna for columna in df_join_raw.columns if columna.split("_")[0] in columns_no_sample]
df_join_raw.drop(columns_delete, axis=1, inplace=True)
df_join_raw """

' columns_delete = [columna for columna in df_join_raw.columns if columna.split("_")[0] in columns_no_sample]\ndf_join_raw.drop(columns_delete, axis=1, inplace=True)\ndf_join_raw '

In [13]:
# get subgroups names

""" def get_subgroups_id(df_join_raw, groups, by_group=False):
    dict_groups_id = {}
    for group in groups:
        # get group
        if by_group:
            dict_groups_id[group] = ["1"]
        else:
            columns = list(df_join_raw.filter(like=group).columns)
            subgroups = [item.split("{}_".format(group))[1].split(".")[0] for item in columns]
            subgroups = np.unique(subgroups)
            dict_groups_id[group] = subgroups.tolist()
    return dict_groups_id """

subgroups_id = get_subgroups_id(df_join_raw, groups_id)
subgroups_id

{'AR': ['1', '2'],
 'BC': ['1', '2'],
 'BPH': ['1', '2'],
 'CKD-Mild': ['1', '2'],
 'CKD-Moderate': ['1', '2'],
 'CKD-Severe': ['1', '2'],
 'CKD5-HD': ['1', '2'],
 'CKD5-PD': ['1', '2'],
 'CRS': ['1', '2'],
 'Health': ['1', '2'],
 'LPRD': ['1', '2'],
 'LSNB': ['1', '2'],
 'OSA': ['1', '2'],
 'PCa': ['1', '2'],
 'PD': ['1', '2'],
 'RCC': ['1', '2'],
 'SGB': ['1', '2'],
 'SKD': ['1', '2']}

In [14]:
# count analtical repetitions
# df_join_raw.filter(like="AA_1.")

In [15]:
# check distribution

In [16]:
""" x = df_join_raw.iloc[2, 3:]
print(x.min(), x.max(), x.mean())
x.hist(bins=200) """

' x = df_join_raw.iloc[2, 3:]\nprint(x.min(), x.max(), x.mean())\nx.hist(bins=200) '

In [17]:
# f_join_raw.iloc[:, 5].hist(bins=100)

In [18]:
params["controls"], groups_id

(['AR'],
 ['AR',
  'BC',
  'BPH',
  'CKD-Mild',
  'CKD-Moderate',
  'CKD-Severe',
  'CKD5-HD',
  'CKD5-PD',
  'CRS',
  'Health',
  'LPRD',
  'LSNB',
  'OSA',
  'PCa',
  'PD',
  'RCC',
  'SGB',
  'SKD'])

In [19]:
# get groups combination
groups = []
controls = params["controls"]

groups = []
for control in controls:
    for group_id in groups_id:
        if control != group_id:
            groups.append([control, group_id])
print(groups)

[['AR', 'BC'], ['AR', 'BPH'], ['AR', 'CKD-Mild'], ['AR', 'CKD-Moderate'], ['AR', 'CKD-Severe'], ['AR', 'CKD5-HD'], ['AR', 'CKD5-PD'], ['AR', 'CRS'], ['AR', 'Health'], ['AR', 'LPRD'], ['AR', 'LSNB'], ['AR', 'OSA'], ['AR', 'PCa'], ['AR', 'PD'], ['AR', 'RCC'], ['AR', 'SGB'], ['AR', 'SKD']]

### Create folders

In [20]:
# create experiments folder
try: 
    os.mkdir("experiments/output/{}".format(exp))
    os.mkdir("experiments/output/{}/correlations".format(exp))
    os.mkdir("experiments/output/{}/preprocessing".format(exp))
    os.mkdir("experiments/output/{}/preprocessing/edges".format(exp))
    os.mkdir("experiments/output/{}/preprocessing/graphs_data".format(exp))
    os.mkdir("experiments/output/{}/loss".format(exp))
    os.mkdir("experiments/output/{}/node_embeddings".format(exp))
    os.mkdir("experiments/output/{}/common_nodes".format(exp))
    os.mkdir("experiments/output/{}/filter_raw".format(exp))
    os.mkdir("experiments/output/{}/plots".format(exp))
except OSError as error: 
    print(error)

### Save dataset and parameters

In [21]:
# save dataset
df_join_raw.to_csv("experiments/input/{}_raw.csv".format(exp), index=True)

# save parameters
parameters = {
    "exp": exp,
    "methods": params["methods"],
    "data_variations": params["data_variations"],
    "apply_transformation": params["apply_transformation"],
    "controls": params["controls"],
    "dimension": params["dimension"],
    "threshold_corr": params["threshold_corr"],
    "threshold_log2": params["threshold_log2"],
    "alpha": params["alpha"],
    "iterations": params["iterations"],
    "raw_data_file": params["raw_data_file"],
    "groups_id": groups_id,
    "subgroups_id": subgroups_id,
    "groups": groups,
    "groups_id_no": params["groups_id_no"],
    "sensitivity": params["sensitivity"],
    
    "from": params["from"],
    "cuda": params["cuda"],
    "epochs": params["epochs"],
    "lr": params["lr"],
    "weight_decay": params["weight_decay"],
    "patience": params["patience"],
    "contamination": params["contamination"],
    "n_jobs": params["n_jobs"],

    "seeds": params["seeds"],
    "obs": params["obs"]
}

with open("experiments/output/{}/parameters.json".format(exp), "w") as outfile:
    json.dump(parameters, outfile, indent=4)

In [22]:
experiments = {
    "exp": exp
}

with open("exp.json".format(experiments), "w") as outfile:
    json.dump(experiments, outfile, indent=4)

In [23]:
# return exp