### Imports

In [24]:
import json
import os
import pandas as pd

from utils_MS import *

# %load_ext autotime

In [25]:
# def run(params):

### Parameters

In [26]:
""" try:
    dir = os.path.dirname(os.path.abspath(__file__))
except:
    dir = os.getcwd()
print(dir) """

' try:\n    dir = os.path.dirname(os.path.abspath(__file__))\nexcept:\n    dir = os.getcwd()\nprint(dir) '

In [27]:
dict_dataset = {
    1: ["Mentos_2_process_NormalizationFiltered_format", ["Orange"]], # new mentos,  for Metabolomics
    2: ["deybis_filter_september_2br_3ar_format", ["SecoAmazonas"]],
    3: ["deybis_filter_december_2br_3ar_format", ["SecoAmazonas"]],
    4: ["deybis_filter_september_2br_10ar_format", ["SecoAmazonas"]],
    5: ["deybis_filter_december_2br_10ar_format", ["SecoAmazonas"]], # for Metabolomics
    6: ["deybis_filter_september_min_2br_3ar_format", ["SecoAmazonas"]],
    7: ["deybis_filter_december_min_2br_3ar_format", ["SecoAmazonas"]],
    8: ["vanessa_december_2br_3ar_format", ["SecoAmazonas"]],
    9: ["Pablo_2br_14ar_format", ["AR"]],
    10: ["Pablo_2br_nar_format", ["AR"]],
    11: ["Pablo_2br_3ar_pn_42_format", ["AR"]],
    12: ["Pablo_2br_6ar_format", ["AR"]],
    13: ["Pablo_2br_3ar_p_42_format", ["AR"]],
    14: ["Pablo_2br_3ar_p_43_format", ["AR"]],
    15: ["Pablo_2br_3ar_p_44_format", ["AR"]],
    
    16: ["Pablo_2br_4ar_p_42_format", ["AR"]],
    17: ["Pablo_2br_4ar_p_43_format", ["AR"]],
    18: ["Pablo_2br_4ar_p_44_format", ["AR"]],
    19: ["Pablo_2br_8ar_p_42_format", ["AR"]],
	20: ["Pablo_2br_8ar_p_43_format", ["AR"]],
	21: ["Pablo_2br_8ar_p_44_format", ["AR"]],
	22: ["Pablo_2br_16ar_p_42_format", ["AR"]],
	23: ["Pablo_2br_16ar_p_43_format", ["AR"]],
	24: ["Pablo_2br_16ar_p_44_format", ["AR"]],
	25: ["Pablo_2br_mid_ar_p_42_format", ["AR"]],
	26: ["Pablo_2br_mid_ar_p_43_format", ["AR"]],
	27: ["Pablo_2br_mid_ar_p_44_format", ["AR"]],
	
	28: ["Pablo_2br_mid_sk_ar_p_42_format", ["AR"]],
	29: ["Pablo_2br_mid_sk_ar_p_43_format", ["AR"]],
	30: ["Pablo_2br_mid_sk_ar_p_44_format", ["AR"]],

	31: ["Pablo_new_2br_mid_ar_p_42_format", ["AR"]],
	32: ["Pablo_new_2br_mid_ar_p_43_format", ["AR"]],
	33: ["Pablo_new_2br_mid_ar_p_44_format", ["AR"]],
	
	34: ["Pablo_new_2br_N_ar_p_42_format", ["AR"]],
	35: ["Pablo_new_2br_N_ar_p_43_format", ["AR"]],
	36: ["Pablo_new_2br_N_ar_p_44_format", ["AR"]],

	37: ["Pablo_new_N_br_M_ar_p_42_format", ["AR"]],
}
dataset = dict_dataset[37] # change
dataset

['Pablo_new_N_br_M_ar_p_42_format', ['AR']]

In [28]:
params = {
    "exp": "exp102", # Change
    "methods": ["t-gae"], # ["vgae-base", "argva-base", "vgae-line", "dgi-tran", "t-gae"],
    "data_variations": ["none"],
    "apply_transformation": False, # True or False
    "controls": dataset[1],
    "dimension": 64,
    "threshold_corr": 0.5,
    "threshold_log2": 0,
    "alpha": 0.05,
    "iterations": 1,
    "raw_data_file": dataset[0],
    "groups_id_no": ["Blank", "QC", "Std"],
    "sensitivity": False, # False: f1 (selectivity), True: f1 (selectivity), f2 (sensitivity)
    "obs": "",
    "seeds": [41, 42, 43, 44, 45, 46],
    
    "from": "python",
    "cuda": 0,
    "epochs": 500,
    "lr": 0.0001,
    "weight_decay": 1e-4,
    "patience": 10,
    "contamination": 0.1, # float in (0., 0.5)
    "n_jobs": 1, # -1 all
}

In [29]:
""" dir_path = "experiments/output"
res = sorted(os.listdir(dir_path))
n = len(res)
exp = "exp{}".format(n) """

exp = str(params["exp"])
exp

'exp102'

### Load dataset

In [30]:
# load dataset groups
if params["from"] == "python":
    df_raw = pd.read_csv("experiments/raw_data/{}.csv".format(params["raw_data_file"]), delimiter="|")
elif params["from"] == "drf":
    df_raw = pd.read_csv("{}".format(params["raw_data_file"]), delimiter="|") # from DRF
df_raw

,Alignment ID,Average Rt,Average Mz,Metabolite name,disease_1.1,disease_1.2,disease_1.3,disease_1.4,disease_1.5,disease_1.6,...,disease_18.96,disease_18.97,disease_18.98,disease_18.99,disease_18.100,disease_18.101,disease_18.102,disease_18.103,disease_18.104,disease_18.105
0,0,1.0,69.99951,Unknown,0.469752,-0.828568,-0.827568,0.200746,0.307196,0.509462,...,-0.729955,-0.248259,-0.270328,0.018966,0.016301,0.002993,-0.002321,-0.631255,0.037658,-0.167405
1,1,1.0,70.04025,Unknown,4.717494,2.647113,2.649208,2.651302,2.657570,2.659655,...,2.541524,2.410119,2.681824,1.790231,2.492337,2.168390,1.797099,3.568087,1.990979,2.795018
2,2,1.0,70.04151,Unknown,1.699017,1.924916,0.604168,1.560021,1.636312,1.426482,...,0.574928,0.988399,0.967726,1.214311,1.212080,1.200939,1.196488,0.657424,1.229950,1.057784
3,3,1.0,70.04908,Unknown,2.646457,0.766210,2.297061,2.267749,2.427032,2.043593,...,0.913754,1.323937,1.278797,1.735250,1.732453,1.718473,1.712885,1.024026,1.754852,1.540681
4,4,1.0,70.06267,Unknown,2.798181,1.189463,1.190252,1.191041,2.456294,1.192615,...,0.701041,1.192136,1.161074,1.434289,1.431611,1.418250,1.412920,0.794569,1.453092,1.248657
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5439,5439,1.0,732.79951,Unknown,0.502054,0.654775,1.824769,0.656963,0.663514,0.665692,...,2.599980,0.328132,0.310181,0.421443,0.419606,0.412262,0.410427,0.072420,0.428798,0.308473
5440,5440,1.0,748.76437,Unknown,0.623760,0.806753,0.809089,0.811422,0.818408,0.820732,...,2.643091,0.482493,0.465820,1.871109,0.493498,0.485489,0.482288,0.222039,1.651601,0.399560
5441,5441,1.0,794.79590,Unknown,0.667099,0.792504,0.794923,2.596137,3.115424,3.171670,...,0.301803,0.451295,2.051681,2.173131,0.568968,0.562109,0.558680,0.315719,2.405655,0.493483
5442,5442,1.0,800.81295,Unknown,1.067389,1.154493,1.156508,2.621274,2.978477,3.126827,...,3.050052,0.731652,0.712799,2.145547,0.887204,1.819582,0.879101,2.786172,2.458741,0.804493
5443,5443,1.0,860.74167,Unknown,0.056521,0.213122,0.215270,0.217416,0.223839,0.225976,...,-0.461852,-0.098697,-0.115758,-0.036997,-0.039008,-0.049052,-0.053063,1.755878,-0.026927,-0.164096

### Format dataset

In [31]:
# apply transformation
columns_data = list(df_raw.columns)[4:]
if params["apply_transformation"]:
    print("transformation")
    for column in columns_data:
        df_raw[column] = df_raw[column].apply(lambda x: 10**x)
df_raw

,Alignment ID,Average Rt,Average Mz,Metabolite name,disease_1.1,disease_1.2,disease_1.3,disease_1.4,disease_1.5,disease_1.6,...,disease_18.96,disease_18.97,disease_18.98,disease_18.99,disease_18.100,disease_18.101,disease_18.102,disease_18.103,disease_18.104,disease_18.105
0,0,1.0,69.99951,Unknown,0.469752,-0.828568,-0.827568,0.200746,0.307196,0.509462,...,-0.729955,-0.248259,-0.270328,0.018966,0.016301,0.002993,-0.002321,-0.631255,0.037658,-0.167405
1,1,1.0,70.04025,Unknown,4.717494,2.647113,2.649208,2.651302,2.657570,2.659655,...,2.541524,2.410119,2.681824,1.790231,2.492337,2.168390,1.797099,3.568087,1.990979,2.795018
2,2,1.0,70.04151,Unknown,1.699017,1.924916,0.604168,1.560021,1.636312,1.426482,...,0.574928,0.988399,0.967726,1.214311,1.212080,1.200939,1.196488,0.657424,1.229950,1.057784
3,3,1.0,70.04908,Unknown,2.646457,0.766210,2.297061,2.267749,2.427032,2.043593,...,0.913754,1.323937,1.278797,1.735250,1.732453,1.718473,1.712885,1.024026,1.754852,1.540681
4,4,1.0,70.06267,Unknown,2.798181,1.189463,1.190252,1.191041,2.456294,1.192615,...,0.701041,1.192136,1.161074,1.434289,1.431611,1.418250,1.412920,0.794569,1.453092,1.248657
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5439,5439,1.0,732.79951,Unknown,0.502054,0.654775,1.824769,0.656963,0.663514,0.665692,...,2.599980,0.328132,0.310181,0.421443,0.419606,0.412262,0.410427,0.072420,0.428798,0.308473
5440,5440,1.0,748.76437,Unknown,0.623760,0.806753,0.809089,0.811422,0.818408,0.820732,...,2.643091,0.482493,0.465820,1.871109,0.493498,0.485489,0.482288,0.222039,1.651601,0.399560
5441,5441,1.0,794.79590,Unknown,0.667099,0.792504,0.794923,2.596137,3.115424,3.171670,...,0.301803,0.451295,2.051681,2.173131,0.568968,0.562109,0.558680,0.315719,2.405655,0.493483
5442,5442,1.0,800.81295,Unknown,1.067389,1.154493,1.156508,2.621274,2.978477,3.126827,...,3.050052,0.731652,0.712799,2.145547,0.887204,1.819582,0.879101,2.786172,2.458741,0.804493
5443,5443,1.0,860.74167,Unknown,0.056521,0.213122,0.215270,0.217416,0.223839,0.225976,...,-0.461852,-0.098697,-0.115758,-0.036997,-0.039008,-0.049052,-0.053063,1.755878,-0.026927,-0.164096

In [32]:
# concat
df_join_raw = pd.concat([
    df_raw.iloc[:, :]], axis=1)
df_join_raw.set_index("Alignment ID", inplace=True)
df_join_raw

,Average Rt,Average Mz,Metabolite name,disease_1.1,disease_1.2,disease_1.3,disease_1.4,disease_1.5,disease_1.6,disease_1.7,...,disease_18.96,disease_18.97,disease_18.98,disease_18.99,disease_18.100,disease_18.101,disease_18.102,disease_18.103,disease_18.104,disease_18.105
Alignment ID,,,,,,,,,,,,,,,,,,,,,
0,1.0,69.99951,Unknown,0.469752,-0.828568,-0.827568,0.200746,0.307196,0.509462,-0.825574,...,-0.729955,-0.248259,-0.270328,0.018966,0.016301,0.002993,-0.002321,-0.631255,0.037658,-0.167405
1,1.0,70.04025,Unknown,4.717494,2.647113,2.649208,2.651302,2.657570,2.659655,4.784085,...,2.541524,2.410119,2.681824,1.790231,2.492337,2.168390,1.797099,3.568087,1.990979,2.795018
2,1.0,70.04151,Unknown,1.699017,1.924916,0.604168,1.560021,1.636312,1.426482,1.514371,...,0.574928,0.988399,0.967726,1.214311,1.212080,1.200939,1.196488,0.657424,1.229950,1.057784
3,1.0,70.04908,Unknown,2.646457,0.766210,2.297061,2.267749,2.427032,2.043593,2.650094,...,0.913754,1.323937,1.278797,1.735250,1.732453,1.718473,1.712885,1.024026,1.754852,1.540681
4,1.0,70.06267,Unknown,2.798181,1.189463,1.190252,1.191041,2.456294,1.192615,2.864629,...,0.701041,1.192136,1.161074,1.434289,1.431611,1.418250,1.412920,0.794569,1.453092,1.248657
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5439,1.0,732.79951,Unknown,0.502054,0.654775,1.824769,0.656963,0.663514,0.665692,4.044635,...,2.599980,0.328132,0.310181,0.421443,0.419606,0.412262,0.410427,0.072420,0.428798,0.308473
5440,1.0,748.76437,Unknown,0.623760,0.806753,0.809089,0.811422,0.818408,0.820732,4.036585,...,2.643091,0.482493,0.465820,1.871109,0.493498,0.485489,0.482288,0.222039,1.651601,0.399560
5441,1.0,794.79590,Unknown,0.667099,0.792504,0.794923,2.596137,3.115424,3.171670,3.684022,...,0.301803,0.451295,2.051681,2.173131,0.568968,0.562109,0.558680,0.315719,2.405655,0.493483
5442,1.0,800.81295,Unknown,1.067389,1.154493,1.156508,2.621274,2.978477,3.126827,4.014572,...,3.050052,0.731652,0.712799,2.145547,0.887204,1.819582,0.879101,2.786172,2.458741,0.804493
5443,1.0,860.74167,Unknown,0.056521,0.213122,0.215270,0.217416,0.223839,0.225976,3.568362,...,-0.461852,-0.098697,-0.115758,-0.036997,-0.039008,-0.049052,-0.053063,1.755878,-0.026927,-0.164096

In [33]:
# split
df_join_raw = df_join_raw.rename_axis(None)
# df_join_raw = df_join_raw.iloc[:, 2:]
df_join_raw

,Average Rt,Average Mz,Metabolite name,disease_1.1,disease_1.2,disease_1.3,disease_1.4,disease_1.5,disease_1.6,disease_1.7,...,disease_18.96,disease_18.97,disease_18.98,disease_18.99,disease_18.100,disease_18.101,disease_18.102,disease_18.103,disease_18.104,disease_18.105
0,1.0,69.99951,Unknown,0.469752,-0.828568,-0.827568,0.200746,0.307196,0.509462,-0.825574,...,-0.729955,-0.248259,-0.270328,0.018966,0.016301,0.002993,-0.002321,-0.631255,0.037658,-0.167405
1,1.0,70.04025,Unknown,4.717494,2.647113,2.649208,2.651302,2.657570,2.659655,4.784085,...,2.541524,2.410119,2.681824,1.790231,2.492337,2.168390,1.797099,3.568087,1.990979,2.795018
2,1.0,70.04151,Unknown,1.699017,1.924916,0.604168,1.560021,1.636312,1.426482,1.514371,...,0.574928,0.988399,0.967726,1.214311,1.212080,1.200939,1.196488,0.657424,1.229950,1.057784
3,1.0,70.04908,Unknown,2.646457,0.766210,2.297061,2.267749,2.427032,2.043593,2.650094,...,0.913754,1.323937,1.278797,1.735250,1.732453,1.718473,1.712885,1.024026,1.754852,1.540681
4,1.0,70.06267,Unknown,2.798181,1.189463,1.190252,1.191041,2.456294,1.192615,2.864629,...,0.701041,1.192136,1.161074,1.434289,1.431611,1.418250,1.412920,0.794569,1.453092,1.248657
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5439,1.0,732.79951,Unknown,0.502054,0.654775,1.824769,0.656963,0.663514,0.665692,4.044635,...,2.599980,0.328132,0.310181,0.421443,0.419606,0.412262,0.410427,0.072420,0.428798,0.308473
5440,1.0,748.76437,Unknown,0.623760,0.806753,0.809089,0.811422,0.818408,0.820732,4.036585,...,2.643091,0.482493,0.465820,1.871109,0.493498,0.485489,0.482288,0.222039,1.651601,0.399560
5441,1.0,794.79590,Unknown,0.667099,0.792504,0.794923,2.596137,3.115424,3.171670,3.684022,...,0.301803,0.451295,2.051681,2.173131,0.568968,0.562109,0.558680,0.315719,2.405655,0.493483
5442,1.0,800.81295,Unknown,1.067389,1.154493,1.156508,2.621274,2.978477,3.126827,4.014572,...,3.050052,0.731652,0.712799,2.145547,0.887204,1.819582,0.879101,2.786172,2.458741,0.804493
5443,1.0,860.74167,Unknown,0.056521,0.213122,0.215270,0.217416,0.223839,0.225976,3.568362,...,-0.461852,-0.098697,-0.115758,-0.036997,-0.039008,-0.049052,-0.053063,1.755878,-0.026927,-0.164096

In [34]:
# get groups name
groups_id_no = params["groups_id_no"]
groups_id = []
for item in df_join_raw.iloc[:, 3:].columns.values:
    group_id = item.split("_")[0]
    if group_id not in groups_id and group_id not in groups_id_no:
        groups_id.append(group_id)
groups_id

['disease']

In [35]:
# delete no sample columns
""" columns_delete = [columna for columna in df_join_raw.columns if columna.split("_")[0] in columns_no_sample]
df_join_raw.drop(columns_delete, axis=1, inplace=True)
df_join_raw """

' columns_delete = [columna for columna in df_join_raw.columns if columna.split("_")[0] in columns_no_sample]\ndf_join_raw.drop(columns_delete, axis=1, inplace=True)\ndf_join_raw '

In [36]:
# get subgroups names

""" def get_subgroups_id(df_join_raw, groups, by_group=False):
    dict_groups_id = {}
    for group in groups:
        # get group
        if by_group:
            dict_groups_id[group] = ["1"]
        else:
            columns = list(df_join_raw.filter(like=group).columns)
            subgroups = [item.split("{}_".format(group))[1].split(".")[0] for item in columns]
            subgroups = np.unique(subgroups)
            dict_groups_id[group] = subgroups.tolist()
    return dict_groups_id """

subgroups_id = get_subgroups_id(df_join_raw, groups_id)
subgroups_id

{'disease': ['1',
  '10',
  '11',
  '12',
  '13',
  '14',
  '15',
  '16',
  '17',
  '18',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9']}

In [37]:
# count analtical repetitions
# df_join_raw.filter(like="AA_1.")

In [38]:
# check distribution

In [39]:
""" x = df_join_raw.iloc[2, 3:]
print(x.min(), x.max(), x.mean())
x.hist(bins=200) """

' x = df_join_raw.iloc[2, 3:]\nprint(x.min(), x.max(), x.mean())\nx.hist(bins=200) '

In [40]:
# f_join_raw.iloc[:, 5].hist(bins=100)

In [41]:
params["controls"], groups_id

(['AR'], ['disease'])

In [42]:
# get groups combination
groups = []
controls = params["controls"]

groups = []
for control in controls:
    for group_id in groups_id:
        if control != group_id:
            groups.append([control, group_id])
print(groups)

[['AR', 'disease']]

### Create folders

In [43]:
# create experiments folder
try: 
    os.mkdir("experiments/output/{}".format(exp))
    os.mkdir("experiments/output/{}/correlations".format(exp))
    os.mkdir("experiments/output/{}/preprocessing".format(exp))
    os.mkdir("experiments/output/{}/preprocessing/edges".format(exp))
    os.mkdir("experiments/output/{}/preprocessing/graphs_data".format(exp))
    os.mkdir("experiments/output/{}/loss".format(exp))
    os.mkdir("experiments/output/{}/node_embeddings".format(exp))
    os.mkdir("experiments/output/{}/common_nodes".format(exp))
    os.mkdir("experiments/output/{}/filter_raw".format(exp))
    os.mkdir("experiments/output/{}/plots".format(exp))
except OSError as error: 
    print(error)

### Save dataset and parameters

In [44]:
# save dataset
df_join_raw.to_csv("experiments/input/{}_raw.csv".format(exp), index=True)

# save parameters
parameters = {
    "exp": exp,
    "methods": params["methods"],
    "data_variations": params["data_variations"],
    "apply_transformation": params["apply_transformation"],
    "controls": params["controls"],
    "dimension": params["dimension"],
    "threshold_corr": params["threshold_corr"],
    "threshold_log2": params["threshold_log2"],
    "alpha": params["alpha"],
    "iterations": params["iterations"],
    "raw_data_file": params["raw_data_file"],
    "groups_id": groups_id,
    "subgroups_id": subgroups_id,
    "groups": groups,
    "groups_id_no": params["groups_id_no"],
    "sensitivity": params["sensitivity"],
    
    "from": params["from"],
    "cuda": params["cuda"],
    "epochs": params["epochs"],
    "lr": params["lr"],
    "weight_decay": params["weight_decay"],
    "patience": params["patience"],
    "contamination": params["contamination"],
    "n_jobs": params["n_jobs"],

    "seeds": params["seeds"],
    "obs": params["obs"]
}

with open("experiments/output/{}/parameters.json".format(exp), "w") as outfile:
    json.dump(parameters, outfile, indent=4)

In [45]:
experiments = {
    "exp": exp
}

with open("exp.json".format(experiments), "w") as outfile:
    json.dump(experiments, outfile, indent=4)

In [46]:
# return exp