### Imports

In [1]:
import json
import os
import pandas as pd

from utils_MS import *

# %load_ext autotime

/home/ealvarez/miniconda3/envs/graph_matching/lib/python3.10/site-packages/outdated/utils.py:14: OutdatedPackageWarning: The package pingouin is out of date. Your version is 0.5.3, the latest is 0.6.1.
Set the environment variable OUTDATED_IGNORE=1 to disable these warnings.
  return warn(

In [2]:
# def run(params):

### Parameters

In [3]:
""" try:
    dir = os.path.dirname(os.path.abspath(__file__))
except:
    dir = os.getcwd()
print(dir) """

' try:\n    dir = os.path.dirname(os.path.abspath(__file__))\nexcept:\n    dir = os.getcwd()\nprint(dir) '

In [4]:
dict_dataset = {
    1: ["Mentos_2_process_NormalizationFiltered_format", ["Orange"]], # new mentos,  for Metabolomics
    2: ["deybis_filter_september_2br_3ar_format", ["SecoAmazonas"]],
    3: ["deybis_filter_december_2br_3ar_format", ["SecoAmazonas"]],
    4: ["deybis_filter_september_2br_10ar_format", ["SecoAmazonas"]],
    5: ["deybis_filter_december_2br_10ar_format", ["SecoAmazonas"]], # for Metabolomics
    6: ["deybis_filter_september_min_2br_3ar_format", ["SecoAmazonas"]],
    7: ["deybis_filter_december_min_2br_3ar_format", ["SecoAmazonas"]],
    8: ["vanessa_december_2br_3ar_format", ["SecoAmazonas"]],
    9: ["Pablo_2br_14ar_format", ["AR"]],
    10: ["Pablo_2br_nar_format", ["AR"]],
    11: ["Pablo_2br_3ar_pn_42_format", ["AR"]],
    12: ["Pablo_2br_6ar_format", ["AR"]],
    13: ["Pablo_2br_3ar_p_42_format", ["AR"]],
    14: ["Pablo_2br_3ar_p_43_format", ["AR"]],
}
dataset = dict_dataset[14] # change
dataset

['Pablo_2br_3ar_p_43_format', ['AR']]

In [5]:
params = {
    "exp": "exp13", # Change
    "methods": ["t-gae"], # ["vgae-base", "argva-base", "vgae-line", "dgi-tran", "t-gae"],
    "data_variations": ["none"],
    "apply_transformation": False, # True or False
    "controls": dataset[1],
    "dimension": 64,
    "threshold_corr": 0.5,
    "threshold_log2": 0,
    "alpha": 0.05,
    "iterations": 1,
    "raw_data_file": dataset[0],
    "groups_id_no": ["Blank", "QC", "Std"],
    "sensitivity": False, # False: f1 (selectivity), True: f1 (selectivity), f2 (sensitivity)
    "obs": "",
    "seeds": [41, 42, 43, 44, 45, 46],
    
    "from": "python",
    "cuda": 0,
    "epochs": 500,
    "lr": 0.0001,
    "weight_decay": 1e-4,
    "patience": 10,
    "contamination": 0.1, # float in (0., 0.5)
    "n_jobs": 1, # -1 all
}

In [6]:
""" dir_path = "experiments/output"
res = sorted(os.listdir(dir_path))
n = len(res)
exp = "exp{}".format(n) """

exp = str(params["exp"])
exp

'exp13'

### Load dataset

In [7]:
# load dataset groups
if params["from"] == "python":
    df_raw = pd.read_csv("experiments/raw_data/{}.csv".format(params["raw_data_file"]), delimiter="|")
elif params["from"] == "drf":
    df_raw = pd.read_csv("{}".format(params["raw_data_file"]), delimiter="|") # from DRF
df_raw

,Alignment ID,Average Rt,Average Mz,Metabolite name,AR_1.1,AR_1.2,AR_1.3,AR_2.1,AR_2.2,AR_2.3,...,SGB_1.3,SGB_2.1,SGB_2.2,SGB_2.3,health_1.1,health_1.2,health_1.3,health_2.1,health_2.2,health_2.3
0,0,1.0,69.99951,Unknown,0.067434,0.524123,-0.866715,0.407143,-0.406209,0.009354,...,-1.070179,-0.944405,-1.070179,0.243862,0.213709,-0.178399,-0.301910,-0.167625,-0.189232,-0.178399
1,1,1.0,70.04025,Unknown,2.617854,3.259370,4.805380,3.076543,2.158068,2.745557,...,2.074975,2.584545,2.074975,2.450491,2.697953,2.316318,2.421034,2.327056,2.305521,2.316318
2,2,1.0,70.04151,Unknown,1.088222,1.732480,1.674824,1.235654,0.836471,1.315006,...,1.811865,1.974349,1.811865,0.854473,1.301124,1.092894,1.155690,1.098620,1.087138,1.092894
3,3,1.0,70.04908,Unknown,1.880941,2.504997,2.535388,1.880900,1.544437,2.014078,...,0.706776,1.856629,0.706776,1.714065,2.358324,2.080343,1.900361,2.088160,2.072484,2.080343
4,4,1.0,70.06267,Unknown,1.659528,2.097781,2.593391,1.309826,1.316238,1.668676,...,1.153538,1.286182,1.153538,1.050297,2.077151,1.793208,1.525407,1.801015,1.785358,1.793208
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5439,5439,1.0,732.79951,Unknown,0.892378,3.759797,0.585675,1.039707,0.346959,0.665817,...,0.195989,2.321735,0.195989,0.663823,1.091110,0.643823,0.487232,0.656200,0.631372,0.643823
5440,5440,1.0,748.76437,Unknown,0.916754,1.620635,0.718502,1.221477,0.400736,1.054753,...,0.297500,0.758849,0.297500,0.759580,1.002615,0.575805,0.695502,0.587540,0.564006,0.575805
5441,5441,1.0,794.79590,Unknown,1.151250,2.041729,2.984408,1.105385,0.734599,1.412716,...,3.053481,0.755768,3.053481,0.888324,1.291584,0.955433,1.061403,0.964905,0.945910,0.955433
5442,5442,1.0,800.81295,Unknown,1.478938,2.421294,3.121924,1.400182,1.092336,1.761611,...,3.010984,2.673166,3.010984,1.239034,1.662417,1.343335,1.420552,1.352313,1.334307,1.343335
5443,5443,1.0,860.74167,Unknown,0.344954,0.992325,0.136437,0.612615,-0.373978,0.452590,...,-0.261434,0.158394,-0.261434,-0.002186,0.861377,0.267264,0.172128,0.283610,0.250828,0.267264

### Format dataset

In [8]:
# apply transformation
columns_data = list(df_raw.columns)[4:]
if params["apply_transformation"]:
    print("transformation")
    for column in columns_data:
        df_raw[column] = df_raw[column].apply(lambda x: 10**x)
df_raw

,Alignment ID,Average Rt,Average Mz,Metabolite name,AR_1.1,AR_1.2,AR_1.3,AR_2.1,AR_2.2,AR_2.3,...,SGB_1.3,SGB_2.1,SGB_2.2,SGB_2.3,health_1.1,health_1.2,health_1.3,health_2.1,health_2.2,health_2.3
0,0,1.0,69.99951,Unknown,0.067434,0.524123,-0.866715,0.407143,-0.406209,0.009354,...,-1.070179,-0.944405,-1.070179,0.243862,0.213709,-0.178399,-0.301910,-0.167625,-0.189232,-0.178399
1,1,1.0,70.04025,Unknown,2.617854,3.259370,4.805380,3.076543,2.158068,2.745557,...,2.074975,2.584545,2.074975,2.450491,2.697953,2.316318,2.421034,2.327056,2.305521,2.316318
2,2,1.0,70.04151,Unknown,1.088222,1.732480,1.674824,1.235654,0.836471,1.315006,...,1.811865,1.974349,1.811865,0.854473,1.301124,1.092894,1.155690,1.098620,1.087138,1.092894
3,3,1.0,70.04908,Unknown,1.880941,2.504997,2.535388,1.880900,1.544437,2.014078,...,0.706776,1.856629,0.706776,1.714065,2.358324,2.080343,1.900361,2.088160,2.072484,2.080343
4,4,1.0,70.06267,Unknown,1.659528,2.097781,2.593391,1.309826,1.316238,1.668676,...,1.153538,1.286182,1.153538,1.050297,2.077151,1.793208,1.525407,1.801015,1.785358,1.793208
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5439,5439,1.0,732.79951,Unknown,0.892378,3.759797,0.585675,1.039707,0.346959,0.665817,...,0.195989,2.321735,0.195989,0.663823,1.091110,0.643823,0.487232,0.656200,0.631372,0.643823
5440,5440,1.0,748.76437,Unknown,0.916754,1.620635,0.718502,1.221477,0.400736,1.054753,...,0.297500,0.758849,0.297500,0.759580,1.002615,0.575805,0.695502,0.587540,0.564006,0.575805
5441,5441,1.0,794.79590,Unknown,1.151250,2.041729,2.984408,1.105385,0.734599,1.412716,...,3.053481,0.755768,3.053481,0.888324,1.291584,0.955433,1.061403,0.964905,0.945910,0.955433
5442,5442,1.0,800.81295,Unknown,1.478938,2.421294,3.121924,1.400182,1.092336,1.761611,...,3.010984,2.673166,3.010984,1.239034,1.662417,1.343335,1.420552,1.352313,1.334307,1.343335
5443,5443,1.0,860.74167,Unknown,0.344954,0.992325,0.136437,0.612615,-0.373978,0.452590,...,-0.261434,0.158394,-0.261434,-0.002186,0.861377,0.267264,0.172128,0.283610,0.250828,0.267264

In [9]:
# concat
df_join_raw = pd.concat([
    df_raw.iloc[:, :]], axis=1)
df_join_raw.set_index("Alignment ID", inplace=True)
df_join_raw

,Average Rt,Average Mz,Metabolite name,AR_1.1,AR_1.2,AR_1.3,AR_2.1,AR_2.2,AR_2.3,BC_1.1,...,SGB_1.3,SGB_2.1,SGB_2.2,SGB_2.3,health_1.1,health_1.2,health_1.3,health_2.1,health_2.2,health_2.3
Alignment ID,,,,,,,,,,,,,,,,,,,,,
0,1.0,69.99951,Unknown,0.067434,0.524123,-0.866715,0.407143,-0.406209,0.009354,0.310919,...,-1.070179,-0.944405,-1.070179,0.243862,0.213709,-0.178399,-0.301910,-0.167625,-0.189232,-0.178399
1,1.0,70.04025,Unknown,2.617854,3.259370,4.805380,3.076543,2.158068,2.745557,2.617659,...,2.074975,2.584545,2.074975,2.450491,2.697953,2.316318,2.421034,2.327056,2.305521,2.316318
2,1.0,70.04151,Unknown,1.088222,1.732480,1.674824,1.235654,0.836471,1.315006,1.484309,...,1.811865,1.974349,1.811865,0.854473,1.301124,1.092894,1.155690,1.098620,1.087138,1.092894
3,1.0,70.04908,Unknown,1.880941,2.504997,2.535388,1.880900,1.544437,2.014078,2.423544,...,0.706776,1.856629,0.706776,1.714065,2.358324,2.080343,1.900361,2.088160,2.072484,2.080343
4,1.0,70.06267,Unknown,1.659528,2.097781,2.593391,1.309826,1.316238,1.668676,2.019882,...,1.153538,1.286182,1.153538,1.050297,2.077151,1.793208,1.525407,1.801015,1.785358,1.793208
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5439,1.0,732.79951,Unknown,0.892378,3.759797,0.585675,1.039707,0.346959,0.665817,3.175910,...,0.195989,2.321735,0.195989,0.663823,1.091110,0.643823,0.487232,0.656200,0.631372,0.643823
5440,1.0,748.76437,Unknown,0.916754,1.620635,0.718502,1.221477,0.400736,1.054753,3.072149,...,0.297500,0.758849,0.297500,0.759580,1.002615,0.575805,0.695502,0.587540,0.564006,0.575805
5441,1.0,794.79590,Unknown,1.151250,2.041729,2.984408,1.105385,0.734599,1.412716,3.116183,...,3.053481,0.755768,3.053481,0.888324,1.291584,0.955433,1.061403,0.964905,0.945910,0.955433
5442,1.0,800.81295,Unknown,1.478938,2.421294,3.121924,1.400182,1.092336,1.761611,3.365476,...,3.010984,2.673166,3.010984,1.239034,1.662417,1.343335,1.420552,1.352313,1.334307,1.343335
5443,1.0,860.74167,Unknown,0.344954,0.992325,0.136437,0.612615,-0.373978,0.452590,2.979570,...,-0.261434,0.158394,-0.261434,-0.002186,0.861377,0.267264,0.172128,0.283610,0.250828,0.267264

In [10]:
# split
df_join_raw = df_join_raw.rename_axis(None)
# df_join_raw = df_join_raw.iloc[:, 2:]
df_join_raw

,Average Rt,Average Mz,Metabolite name,AR_1.1,AR_1.2,AR_1.3,AR_2.1,AR_2.2,AR_2.3,BC_1.1,...,SGB_1.3,SGB_2.1,SGB_2.2,SGB_2.3,health_1.1,health_1.2,health_1.3,health_2.1,health_2.2,health_2.3
0,1.0,69.99951,Unknown,0.067434,0.524123,-0.866715,0.407143,-0.406209,0.009354,0.310919,...,-1.070179,-0.944405,-1.070179,0.243862,0.213709,-0.178399,-0.301910,-0.167625,-0.189232,-0.178399
1,1.0,70.04025,Unknown,2.617854,3.259370,4.805380,3.076543,2.158068,2.745557,2.617659,...,2.074975,2.584545,2.074975,2.450491,2.697953,2.316318,2.421034,2.327056,2.305521,2.316318
2,1.0,70.04151,Unknown,1.088222,1.732480,1.674824,1.235654,0.836471,1.315006,1.484309,...,1.811865,1.974349,1.811865,0.854473,1.301124,1.092894,1.155690,1.098620,1.087138,1.092894
3,1.0,70.04908,Unknown,1.880941,2.504997,2.535388,1.880900,1.544437,2.014078,2.423544,...,0.706776,1.856629,0.706776,1.714065,2.358324,2.080343,1.900361,2.088160,2.072484,2.080343
4,1.0,70.06267,Unknown,1.659528,2.097781,2.593391,1.309826,1.316238,1.668676,2.019882,...,1.153538,1.286182,1.153538,1.050297,2.077151,1.793208,1.525407,1.801015,1.785358,1.793208
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5439,1.0,732.79951,Unknown,0.892378,3.759797,0.585675,1.039707,0.346959,0.665817,3.175910,...,0.195989,2.321735,0.195989,0.663823,1.091110,0.643823,0.487232,0.656200,0.631372,0.643823
5440,1.0,748.76437,Unknown,0.916754,1.620635,0.718502,1.221477,0.400736,1.054753,3.072149,...,0.297500,0.758849,0.297500,0.759580,1.002615,0.575805,0.695502,0.587540,0.564006,0.575805
5441,1.0,794.79590,Unknown,1.151250,2.041729,2.984408,1.105385,0.734599,1.412716,3.116183,...,3.053481,0.755768,3.053481,0.888324,1.291584,0.955433,1.061403,0.964905,0.945910,0.955433
5442,1.0,800.81295,Unknown,1.478938,2.421294,3.121924,1.400182,1.092336,1.761611,3.365476,...,3.010984,2.673166,3.010984,1.239034,1.662417,1.343335,1.420552,1.352313,1.334307,1.343335
5443,1.0,860.74167,Unknown,0.344954,0.992325,0.136437,0.612615,-0.373978,0.452590,2.979570,...,-0.261434,0.158394,-0.261434,-0.002186,0.861377,0.267264,0.172128,0.283610,0.250828,0.267264

In [11]:
# get groups name
groups_id_no = params["groups_id_no"]
groups_id = []
for item in df_join_raw.iloc[:, 3:].columns.values:
    group_id = item.split("_")[0]
    if group_id not in groups_id and group_id not in groups_id_no:
        groups_id.append(group_id)
groups_id

['AR',
 'BC',
 'BPH',
 'CKD14',
 'CKD5',
 'CRS',
 'ED',
 'HC',
 'LP',
 'LPRD',
 'LSNB',
 'OSA',
 'PCa',
 'PD',
 'PSG',
 'RCC',
 'SGB',
 'health']

In [12]:
# delete no sample columns
""" columns_delete = [columna for columna in df_join_raw.columns if columna.split("_")[0] in columns_no_sample]
df_join_raw.drop(columns_delete, axis=1, inplace=True)
df_join_raw """

' columns_delete = [columna for columna in df_join_raw.columns if columna.split("_")[0] in columns_no_sample]\ndf_join_raw.drop(columns_delete, axis=1, inplace=True)\ndf_join_raw '

In [13]:
# get subgroups names

""" def get_subgroups_id(df_join_raw, groups, by_group=False):
    dict_groups_id = {}
    for group in groups:
        # get group
        if by_group:
            dict_groups_id[group] = ["1"]
        else:
            columns = list(df_join_raw.filter(like=group).columns)
            subgroups = [item.split("{}_".format(group))[1].split(".")[0] for item in columns]
            subgroups = np.unique(subgroups)
            dict_groups_id[group] = subgroups.tolist()
    return dict_groups_id """

subgroups_id = get_subgroups_id(df_join_raw, groups_id)
subgroups_id

{'AR': ['1', '2'],
 'BC': ['1', '2'],
 'BPH': ['1', '2'],
 'CKD14': ['1', '2'],
 'CKD5': ['1', '2'],
 'CRS': ['1', '2'],
 'ED': ['1', '2'],
 'HC': ['1', '2'],
 'LP': ['1', '2'],
 'LPRD': ['1', '2'],
 'LSNB': ['1', '2'],
 'OSA': ['1', '2'],
 'PCa': ['1', '2'],
 'PD': ['1', '2'],
 'PSG': ['1', '2'],
 'RCC': ['1', '2'],
 'SGB': ['1', '2'],
 'health': ['1', '2']}

In [14]:
# count analtical repetitions
# df_join_raw.filter(like="AA_1.")

In [15]:
# check distribution

In [16]:
""" x = df_join_raw.iloc[2, 3:]
print(x.min(), x.max(), x.mean())
x.hist(bins=200) """

' x = df_join_raw.iloc[2, 3:]\nprint(x.min(), x.max(), x.mean())\nx.hist(bins=200) '

In [17]:
# f_join_raw.iloc[:, 5].hist(bins=100)

In [18]:
params["controls"], groups_id

(['AR'],
 ['AR',
  'BC',
  'BPH',
  'CKD14',
  'CKD5',
  'CRS',
  'ED',
  'HC',
  'LP',
  'LPRD',
  'LSNB',
  'OSA',
  'PCa',
  'PD',
  'PSG',
  'RCC',
  'SGB',
  'health'])

In [19]:
# get groups combination
groups = []
controls = params["controls"]

groups = []
for control in controls:
    for group_id in groups_id:
        if control != group_id:
            groups.append([control, group_id])
print(groups)

[['AR', 'BC'], ['AR', 'BPH'], ['AR', 'CKD14'], ['AR', 'CKD5'], ['AR', 'CRS'], ['AR', 'ED'], ['AR', 'HC'], ['AR', 'LP'], ['AR', 'LPRD'], ['AR', 'LSNB'], ['AR', 'OSA'], ['AR', 'PCa'], ['AR', 'PD'], ['AR', 'PSG'], ['AR', 'RCC'], ['AR', 'SGB'], ['AR', 'health']]

### Create folders

In [20]:
# create experiments folder
try: 
    os.mkdir("experiments/output/{}".format(exp))
    os.mkdir("experiments/output/{}/correlations".format(exp))
    os.mkdir("experiments/output/{}/preprocessing".format(exp))
    os.mkdir("experiments/output/{}/preprocessing/edges".format(exp))
    os.mkdir("experiments/output/{}/preprocessing/graphs_data".format(exp))
    os.mkdir("experiments/output/{}/loss".format(exp))
    os.mkdir("experiments/output/{}/node_embeddings".format(exp))
    os.mkdir("experiments/output/{}/common_nodes".format(exp))
    os.mkdir("experiments/output/{}/filter_raw".format(exp))
    os.mkdir("experiments/output/{}/plots".format(exp))
except OSError as error: 
    print(error)

### Save dataset and parameters

In [21]:
# save dataset
df_join_raw.to_csv("experiments/input/{}_raw.csv".format(exp), index=True)

# save parameters
parameters = {
    "exp": exp,
    "methods": params["methods"],
    "data_variations": params["data_variations"],
    "apply_transformation": params["apply_transformation"],
    "controls": params["controls"],
    "dimension": params["dimension"],
    "threshold_corr": params["threshold_corr"],
    "threshold_log2": params["threshold_log2"],
    "alpha": params["alpha"],
    "iterations": params["iterations"],
    "raw_data_file": params["raw_data_file"],
    "groups_id": groups_id,
    "subgroups_id": subgroups_id,
    "groups": groups,
    "groups_id_no": params["groups_id_no"],
    "sensitivity": params["sensitivity"],
    
    "from": params["from"],
    "cuda": params["cuda"],
    "epochs": params["epochs"],
    "lr": params["lr"],
    "weight_decay": params["weight_decay"],
    "patience": params["patience"],
    "contamination": params["contamination"],
    "n_jobs": params["n_jobs"],

    "seeds": params["seeds"],
    "obs": params["obs"]
}

with open("experiments/output/{}/parameters.json".format(exp), "w") as outfile:
    json.dump(parameters, outfile, indent=4)

In [22]:
experiments = {
    "exp": exp
}

with open("exp.json".format(experiments), "w") as outfile:
    json.dump(experiments, outfile, indent=4)

In [23]:
# return exp