In [1]:
# Torch version
!python -c "import torch; print(torch.__version__)"

# Cuda version
!python -c "import torch; print(torch.version.cuda)"

2.6.0+cu124
12.4

In [2]:
# Uninstall
# !pip uninstall torch-scatter torch-sparse torch-cluster torch-spline-conv pyg-lib -y

In [3]:
# Update Torch
# !pip install torch==2.6.0 torchvision==0.21.0 torchaudio==2.6.0 --index-url https://download.pytorch.org/whl/cu124

In [4]:
# Install PyG (automatic)
# !pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-{torch.__version__}.html
# !pip install torch_geometric

In [5]:
# Verify instalation
import torch
import torch_geometric
import torch_scatter

print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.is_available())
print(torch_scatter.__version__)
print(torch_geometric.__version__)

2.6.0+cu124
12.4
True
2.1.2+pt26cu124
2.7.0

In [6]:
from model_PyG_cla import *
from utils import *

In [7]:
import json
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
import pandas as pd
import time
import torch
import torch.nn.functional as F
import torch_geometric.transforms as T

from mpl_toolkits.mplot3d import Axes3D
from sklearn.decomposition import PCA
from sklearn.neighbors import NearestNeighbors
from torch_geometric.data import InMemoryDataset, Data
from torch_geometric.nn.conv.gcn_conv import gcn_norm
from torch_geometric.transforms import Compose
from torch_geometric.utils import dense_to_sparse, negative_sampling
from torch.nn.functional import binary_cross_entropy_with_logits
from torch.optim import Adam

In [8]:
import torch_geometric
print(torch_geometric.__version__)

np.random.seed(0)
torch.manual_seed(0)
torch.cuda.manual_seed(0)
torch.cuda.manual_seed_all(0)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

2.7.0

### Parameters

In [9]:
file = open("exp.json")
experiment = json.load(file)
exp = experiment["exp"] # Change to static, e.g. "exp1"

file = open("experiments/output/{}/parameters.json".format(exp))
params = json.load(file)

print("Exp:\t\t", exp)

raw_data_file = params["raw_data_file"]
print("Raw data:\t", raw_data_file)

methods = params["methods"]
print("Methods:\t", methods)

apply_transformation = params["apply_transformation"]
print("Has transformation:", apply_transformation)

dimension = params["dimension"]
print("Dimension:\t", dimension)

groups_id = params["groups_id"]
print("Groups id:\t", groups_id)

subgroups_id = params["subgroups_id"]
print("Subgroups id:\t", subgroups_id)

cuda = params["cuda"]
print("Cuda:\t", cuda)

epochs = params["epochs"]
print("Epochs:\t", epochs)

lr = params["lr"]
print("Lr:\t", lr)

weight_decay = params["weight_decay"]
print("Weight decay:\t", weight_decay)

patience = params["patience"]
print("Patience:\t", patience)

Exp:		 exp108
Raw data:	 douban
Methods:	 ['t-gae']
Has transformation: False
Dimension:	 512
Groups id:	 ['douban']
Subgroups id:	 {'douban': ['1', '2']}
Cuda:	 1
Epochs:	 500
Lr:	 0.0001
Weight decay:	 0.0001
Patience:	 10

### Setup

In [10]:
# Parameters models

dataset = exp
encoders = ["GCNRes", "GIN", "GINE", "GCN", "GAT", "GATE"] # ["GIN", "GINE"] # ["GIN", "GINE"] # ["GIN", "GINE"] # Change
device = torch.device(f"cuda:{cuda}" if torch.cuda.is_available() else "cpu")
# device = torch.device("cpu")

NUM_HIDDEN_LAYERS = 12
HIDDEN_DIM = [1024] * NUM_HIDDEN_LAYERS + [1024]
output_feature_size = dimension # 128
# lr = 0.001
# epochs = 100

In [11]:
# Create datasets (groups and subgroups)

list_train_set = []

for group_id in groups_id:
	train_set = []
	for subgroup_id in subgroups_id[group_id]:
		train_set.append("{}_{}".format(group_id, subgroup_id))
	list_train_set.append(train_set)
list_train_set

[['douban_1', 'douban_2']]

### Create Data (PyG)

In [12]:
# Only for GIN
""" transform = Compose([
	# T.NormalizeFeatures(),
	T.ToUndirected(reduce="mean"),
	T.AddSelfLoops(fill_value=1.0),
	T.ToDevice(device)
]) """

# For GIN and GINE
transform = T.Compose([
	# T.NormalizeFeatures(),
	T.ToUndirected(reduce="mean"),
	# T.AddSelfLoops(attr="edge_attr", fill_value="mean"),
	# T.AddLaplacianEigenvectorPE(k=3, attr_name=None, is_undirected=True),
	# T.AddRandomWalkPE(walk_length=8, attr_name=None),
	T.ToDevice(device)
])

In [13]:
print("Loading training datasets")
has_edge_attributes = False
with_mean1 = True
with_mean2 = True

list_train_loader = []

if raw_data_file == "ACM_DBLP":
	group_id = groups_id[0]
	
	# Read dataset
	b = np.load("data/ACM-DBLP.npz")

	# Node matching
	test_pairs = b["test_pairs"].astype(np.int32)
	pos_pairs = b["pos_pairs"].astype(np.int32)
	df_node_alignment_truth = pd.DataFrame(np.concatenate((test_pairs, pos_pairs), axis=0))
	df_node_alignment_truth

	# Data preparation
	subgroup_id = 1
	edge_index1 = torch.tensor(b[f"edge_index{subgroup_id}"], dtype=torch.long)
	x1 = torch.tensor(b[f"x{subgroup_id}"], dtype=torch.float)

	subgroup_id = 2
	edge_index2 = torch.tensor(b[f"edge_index{subgroup_id}"], dtype=torch.long)
	x2 = torch.tensor(b[f"x{subgroup_id}"], dtype=torch.float)

elif raw_data_file == "Douban Online_Offline":
	group_id = groups_id[0]
	
	# Read dataset
	a1, f1, a2, f2, test_pairs = load_douban()

	# Node matching
	test_pairs = torch.tensor(np.array(test_pairs, dtype=int)) - 1
	test_pairs = test_pairs.numpy()
	df_node_alignment_truth = pd.DataFrame(test_pairs.T)
	df_node_alignment_truth

	# Create data
	edge_index1, _ = dense_to_sparse(torch.from_numpy(a1.toarray()))
	x1 = torch.from_numpy(f1.toarray()).float()

	edge_index2, _= dense_to_sparse(torch.from_numpy(a2.toarray()))
	x2 = torch.from_numpy(f2.toarray()).float()

	with_mean1 = False
	with_mean2 = False

elif raw_data_file == "Cora1-Cora2":
	group_id = groups_id[0]
		
	# Read dataset
	loader = load_npz("data/cora.npz")
	data = loader["adj_matrix"]
	samples = data.shape[0]
	features = data.shape[1]
	values = data.data
	coo_data = data.tocoo()
	# indices = torch.LongTensor([coo_data.row, coo_data.col])
	indices = np.array([coo_data.row, coo_data.col])

	# Node matching
	N = 2708
	test_pairs = [[i, i] for i in range(N)]
	df_node_alignment_truth = pd.DataFrame(test_pairs)
	df_node_alignment_truth

	# Create data
	node_features = loader["node_attr"]
	node_features = node_features.toarray()

	edge_index1 = torch.tensor(indices, dtype=torch.long)
	x1 = torch.tensor(node_features, dtype=torch.float)

	edge_index2 = torch.tensor(indices, dtype=torch.long)
	x2 = torch.tensor(node_features, dtype=torch.float)

	with_mean1 = False
	with_mean2 = True

elif raw_data_file == "flickr-lastfm":
	# https://github.com/yq-leo/PlanetAlign/blob/main/PlanetAlign/datasets/flickr_lastfm.py
	data = torch.load("data/flickr-lastfm.pt")
	edges = data["edges"]
	node_features = data["node_attributes"]
	edges_attributes = data["edge_attributes"]
	
	# Node matching
	test_pairs = data["anchor_links"].cpu().numpy()
	df_node_alignment_truth = pd.DataFrame(test_pairs)
	df_node_alignment_truth

	# Create data
	edge_index1 = edges[0]
	x1 = torch.tensor(node_features[0].cpu().numpy(), dtype=torch.float)
	edge_attr1 = torch.tensor(edges_attributes[0].cpu().numpy(), dtype=torch.float)

	edge_index2 = edges[1]
	x2 = torch.tensor(node_features[1].cpu().numpy(), dtype=torch.float)
	edge_attr2 = torch.tensor(edges_attributes[1].cpu().numpy(), dtype=torch.float)

	has_edge_attributes = True
	with_mean1 = False
	with_mean2 = False

elif raw_data_file == "douban":
	# https://github.com/yq-leo/PlanetAlign/blob/main/PlanetAlign/datasets/flickr_lastfm.py
	data = torch.load("data/douban.pt")
	edges = data["edges"]
	node_features = data["node_attributes"]
	edges_attributes = data["edge_attributes"]
	
	# Node matching
	test_pairs = data["anchor_links"].cpu().numpy()
	df_node_alignment_truth = pd.DataFrame(test_pairs)
	df_node_alignment_truth

	# Create data
	edge_index1 = edges[0]
	x1 = torch.tensor(node_features[0].cpu().numpy(), dtype=torch.float)
	edge_attr1 = torch.tensor(edges_attributes[0].cpu().numpy(), dtype=torch.float)

	edge_index2 = edges[1]
	x2 = torch.tensor(node_features[1].cpu().numpy(), dtype=torch.float)
	edge_attr2 = torch.tensor(edges_attributes[1].cpu().numpy(), dtype=torch.float)

	has_edge_attributes = True
	with_mean1 = False
	with_mean2 = False

elif raw_data_file == "flickr-myspace":
	# https://github.com/yq-leo/PlanetAlign/blob/main/PlanetAlign/datasets/flickr_lastfm.py
	data = torch.load("data/flickr-myspace.pt")
	edges = data["edges"]
	node_features = data["node_attributes"]
	edges_attributes = data["edge_attributes"]
	
	# Node matching
	test_pairs = data["anchor_links"].cpu().numpy()
	df_node_alignment_truth = pd.DataFrame(test_pairs)
	df_node_alignment_truth

	# Create data
	edge_index1 = edges[0]
	x1 = torch.tensor(node_features[0].cpu().numpy(), dtype=torch.float)
	edge_attr1 = torch.tensor(edges_attributes[0].cpu().numpy(), dtype=torch.float)

	edge_index2 = edges[1]
	x2 = torch.tensor(node_features[1].cpu().numpy(), dtype=torch.float)
	edge_attr2 = torch.tensor(edges_attributes[1].cpu().numpy(), dtype=torch.float)

	has_edge_attributes = True
	with_mean1 = False
	with_mean2 = False

elif raw_data_file == "ACM-DBLP":
	# https://github.com/yq-leo/PlanetAlign/blob/main/PlanetAlign/datasets/flickr_lastfm.py
	data = torch.load("data/ACM-DBLP.pt")
	edges = data["edges"]
	node_features = data["node_attributes"]
	# edges_attributes = data["edge_attributes"]
	
	# Node matching
	test_pairs = data["anchor_links"].cpu().numpy()
	df_node_alignment_truth = pd.DataFrame(test_pairs)
	df_node_alignment_truth

	# Create data
	edge_index1 = edges[0]
	x1 = torch.tensor(node_features[0].cpu().numpy(), dtype=torch.float)
	# edge_attr1 = torch.tensor(edges_attributes[0].cpu().numpy(), dtype=torch.float)

	edge_index2 = edges[1]
	x2 = torch.tensor(node_features[1].cpu().numpy(), dtype=torch.float)
	# edge_attr2 = torch.tensor(edges_attributes[1].cpu().numpy(), dtype=torch.float)

	has_edge_attributes = False
	with_mean1 = True
	with_mean2 = True

elif raw_data_file == "cora":
	# https://github.com/yq-leo/PlanetAlign/blob/main/PlanetAlign/datasets/flickr_lastfm.py
	data = torch.load("data/cora.pt")
	edges = data["edges"]
	node_features = data["node_attributes"]
	# edges_attributes = data["edge_attributes"]
	
	# Node matching
	test_pairs = data["anchor_links"].cpu().numpy()
	df_node_alignment_truth = pd.DataFrame(test_pairs)
	df_node_alignment_truth

	# Create data
	edge_index1 = edges[0]
	x1 = torch.tensor(node_features[0].cpu().numpy(), dtype=torch.float)
	# edge_attr1 = torch.tensor(edges_attributes[0].cpu().numpy(), dtype=torch.float)

	edge_index2 = edges[1]
	x2 = torch.tensor(node_features[1].cpu().numpy(), dtype=torch.float)
	# edge_attr2 = torch.tensor(edges_attributes[1].cpu().numpy(), dtype=torch.float)

	has_edge_attributes = False
	with_mean1 = False
	with_mean2 = True
	
# Create data
train_loader = {}

# Include edge_attr
subgroup_id = 1
data1 = Data(x=x1, edge_index=edge_index1)
if has_edge_attributes:
	data1.edge_attr = edge_attr1
else:
	data1 = add_edge_attributes(data1)
print(subgroup_id, data1)
info_data(data1, include_vectors=True)

subgroup_id = 2
data2 = Data(x=x2, edge_index=edge_index2)
if has_edge_attributes:
	data2.edge_attr = edge_attr2
else:
	data2 = add_edge_attributes(data2)
print(subgroup_id, data2)
info_data(data2, include_vectors=True)

# Normalize
normalize_node_edge_features(data1, data2, with_mean1=with_mean1, with_mean2=with_mean2) # Important

# Apply transform
subgroup_id = 1
data1 = transform(data1)
print(subgroup_id, data1)
# info(data1)

subgroup_id = 2
data2 = transform(data2)
print(subgroup_id, data2)
# info(data2)

# [MEJORA 3] Antes: gcn_norm(..., add_self_loops=False) -> edge_weight = D^-1/2 A D^-1/2 (SIN la identidad).
# El script original usa A_hat = D^-1/2 (A+I) D^-1/2 (preprocess_graph). Ahora el modelo "ORI"/GCNRes calcula
# A_hat internamente con self-loops (gcn_norm(add_self_loops=True)); GIN/GINE no usan edge_weight.
# data.edge_index queda intacto (mismas aristas y mismo orden que edge_attr).
subgroup_id = 1
train_loader[f"{group_id}_{subgroup_id}"] = data1
print(1, data1)

subgroup_id = 2
train_loader[f"{group_id}_{subgroup_id}"] = data2
print(2, data2)

info_data(data1, include_vectors=True)
info_data(data2, include_vectors=True)

list_train_loader.append(train_loader)

Loading training datasets
1 Data(x=[3906, 538], edge_index=[2, 16328], edge_attr=[16328, 2])
Validate:	 True
Num. nodes:	 3906
Num. edges:	 16328
Num. features:	 538
Has isolated:	 False
Has loops:	 False
Is directed:	 True
Is undirected:	 False
tensor([[   0,    0,    1,  ..., 3904, 3905, 3905],
        [ 728, 3714,  160,  ..., 3671, 2166, 3790]])
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
tensor([[0., 1.],
        [0., 1.],
        [0., 1.],
        ...,
        [1., 0.],
        [0., 1.],
        [0., 1.]])
2 Data(x=[1118, 538], edge_index=[2, 3022], edge_attr=[3022, 2])
Validate:	 True
Num. nodes:	 1118
Num. edges:	 3022
Num. features:	 538
Has isolated:	 False
Has loops:	 False
Is directed:	 False
Is undirected:	 True
tensor([[   0,    1,    1,  ..., 1117, 1117, 1117],
        [ 819,  268,  592,  ...,  538,  836,  896]])
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
tensor([[0., 1.],
        [0., 1.],
        [0., 1.],
        ...,
        [0., 1.],
        [0., 1.],
        [0., 1.]])
1 Data(x=[3906, 538], edge_index=[2, 16328], edge_attr=[16328, 2])
2 Data(x=[1118, 538], edge_index=[2, 3022], edge_attr=[3022, 2])
1 Data(x=[3906, 538], edge_index=[2, 16328], edge_attr=[16328, 2])
2 Data(x=[1118, 538], edge_index=[2, 3022], edge_attr=[3022, 2])
Validate:	 True
Num. nodes:	 3906
Num. edges:	 16328
Num. features:	 538
Has isolated:	 False
Has loops:	 False
Is directed:	 False
Is undirected:	 True
tensor([[   0,    0,    1,  ..., 3904, 3905, 3905],
        [ 728, 3714,  160,  ..., 3671, 2166, 3790]], device='cuda:1')
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:1')
tensor([[0.0000, 2.3112],
        [1.1556, 1.1556],
        [0.0000, 2.3112],
        ...,
        [1.1556, 1.1556],
        [1.1556, 1.1556],
        [0.0000, 2.3112]], device='cuda:1')
Validate:	 True
Num. nodes:	 1118
Num. edges:	 3022
Num. features:	 538
Has isolated:	 False
Has loops:	 False
Is directed:	 False
Is undirected:	 True
tensor([[   0,    1,    1,  ..., 1117, 1117, 1117],
        [ 819,  268,  592,  ...,  538,  836,  896]], device='cuda:1')
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:1')
tensor([[0.0000, 2.3112],
        [0.0000, 2.3112],
        [0.0000, 2.3112],
        ...,
        [0.0000, 2.3112],
        [0.0000, 2.3112],
        [0.0000, 2.3112]], device='cuda:1')

In [14]:
df_node_alignment_truth

         0    1
0      831  322
1     1033  537
2     3328  453
3     2535  795
4     3115  612
...    ...  ...
1113  3309  473
1114  1051  325
1115  2819  396
1116  2869  757
1117  3342    3

[1118 rows x 2 columns]

### Train

In [15]:
"""Entrenamiento T-GAE para subgraph alignment (PyTorch Geometric).

Requiere el modelo refactorizado de model_PyG.py (edge_weight / edge_attr por nombre).

Cambios respecto a la versión anterior de fit_TGAE_subgraph:
  1. Los positivos de la reconstrucción son las aristas ORIGINALES sin self-loops
	 (data.pos_edge_index), no data.edge_index (que trae self-loops de AddSelfLoops).
  2. Selección de modelo opcional por alineamiento en un conjunto de validación
	 (val_pairs) y restauración de los mejores pesos. Sin val_pairs: early stopping
	 por pérdida, como antes.
  3. Decoder opcional "cosine" (coseno / tau + sesgo aprendible) además del producto interno.
  4. Aumentación opcional por eliminación de aristas (aug_p > 0): se codifica el grafo
	 perturbado y se reconstruye el grafo original (Ec. 7 del paper, aplicada por grafo).
  5. Pérdida balanceada: 0.5 * (BCE positivos + BCE negativos), con neg_ratio configurable.
  6. Opcional: recorte de gradiente, AdamW, semilla.
  7. Métricas de alineamiento (Hit@K, MRR) con similitud coseno, L2 o CSLS.
"""
import os
import random

import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
from torch_geometric.utils import negative_sampling, remove_self_loops
from tqdm import tqdm


GCNRES_NAMES = ("GCNRes", "ORI")  # "ORI" es el nombre que usa el notebook para la capa original

# ----------------------------------------------------------------------------
# Utilidades
# ----------------------------------------------------------------------------
def set_seed(seed):
	random.seed(seed)
	np.random.seed(seed)
	torch.manual_seed(seed)
	torch.cuda.manual_seed_all(seed)


def make_val_split(pairs, val_frac=0.2, seed=0):
	"""Divide pares de anclaje [K, 2] en (validación, evaluación).

	Reporta las métricas finales SOLO sobre el segundo conjunto.
	"""
	pairs = np.asarray(pairs)
	idx = np.random.default_rng(seed).permutation(len(pairs))
	n_val = int(round(val_frac * len(pairs)))
	return pairs[idx[:n_val]], pairs[idx[n_val:]]


def prepare_graph(data):
	"""Guarda las aristas originales sin self-loops (objetivo de reconstrucción)."""
	if getattr(data, "pos_edge_index", None) is None:
		data.pos_edge_index, _ = remove_self_loops(data.edge_index)
	return data


def drop_undirected_edges(edge_index, edge_attr, p, num_nodes):
	"""Elimina cada arista no dirigida con probabilidad p (ambos sentidos a la vez).

	Conserva los self-loops y mantiene edge_attr alineado con edge_index.
	"""
	row, col = edge_index
	key = torch.minimum(row, col) * num_nodes + torch.maximum(row, col)
	uniq, inv = torch.unique(key, return_inverse=True)
	keep_undirected = torch.rand(uniq.numel(), device=edge_index.device) >= p
	keep = keep_undirected[inv] | (row == col)
	edge_index = edge_index[:, keep]
	if edge_attr is not None:
		edge_attr = edge_attr[keep]
	return edge_index, edge_attr


def _encode(model, data, encoder, aug_p=0.0):
	"""Llama al modelo según el encoder. GCNRes recibe aristas sin loops y el modelo
	calcula Â = D^-1/2 (A+I) D^-1/2 internamente; GCN recibe pesos crudos (ninguno)."""
	ei = data.pos_edge_index if encoder in GCNRES_NAMES else data.edge_index
	ea = data.edge_attr if encoder in ("GINE", "GATE") else None
	if aug_p > 0:
		ei, ea = drop_undirected_edges(ei, ea, aug_p, data.num_nodes)
	kw = {"edge_attr": ea} if ea is not None else {}
	return model(data.x, ei, **kw)


def _edge_logits(z, pos, neg, decoder, tau, bias):
	if decoder == "cosine":
		z = F.normalize(z, dim=1)
	pos_logits = (z[pos[0]] * z[pos[1]]).sum(dim=1)
	neg_logits = (z[neg[0]] * z[neg[1]]).sum(dim=1)
	if decoder == "cosine":
		pos_logits = pos_logits / tau + bias
		neg_logits = neg_logits / tau + bias
	return pos_logits, neg_logits


# ----------------------------------------------------------------------------
# Evaluación de alineamiento
# ----------------------------------------------------------------------------
def _mean_topk(a, b, k, chunk=2048):
	"""Para cada fila de a: media de las k mayores similitudes coseno con las filas de b."""
	out = []
	for i in range(0, a.size(0), chunk):
		out.append((a[i:i + chunk] @ b.T).topk(k, dim=1).values.mean(dim=1))
	return torch.cat(out)


@torch.no_grad()
def similarity_matrix(z1, z2, retrieval="cosine", csls_k=None):
    """Full similarity matrix [N1, N2] (higher = more similar), as PlanetAlign expects."""
    if retrieval == "cosine":
        a, b = F.normalize(z1, dim=1), F.normalize(z2, dim=1)
        sim = a @ b.T
        if csls_k:
            r_s = _mean_topk(a, b, csls_k)
            r_t = _mean_topk(b, a, csls_k)
            sim = 2 * sim - r_s.unsqueeze(1) - r_t.unsqueeze(0)
        return sim
    if retrieval == "l2":
        if csls_k:
            raise ValueError("csls_k is only supported with retrieval='cosine'")
        return -torch.cdist(z1, z2)  # distances -> similarities
    raise ValueError("retrieval must be 'cosine' or 'l2'")

@torch.no_grad()
def evaluate_alignment(z1, z2, pairs, retrieval="cosine", csls_k=None, ks=(1, 5, 10, 50), mode="ltr"):
    """Hit@K and MRR computed with PlanetAlign's hits_ks_scores and mrr_score.

    pairs: [K, 2] (idx in graph 1, idx in graph 2).
    mode: 'ltr' (graph1->graph2), 'rtl', 'mean' or 'max', as in PlanetAlign.
    Returns {"hit@k": ..., "mrr": ...}.
    """
    sim = similarity_matrix(z1, z2, retrieval, csls_k)
    pairs = torch.as_tensor(pairs, dtype=torch.long, device=sim.device)
    hits = hits_ks_scores(sim, pairs, ks=ks, mode=mode)
    out = {f"hit@{k}": hits[k] for k in ks}
    out["mrr"] = mrr_score(sim, pairs, mode=mode)
    return out
 
 
def evaluate_alignment_mean(z1, z2, pairs, **kw):
    """evaluate_alignment with mode="mean" (average of both directions, as in the notebook)."""
    return evaluate_alignment(z1, z2, pairs, mode="mean", **kw)


@torch.no_grad()
def evaluate_alignment_v1(z1, z2, pairs, retrieval="cosine", csls_k=None, ks=(1, 5, 10, 50)):
	"""Hit@K y MRR de z1 (grafo 1) hacia z2 (grafo 2). pairs: [K, 2] (idx en 1, idx en 2)."""
	pairs = torch.as_tensor(np.asarray(pairs), dtype=torch.long, device=z1.device)
	src, tgt = pairs[:, 0], pairs[:, 1]
	if retrieval == "cosine":
		a, b = F.normalize(z1, dim=1), F.normalize(z2, dim=1)
		sim = a[src] @ b.T
		if csls_k:
			r_s = _mean_topk(a[src], b, csls_k)
			r_t = _mean_topk(b, a, csls_k)
			sim = 2 * sim - r_s.unsqueeze(1) - r_t.unsqueeze(0)
	elif retrieval == "l2":
		if csls_k:
			raise ValueError("csls_k solo está soportado con retrieval='cosine'")
		sim = -torch.cdist(z1[src], z2)
	else:
		raise ValueError("retrieval debe ser 'cosine' o 'l2'")
	true = sim[torch.arange(len(src), device=sim.device), tgt].unsqueeze(1)
	rank = (sim > true).sum(dim=1) + 1
	out = {f"hit@{k}": (rank <= k).float().mean().item() for k in ks}
	out["mrr"] = (1.0 / rank.float()).mean().item()
	print(1, out)
	# return out

	print(type(sim))
	print(sim)

	# Based on PlanetAlign
	hits = hits_ks_scores(sim.clone().detach(), torch.tensor(EVAL_PAIRS), ks=ks,  mode="mean")
	print(10)
	mrr = mrr_score(sim.clone().detach(), torch.tensor(EVAL_PAIRS), mode="mean")
	print(11)
	hits["mrr"] = mrr
	print(2, hits)
	return hits


def evaluate_alignment_mean_v1(z1, z2, pairs, **kw):
	"""Promedio de grafo1->grafo2 y grafo2->grafo1 (equivale a mode="mean" de PlanetAlign)."""
	pairs = np.asarray(pairs)
	a = evaluate_alignment_v1(z1, z2, pairs, **kw)
	b = evaluate_alignment_v1(z2, z1, pairs[:, ::-1].copy(), **kw)
	return {k: (a[k] + b[k]) / 2 for k in a}


# ----------------------------------------------------------------------------
# Entrenamiento
# ----------------------------------------------------------------------------
def fit_TGAE_subgraph(model, encoder, exp, group_id, subgroups_id, train_loader, train_set,
					no_samples, epochs, lr, weight_decay,
					val_pairs=None, eval_every=5, select_metric="mrr",
					retrieval="cosine", csls_k=None,
					decoder="dot", tau=0.2, neg_ratio=1.0,
					aug_p=0.0, grad_clip=None, optimizer_name="adam",
					patience=50, delta=1e-4, warmup=10, seed=None, save_outputs=True):
	"""Entrena el encoder y guarda embeddings y pérdida (mismas rutas que antes).

	no_samples se conserva por compatibilidad de firma; la pérdida se promedia
	sobre len(train_set). Devuelve un dict con el resumen del entrenamiento.
	"""
	if seed is not None:
		set_seed(seed)
	dev = next(model.parameters()).device
	if val_pairs is not None and len(subgroups_id) < 2:
		raise ValueError("La validación requiere dos subgrafos en subgroups_id")

	for ts in train_set:
		prepare_graph(train_loader[ts])
	for sg in subgroups_id:
		prepare_graph(train_loader[f"{group_id}_{sg}"])

	# Sesgo aprendible solo para el decoder coseno (sin él, la pérdida satura).
	bias = torch.zeros((), device=dev, requires_grad=True) if decoder == "cosine" else None
	param_groups = [{"params": list(model.parameters())}]
	if bias is not None:
		param_groups.append({"params": [bias], "weight_decay": 0.0})
	opt_cls = torch.optim.AdamW if optimizer_name == "adamw" else torch.optim.Adam
	optimizer = opt_cls(param_groups, lr=lr, weight_decay=weight_decay)

	use_val = val_pairs is not None
	list_loss, history = [], []
	best_score, best_epoch, best_state = -float("inf"), 0, None
	best_loss, bad_count, stopped_epoch = None, 0, None
	max_bad = max(1, patience // eval_every) if use_val else patience

	model.train()
	loop_obj = tqdm(range(1, epochs + 1))
	for epoch in loop_obj:
		loop_obj.set_description(f"Epoch: {epoch}")
		optimizer.zero_grad()
		loss = torch.zeros((), device=dev)

		for ts in train_set:
			data = train_loader[ts]
			z = _encode(model, data, encoder, aug_p)

			pos = data.pos_edge_index  # objetivo: grafo original, sin self-loops
			neg = negative_sampling(
				edge_index=pos, num_nodes=z.size(0),
				num_neg_samples=int(neg_ratio * pos.size(1)), method="sparse",
			)
			pos_logits, neg_logits = _edge_logits(z, pos, neg, decoder, tau, bias)
			loss = loss + 0.5 * (
				F.binary_cross_entropy_with_logits(pos_logits, torch.ones_like(pos_logits))
				+ F.binary_cross_entropy_with_logits(neg_logits, torch.zeros_like(neg_logits))
			)

		loss = loss / len(train_set)
		loss.backward()
		if grad_clip is not None:
			torch.nn.utils.clip_grad_norm_(model.parameters(), grad_clip)
		optimizer.step()

		loss_value = loss.item()
		list_loss.append(loss_value)
		loop_obj.set_postfix_str(f"Loss: {loss_value:.4f}")

		if use_val:
			if epoch % eval_every == 0 or epoch == epochs:
				model.eval()
				with torch.no_grad():
					z1 = _encode(model, train_loader[f"{group_id}_{subgroups_id[0]}"], encoder)
					z2 = _encode(model, train_loader[f"{group_id}_{subgroups_id[1]}"], encoder)
					metrics = evaluate_alignment(z1, z2, val_pairs, retrieval, csls_k)
				model.train()
				metrics["epoch"] = epoch
				history.append(metrics)
				score = metrics[select_metric]
				loop_obj.set_postfix_str(f"Loss: {loss_value:.4f} val_{select_metric}: {score:.4f}")
				if score > best_score + 1e-6:
					best_score, best_epoch, bad_count = score, epoch, 0
					# En CPU para no duplicar memoria de GPU.
					best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
				else:
					bad_count += 1
				if epoch >= warmup and bad_count >= max_bad:
					stopped_epoch = epoch
					print(f"Early stopping (validación) en la época {epoch}; mejor época: {best_epoch}")
					break
		else:
			if epoch >= warmup:
				if best_loss is None or loss_value < best_loss - delta:
					best_loss, bad_count = loss_value, 0
				else:
					bad_count += 1
					if bad_count >= max_bad:
						stopped_epoch = epoch
						print(f"Early stopping (pérdida) en la época {epoch}")
						break

	if use_val and best_state is not None:
		model.load_state_dict(best_state)
		print(f"Pesos restaurados de la época {best_epoch} (val_{select_metric}={best_score:.4f})")

	# Embeddings finales
	model.eval()
	list_df_node_embeddings = []
	with torch.no_grad():
		for subgroup_id in subgroups_id:
			data = train_loader[f"{group_id}_{subgroup_id}"]
			z = _encode(model, data, encoder)
			df = pd.DataFrame(z.cpu().numpy())
			df["subgroup_id"] = [subgroup_id] * len(df)
			df.insert(0, "Id", range(len(df)))  # solo para datos que no son MS
			list_df_node_embeddings.append(df)
	df_node_embeddings_concat = pd.concat(list_df_node_embeddings, ignore_index=True)

	if save_outputs:
		emb_dir = f"experiments/output/{exp}/node_embeddings"
		loss_dir = f"experiments/output/{exp}/loss"
		os.makedirs(emb_dir, exist_ok=True)
		os.makedirs(loss_dir, exist_ok=True)
		df_node_embeddings_concat.to_csv(f"{emb_dir}/{encoder}_{group_id}.csv", index=False)
		np.save(f"{loss_dir}/{encoder}_{group_id}.npy", np.array(list_loss))

	if torch.cuda.is_available():
		torch.cuda.empty_cache()

	return {
		"best_epoch": best_epoch if use_val else None,
		"best_val_score": best_score if use_val else None,
		"stopped_epoch": stopped_epoch,
		"epochs_run": len(list_loss),
		"loss": list_loss,
		"val_history": history,
	}

In [16]:
# [MEJORA 1] Hiperparámetros de entrenamiento y partición de pares en un solo lugar
SEED = 42
WEIGHT_DECAY = weight_decay         # antes fijo dentro de la función
HEADS = 4                    # solo GAT / GATE

# Selección de modelo (usa anclajes -> supervisión; poner False para el protocolo no supervisado)
USE_VALIDATION = False
VAL_FRAC = 0.2
EVAL_EVERY = 5
SELECT_METRIC = "mrr"        # "mrr" | "hit@1" | "hit@5" | "hit@10" | "hit@50"
RETRIEVAL = "l2"             # "l2" (como el paper y la evaluación final) | "cosine"

# Objetivo de entrenamiento (valores por defecto = comportamiento previo / paper)
DECODER = "dot"              # "dot" | "cosine" (con TAU y sesgo aprendible)
TAU = 0.2
NEG_RATIO = 1.0              # negativos por positivo
AUG_P = 0.0                  # probabilidad de eliminar cada arista al codificar (experimento A/B)
GRAD_CLIP = None             # p. ej. 1.0

# Con validación el criterio se mide en épocas: 50 = 10 evaluaciones sin mejora con EVAL_EVERY = 5
PATIENCE = 50 if USE_VALIDATION else patience
WARMUP = 10

# Nombre en `encoders` -> tipo de convolución de model_PyG.TGAE
ENCODER_TO_CONV = {"GCNRes": "gcnres", "GIN": "gin", "GINE": "gine",
				   "GCN": "gcn", "GAT": "gatv2", "GATE": "gatv2e"}
# Evaluation
KS = (1, 5, 10, 50)

all_pairs = df_node_alignment_truth.values.astype(np.int64)   # [K, 2]: (nodo en grafo 1, nodo en grafo 2)
if USE_VALIDATION:
	VAL_PAIRS, EVAL_PAIRS = make_val_split(all_pairs, val_frac=VAL_FRAC, seed=SEED)
else:
	VAL_PAIRS, EVAL_PAIRS = None, all_pairs
df_eval_truth = pd.DataFrame(EVAL_PAIRS)
print("Pares totales:", len(all_pairs), "| validación:", 0 if VAL_PAIRS is None else len(VAL_PAIRS),
	  "| evaluación:", len(EVAL_PAIRS))

Pares totales: 1118 | validación: 0 | evaluación: 1118

In [17]:
encoders

['GCNRes', 'GIN', 'GINE', 'GCN', 'GAT', 'GATE']

In [18]:
list_train_set

[['douban_1', 'douban_2']]

In [19]:
list_train_loader

[{'douban_1': Data(x=[3906, 538], edge_index=[2, 16328], edge_attr=[16328, 2]),
  'douban_2': Data(x=[1118, 538], edge_index=[2, 3022], edge_attr=[3022, 2])}]

In [20]:
num_exp = 10 # Change

list_exp = []

for n_exp in range(num_exp):
	print(n_exp)
	#---
	# Train
	#---

	# list_runtime = []
	# list_fit_info = []
	for encoder in encoders:
		for i, train_loader in enumerate(list_train_loader):
			group_id = groups_id[i]
			subgroups_id_ = subgroups_id[group_id]
			train_set = list_train_set[i]

			no_samples = len(train_set)
			input_dim = train_loader[train_set[0]].num_node_features
			edge_dim = train_loader[train_set[0]].edge_attr.size(1) if encoder in ("GINE", "GATE") else None

			# [MEJORA 4a] Semilla ANTES de construir el modelo: antes cada encoder continuaba el flujo aleatorio
			# del anterior (resultados dependientes del orden de `encoders`) y los pesos iniciales no se repetían.
			set_seed(SEED + n_exp)
			model = TGAE(ENCODER_TO_CONV[encoder], NUM_HIDDEN_LAYERS, input_dim, HIDDEN_DIM,
						output_feature_size, edge_dim=edge_dim, heads=HEADS).to(device)

			print("Fitting model")
			print(encoder, dataset, train_set, lr, epochs, input_dim, output_feature_size, no_samples)

			# [MEJORA 4b] CUDA es asíncrono: sincronizar antes y después para medir el tiempo real.
			# Nota: con validación activa, el tiempo incluye las evaluaciones periódicas.
			if device.type == "cuda":
				torch.cuda.synchronize(device)
			start_time = time.perf_counter()

			info_fit = fit_TGAE_subgraph(
				model, encoder, dataset, group_id, subgroups_id_, train_loader, train_set, no_samples,
				epochs, lr, WEIGHT_DECAY,
				val_pairs=VAL_PAIRS, eval_every=EVAL_EVERY, select_metric=SELECT_METRIC, retrieval=RETRIEVAL,
				decoder=DECODER, tau=TAU, neg_ratio=NEG_RATIO, aug_p=AUG_P, grad_clip=GRAD_CLIP,
				patience=PATIENCE, warmup=WARMUP,
			)

			if device.type == "cuda":
				torch.cuda.synchronize(device)
			end_time = time.perf_counter()
			execution_time = end_time - start_time
			list_exp.append([raw_data_file, encoder, output_feature_size, NUM_HIDDEN_LAYERS, n_exp + 1, execution_time])
			
			# list_runtime.append(execution_time)
			# list_fit_info.append({"encoder": encoder, "group_id": group_id,
			# 					**{k: v for k, v in info_fit.items() if k not in ("loss", "val_history")}})

			# [MEJORA 4c] Liberar el modelo (12 capas x 1024) antes del siguiente encoder
			del model
			if device.type == "cuda":
				torch.cuda.empty_cache()
	#---
	# Similarity analysis
	#---
	k = 1 # Change
	for encoder in encoders:
		for group_id in groups_id:
			df_node_embeddings_concat = pd.read_csv(f"experiments/output/{exp}/node_embeddings/{encoder}_{group_id}.csv", dtype={"subgroup_id": "string"})
			# Id, 0, 1,	2, ..., subgroup_id

			subgroups_id_ = subgroups_id[group_id]

			# Calculate distance matrix (KNN)
			knn = NearestNeighbors(n_neighbors=k, metric="euclidean")

			df_node_embeddings = df_node_embeddings_concat[df_node_embeddings_concat["subgroup_id"] == subgroups_id_[0]]
			x = df_node_embeddings.iloc[:, 1:-1].values

			df_node_alignment = pd.DataFrame()
			df_node_alignment[f"{group_id}_{subgroups_id_[0]}"] = df_node_embeddings["Id"].values

			for subgroup_id in subgroups_id_[1:]:
				df_node_embeddings = df_node_embeddings_concat[df_node_embeddings_concat["subgroup_id"] == subgroup_id]
				y = df_node_embeddings.iloc[:, 1:-1].values

				knn.fit(y)
				distances, indices = knn.kneighbors(x)
				indices = indices.squeeze() # (N,)

				df_node_alignment[f"{group_id}_{subgroup_id}"] = df_node_embeddings["Id"].values[indices]
				
				""" df_node_alignment[f"distances"] = distances
				avg_distances = df_node_alignment["distances"].mean()
				df_node_alignment = df_node_alignment[df_node_alignment["distances"] <= avg_distances].iloc[:, :-1]
				df_node_alignment """
			
			# Save previus node alignment
			df_node_alignment.to_csv(f"experiments/output/{exp}/filter_raw/node_alignment_{encoder}_{group_id}.csv")
			# display(df_node_alignment)

			# Find node alignment for all datasets
			""" df_node_alignment_filter = df_node_alignment[df_node_alignment.nunique(axis=1) == 1]
			list_count_meta.append([encoder, group_id, len(df_node_alignment_filter), len(df_node_alignment)])
			# print(len(df_node_alignment_filter))
			# display(df_node_alignment_filter)
			print(f"{encoder}-{group_id}: {len(df_node_alignment_filter)}")
			
			# Save common node id
			# common_node_id = df_node_alignment_filter.iloc[:, 0].values
			# np.save(f"experiments/output/{exp}/common_nodes/{encoder}_{group_id}.npy", np.array(common_node_id)) """

			# Save common node id as .csv
			df_common_node_id = df_node_alignment.iloc[:, [0, 1]].copy() # df_common_node_id = df_node_alignment_filter.iloc[:, [0, 1]].copy()
			df_common_node_id.sort_values(by=df_common_node_id.columns[0], inplace=True)
			df_common_node_id.to_csv(f"experiments/output/{exp}/common_nodes/{encoder}_{group_id}.csv", index=False, header=False)

	# Intersection and Union
	""" list_common_node_id = []
	for encoder in encoders:
		for group_id in groups_id:
			# Read common node
			common_node_id = np.load(f"experiments/output/{exp}/common_nodes/{encoder}_{group_id}.npy")
			list_common_node_id.append(common_node_id)

		common_node_id_union = list(set.union(*map(set, list_common_node_id)))
		common_node_id_intersection = list(set.intersection(*map(set, list_common_node_id)))

		# Save common node id
		np.save(f"experiments/output/{exp}/common_nodes/{encoder}_union.npy", np.array(common_node_id_union))
		np.save(f"experiments/output/{exp}/common_nodes/{encoder}_intersection.npy", np.array(common_node_id_intersection)) """

	#---
	# Evaluation
	#---
	# list_accuracy = []
	# list_encoder = []

	for j, encoder in enumerate(encoders):
		for group_id in groups_id:
			# Read node alignment
			df_common_node_id = pd.read_csv(f"experiments/output/{exp}/common_nodes/{encoder}_{group_id}.csv", header=None)
			# df_common_node_id[[0, 1]] = np.sort(df_common_node_id[[0, 1]], axis=1)

			# Evaluation
			df_matching = df_common_node_id.merge(df_node_alignment_truth, on=[0, 1], how="inner")

			# Accuracy
			accuracy = len(df_matching) / len(df_node_alignment_truth)
			
			list_exp[len(encoders) * n_exp + j].append(accuracy)
			# list_accuracy.append(accuracy)
			# list_encoder.append(encoder)

	#---
	# Evaluation (based on PlanetAlign)
	#---

	# Get node embeddings
	dict_node_embeddings = {}
	for encoder in encoders:
		list_node_embeddings = []
		for group_id in groups_id:
			df_node_embeddings_concat = pd.read_csv(f"experiments/output/{exp}/node_embeddings/{encoder}_{group_id}.csv", dtype={"subgroup_id": "string"})
			# Id, 0, 1,	2, ..., subgroup_id

			for subgroup_id in subgroups_id[group_id]:
				df_node_embeddings = df_node_embeddings_concat[df_node_embeddings_concat["subgroup_id"] == subgroup_id]
				list_node_embeddings.append(df_node_embeddings)
		dict_node_embeddings[encoder] = list_node_embeddings

	# Evaluation
	# list_metrics = []

	df_node_alignment_truth_ = torch.tensor(df_node_alignment_truth.values)

	for j, encoder in enumerate(encoders):
		list_node_embeddings = dict_node_embeddings[encoder]
		# Id, 0, 1,	2, ..., subgroup_id

		emb1 = list_node_embeddings[0].iloc[:, 1:-1]
		emb2 = list_node_embeddings[1].iloc[:, 1:-1]

		emb1_ = torch.tensor(emb1.values)
		emb2_ = torch.tensor(emb2.values)

		# Similarity matrix
		# Option 1
		S = pairwise_cosine_similarity(emb1_, emb2_)

		# Option 2
		""" S = cosine_similarity(emb1, emb2)
		S = torch.tensor(S) """

		# Option 3
		""" S = pairwise_distances(emb1, emb2, metric="euclidean")
		S = torch.tensor(S)
		S = -S # convert distances matrix to similarity matrix """
		
		# Option 4
		""" S = torch.cdist(emb1_, emb2_, 2)
		S = -S # convert distances matrix to similarity matrix """

		hits = hits_ks_scores(S, df_node_alignment_truth_, ks=KS, mode="mean")
		mrr = mrr_score(S, df_node_alignment_truth_, mode="mean")
		print(encoder, hits, mrr)

		list_exp[len(encoders) * n_exp + j] += list(hits.values()) + [mrr]

0
Fitting model
GCNRes exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 165:  33%|███▎      | 164/500 [00:16<00:34,  9.84it/s, Loss: 0.4460]

Early stopping (pérdida) en la época 165
Fitting model
GIN exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 99:  20%|█▉        | 98/500 [00:25<01:44,  3.84it/s, Loss: 0.4071]

Early stopping (pérdida) en la época 99
Fitting model
GINE exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 126:  25%|██▌       | 125/500 [00:36<01:48,  3.47it/s, Loss: 0.5056]

Early stopping (pérdida) en la época 126
Fitting model
GCN exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 71:  14%|█▍        | 70/500 [00:06<00:40, 10.64it/s, Loss: 0.4229]

Early stopping (pérdida) en la época 71
Fitting model
GAT exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 71:  14%|█▍        | 70/500 [00:13<01:20,  5.37it/s, Loss: 0.4212]

Early stopping (pérdida) en la época 71
Fitting model
GATE exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 71:  14%|█▍        | 70/500 [00:13<01:25,  5.06it/s, Loss: 0.4200]

Early stopping (pérdida) en la época 71
GCNRes {1: 0.26654740422964096, 5: 0.4539355933666229, 10: 0.5402504354715347, 50: 0.7406082451343536} 0.3598587214946747
GIN {1: 0.3443649411201477, 5: 0.5156529396772385, 10: 0.5970482975244522, 50: 0.7902504205703735} 0.43031586706638336
GINE {1: 0.22719141095876694, 5: 0.3649373948574066, 10: 0.447674423456192, 50: 0.6444543749094009} 0.3002644404768944
GCN {1: 0.2580500841140747, 5: 0.4414132535457611, 10: 0.5263863950967789, 50: 0.737030416727066} 0.3491926044225693
GAT {1: 0.273255817592144, 5: 0.44991055130958557, 10: 0.5348837077617645, 50: 0.743291586637497} 0.3622090443968773
GATE {1: 0.2723613604903221, 5: 0.45169946551322937, 10: 0.5335420221090317, 50: 0.7397137880325317} 0.36160634458065033
1
Fitting model
GCNRes exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 101:  20%|██        | 100/500 [00:10<00:41,  9.63it/s, Loss: 0.4792]

Early stopping (pérdida) en la época 101
Fitting model
GIN exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 65:  13%|█▎        | 64/500 [00:17<01:57,  3.73it/s, Loss: 0.4404]

Early stopping (pérdida) en la época 65
Fitting model
GINE exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 100:  20%|█▉        | 99/500 [00:28<01:56,  3.44it/s, Loss: 0.5242]

Early stopping (pérdida) en la época 100
Fitting model
GCN exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 64:  13%|█▎        | 63/500 [00:05<00:41, 10.60it/s, Loss: 0.4286]

Early stopping (pérdida) en la época 64
Fitting model
GAT exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 114:  23%|██▎       | 113/500 [00:20<01:11,  5.41it/s, Loss: 0.4067]

Early stopping (pérdida) en la época 114
Fitting model
GATE exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 92:  18%|█▊        | 91/500 [00:17<01:20,  5.08it/s, Loss: 0.4123]

Early stopping (pérdida) en la época 92
GCNRes {1: 0.2759391814470291, 5: 0.460644006729126, 10: 0.5559033900499344, 50: 0.7598389983177185} 0.3693704605102539
GIN {1: 0.32871198654174805, 5: 0.5089445412158966, 10: 0.5791592299938202, 50: 0.764311283826828} 0.41680824756622314
GINE {1: 0.21109124273061752, 5: 0.3452593982219696, 10: 0.4217352271080017, 50: 0.6158318370580673} 0.28306078910827637
GCN {1: 0.25581395626068115, 5: 0.43738819658756256, 10: 0.5272808521986008, 50: 0.7325581312179565} 0.34486569464206696
GAT {1: 0.253577820956707, 5: 0.43828265368938446, 10: 0.5357781648635864, 50: 0.7482110857963562} 0.34788139164447784
GATE {1: 0.2822003588080406, 5: 0.4530411660671234, 10: 0.5474060773849487, 50: 0.756708413362503} 0.36914557963609695
2
Fitting model
GCNRes exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 131:  26%|██▌       | 130/500 [00:13<00:38,  9.58it/s, Loss: 0.4609]

Early stopping (pérdida) en la época 131
Fitting model
GIN exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 104:  21%|██        | 103/500 [00:27<01:46,  3.74it/s, Loss: 0.4313]

Early stopping (pérdida) en la época 104
Fitting model
GINE exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 154:  31%|███       | 153/500 [00:44<01:40,  3.45it/s, Loss: 0.4945]

Early stopping (pérdida) en la época 154
Fitting model
GCN exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 55:  11%|█         | 54/500 [00:05<00:42, 10.48it/s, Loss: 0.4332]

Early stopping (pérdida) en la época 55
Fitting model
GAT exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 109:  22%|██▏       | 108/500 [00:19<01:12,  5.40it/s, Loss: 0.4037]

Early stopping (pérdida) en la época 109
Fitting model
GATE exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 87:  17%|█▋        | 86/500 [00:16<01:21,  5.08it/s, Loss: 0.4106]

Early stopping (pérdida) en la época 87
GCNRes {1: 0.2661001831293106, 5: 0.4633273631334305, 10: 0.5500894337892532, 50: 0.7544722855091095} 0.36396025121212006
GIN {1: 0.348837211728096, 5: 0.5241502821445465, 10: 0.6010733395814896, 50: 0.7938282787799835} 0.43559272587299347
GINE {1: 0.23255814611911774, 5: 0.3743291646242142, 10: 0.454830065369606, 50: 0.658318430185318} 0.30737684667110443
GCN {1: 0.25581395626068115, 5: 0.43291591107845306, 10: 0.5147584974765778, 50: 0.7325581312179565} 0.3451477587223053
GAT {1: 0.2652057185769081, 5: 0.43649373948574066, 10: 0.5299642235040665, 50: 0.743291586637497} 0.35446450859308243
GATE {1: 0.26744186133146286, 5: 0.44543829560279846, 10: 0.5254919528961182, 50: 0.7392665445804596} 0.35464541614055634
3
Fitting model
GCNRes exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 190:  38%|███▊      | 189/500 [00:19<00:32,  9.65it/s, Loss: 0.4404]

Early stopping (pérdida) en la época 190
Fitting model
GIN exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 100:  20%|█▉        | 99/500 [00:26<01:47,  3.74it/s, Loss: 0.4240]

Early stopping (pérdida) en la época 100
Fitting model
GINE exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 197:  39%|███▉      | 196/500 [00:56<01:27,  3.46it/s, Loss: 0.4848]

Early stopping (pérdida) en la época 197
Fitting model
GCN exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 55:  11%|█         | 54/500 [00:05<00:42, 10.52it/s, Loss: 0.4328]

Early stopping (pérdida) en la época 55
Fitting model
GAT exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 89:  18%|█▊        | 88/500 [00:16<01:16,  5.39it/s, Loss: 0.4182]

Early stopping (pérdida) en la época 89
Fitting model
GATE exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 55:  11%|█         | 54/500 [00:10<01:28,  5.05it/s, Loss: 0.4337]

Early stopping (pérdida) en la época 55
GCNRes {1: 0.2687835395336151, 5: 0.4512522369623184, 10: 0.5254919677972794, 50: 0.7338998019695282} 0.359425887465477
GIN {1: 0.3497316688299179, 5: 0.5165474116802216, 10: 0.6033094674348831, 50: 0.7960644066333771} 0.4351201355457306
GINE {1: 0.2419499158859253, 5: 0.38998210430145264, 10: 0.47182467579841614, 50: 0.6744185984134674} 0.32008273899555206
GCN {1: 0.262522354722023, 5: 0.446332722902298, 10: 0.53220035135746, 50: 0.7517889142036438} 0.35299427807331085
GAT {1: 0.28264757990837097, 5: 0.4543828219175339, 10: 0.5384615510702133, 50: 0.7459749579429626} 0.3706424832344055
GATE {1: 0.27549195289611816, 5: 0.44454382359981537, 10: 0.5317531228065491, 50: 0.7361359596252441} 0.3614000752568245
4
Fitting model
GCNRes exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 131:  26%|██▌       | 130/500 [00:13<00:38,  9.63it/s, Loss: 0.4614]

Early stopping (pérdida) en la época 131
Fitting model
GIN exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 126:  25%|██▌       | 125/500 [00:33<01:40,  3.75it/s, Loss: 0.4012]

Early stopping (pérdida) en la época 126
Fitting model
GINE exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 194:  39%|███▊      | 193/500 [00:55<01:28,  3.46it/s, Loss: 0.4847]

Early stopping (pérdida) en la época 194
Fitting model
GCN exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 36:   7%|▋         | 35/500 [00:03<00:44, 10.40it/s, Loss: 0.4442]

Early stopping (pérdida) en la época 36
Fitting model
GAT exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 105:  21%|██        | 104/500 [00:19<01:13,  5.38it/s, Loss: 0.4078]

Early stopping (pérdida) en la época 105
Fitting model
GATE exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 129:  26%|██▌       | 128/500 [00:25<01:14,  4.99it/s, Loss: 0.3997]

Early stopping (pérdida) en la época 129
GCNRes {1: 0.26744186133146286, 5: 0.4610912501811981, 10: 0.552325576543808, 50: 0.7549194991588593} 0.36389027535915375
GIN {1: 0.3515205681324005, 5: 0.5237030386924744, 10: 0.6055456250905991, 50: 0.8076923191547394} 0.4387364089488983
GINE {1: 0.23881931602954865, 5: 0.3940071612596512, 10: 0.4713774621486664, 50: 0.6690518856048584} 0.317935511469841
GCN {1: 0.26833631098270416, 5: 0.4503577649593353, 10: 0.5375670790672302, 50: 0.7495527863502502} 0.35933761298656464
GAT {1: 0.25402504950761795, 5: 0.4449910670518875, 10: 0.5286225527524948, 50: 0.7406082153320312} 0.34725096076726913
GATE {1: 0.2669946327805519, 5: 0.44454383850097656, 10: 0.5357781797647476, 50: 0.7531305849552155} 0.3566078394651413
5
Fitting model
GCNRes exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 96:  19%|█▉        | 95/500 [00:09<00:42,  9.50it/s, Loss: 0.4879]

Early stopping (pérdida) en la época 96
Fitting model
GIN exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 107:  21%|██        | 106/500 [00:28<01:45,  3.74it/s, Loss: 0.4048]

Early stopping (pérdida) en la época 107
Fitting model
GINE exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 113:  22%|██▏       | 112/500 [00:32<01:52,  3.44it/s, Loss: 0.5209]

Early stopping (pérdida) en la época 113
Fitting model
GCN exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 57:  11%|█         | 56/500 [00:05<00:42, 10.46it/s, Loss: 0.4365]

Early stopping (pérdida) en la época 57
Fitting model
GAT exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 111:  22%|██▏       | 110/500 [00:20<01:12,  5.40it/s, Loss: 0.4059]

Early stopping (pérdida) en la época 111
Fitting model
GATE exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 114:  23%|██▎       | 113/500 [00:22<01:16,  5.09it/s, Loss: 0.4109]

Early stopping (pérdida) en la época 114
GCNRes {1: 0.27370304614305496, 5: 0.46645796298980713, 10: 0.5563506335020065, 50: 0.7598389983177185} 0.3686443120241165
GIN {1: 0.33944544196128845, 5: 0.5187835395336151, 10: 0.5997316539287567, 50: 0.7974061071872711} 0.43049682676792145
GINE {1: 0.22137745469808578, 5: 0.3568872958421707, 10: 0.43559928238391876, 50: 0.6296958923339844} 0.2928014397621155
GCN {1: 0.26386404037475586, 5: 0.43649373948574066, 10: 0.5183363258838654, 50: 0.7374776303768158} 0.34994925558567047
GAT {1: 0.26475849747657776, 5: 0.4472271800041199, 10: 0.5277280956506729, 50: 0.7455277144908905} 0.35622725635766983
GATE {1: 0.26475849747657776, 5: 0.44007153809070587, 10: 0.5348837375640869, 50: 0.7437388300895691} 0.3550638258457184
6
Fitting model
GCNRes exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 166:  33%|███▎      | 165/500 [00:17<00:34,  9.65it/s, Loss: 0.4509]

Early stopping (pérdida) en la época 166
Fitting model
GIN exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 126:  25%|██▌       | 125/500 [00:33<01:40,  3.75it/s, Loss: 0.3967]

Early stopping (pérdida) en la época 126
Fitting model
GINE exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 142:  28%|██▊       | 141/500 [00:41<01:44,  3.42it/s, Loss: 0.4976]

Early stopping (pérdida) en la época 142
Fitting model
GCN exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 37:   7%|▋         | 36/500 [00:03<00:44, 10.41it/s, Loss: 0.4355]

Early stopping (pérdida) en la época 37
Fitting model
GAT exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 135:  27%|██▋       | 134/500 [00:24<01:07,  5.39it/s, Loss: 0.4062]

Early stopping (pérdida) en la época 135
Fitting model
GATE exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 109:  22%|██▏       | 108/500 [00:21<01:17,  5.08it/s, Loss: 0.4046]

Early stopping (pérdida) en la época 109
GCNRes {1: 0.2652057260274887, 5: 0.45169946551322937, 10: 0.534436509013176, 50: 0.7397137880325317} 0.35744380950927734
GIN {1: 0.3506261110305786, 5: 0.5263864099979401, 10: 0.6086762249469757, 50: 0.8041144907474518} 0.43826547265052795
GINE {1: 0.22987478226423264, 5: 0.3734347075223923, 10: 0.4481216371059418, 50: 0.6462433040142059} 0.303539015352726
GCN {1: 0.2705724462866783, 5: 0.4512522369623184, 10: 0.5389087796211243, 50: 0.7468694150447845} 0.36002175509929657
GAT {1: 0.2652057185769081, 5: 0.4432021379470825, 10: 0.5317531228065491, 50: 0.7477638721466064} 0.3561154678463936
GATE {1: 0.2723613679409027, 5: 0.44543828070163727, 10: 0.5357781797647476, 50: 0.7571556568145752} 0.3621862083673477
7
Fitting model
GCNRes exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 104:  21%|██        | 103/500 [00:10<00:41,  9.63it/s, Loss: 0.4829]

Early stopping (pérdida) en la época 104
Fitting model
GIN exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 56:  11%|█         | 55/500 [00:14<01:59,  3.71it/s, Loss: 0.4516]

Early stopping (pérdida) en la época 56
Fitting model
GINE exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 125:  25%|██▍       | 124/500 [00:35<01:48,  3.45it/s, Loss: 0.5065]

Early stopping (pérdida) en la época 125
Fitting model
GCN exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 75:  15%|█▍        | 74/500 [00:07<00:40, 10.57it/s, Loss: 0.4258]

Early stopping (pérdida) en la época 75
Fitting model
GAT exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 94:  19%|█▊        | 93/500 [00:17<01:15,  5.40it/s, Loss: 0.4122]

Early stopping (pérdida) en la época 94
Fitting model
GATE exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 94:  19%|█▊        | 93/500 [00:18<01:20,  5.07it/s, Loss: 0.4091]

Early stopping (pérdida) en la época 94
GCNRes {1: 0.27549195289611816, 5: 0.47093023359775543, 10: 0.559481218457222, 50: 0.7634167969226837} 0.3720323294401169
GIN {1: 0.33586761355400085, 5: 0.512969583272934, 10: 0.5836315006017685, 50: 0.7705724537372589} 0.42392732203006744
GINE {1: 0.22361359000205994, 5: 0.3658318519592285, 10: 0.4414132386445999, 50: 0.6408765614032745} 0.2979065775871277
GCN {1: 0.2553667277097702, 5: 0.43917709589004517, 10: 0.5348837226629257, 50: 0.7495527863502502} 0.34825216233730316
GAT {1: 0.2553667277097702, 5: 0.43470484018325806, 10: 0.5116278976202011, 50: 0.737030416727066} 0.3445996344089508
GATE {1: 0.2562611773610115, 5: 0.4387298673391342, 10: 0.5259391814470291, 50: 0.7365831732749939} 0.3481805622577667
8
Fitting model
GCNRes exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 123:  24%|██▍       | 122/500 [00:12<00:39,  9.62it/s, Loss: 0.4707]

Early stopping (pérdida) en la época 123
Fitting model
GIN exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 75:  15%|█▍        | 74/500 [00:19<01:54,  3.72it/s, Loss: 0.4183]

Early stopping (pérdida) en la época 75
Fitting model
GINE exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 125:  25%|██▍       | 124/500 [00:35<01:49,  3.45it/s, Loss: 0.5068]

Early stopping (pérdida) en la época 125
Fitting model
GCN exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 37:   7%|▋         | 36/500 [00:03<00:44, 10.48it/s, Loss: 0.4359]

Early stopping (pérdida) en la época 37
Fitting model
GAT exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 75:  15%|█▍        | 74/500 [00:13<01:19,  5.38it/s, Loss: 0.4222]

Early stopping (pérdida) en la época 75
Fitting model
GATE exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 75:  15%|█▍        | 74/500 [00:14<01:24,  5.06it/s, Loss: 0.4208]

Early stopping (pérdida) en la época 75
GCNRes {1: 0.2687835469841957, 5: 0.460196778178215, 10: 0.5567978620529175, 50: 0.7571556568145752} 0.36502619087696075
GIN {1: 0.34123434126377106, 5: 0.5187835395336151, 10: 0.5948121696710587, 50: 0.7857781946659088} 0.42790140211582184
GINE {1: 0.22719141095876694, 5: 0.3725402504205704, 10: 0.4472271800041199, 50: 0.6404293477535248} 0.3014957755804062
GCN {1: 0.26744185388088226, 5: 0.44543829560279846, 10: 0.5335420519113541, 50: 0.7450805008411407} 0.35800836980342865
GAT {1: 0.28264757990837097, 5: 0.4597495496273041, 10: 0.5424865782260895, 50: 0.757602870464325} 0.372799851000309
GATE {1: 0.26118067651987076, 5: 0.43738821148872375, 10: 0.5259391963481903, 50: 0.7401610016822815} 0.3514101281762123
9
Fitting model
GCNRes exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 110:  22%|██▏       | 109/500 [00:11<00:40,  9.59it/s, Loss: 0.4731]

Early stopping (pérdida) en la época 110
Fitting model
GIN exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 85:  17%|█▋        | 84/500 [00:22<01:51,  3.74it/s, Loss: 0.4122]

Early stopping (pérdida) en la época 85
Fitting model
GINE exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 158:  31%|███▏      | 157/500 [00:45<01:39,  3.45it/s, Loss: 0.4907]

Early stopping (pérdida) en la época 158
Fitting model
GCN exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 49:  10%|▉         | 48/500 [00:04<00:42, 10.53it/s, Loss: 0.4328]

Early stopping (pérdida) en la época 49
Fitting model
GAT exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 131:  26%|██▌       | 130/500 [00:24<01:08,  5.41it/s, Loss: 0.4006]

Early stopping (pérdida) en la época 131
Fitting model
GATE exp108 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 131:  26%|██▌       | 130/500 [00:25<01:12,  5.09it/s, Loss: 0.3990]

Early stopping (pérdida) en la época 131
GCNRes {1: 0.27191413193941116, 5: 0.4660107344388962, 10: 0.5559034049510956, 50: 0.7616278827190399} 0.3691936731338501
GIN {1: 0.34123434126377106, 5: 0.5138640403747559, 10: 0.5992844253778458, 50: 0.7830948233604431} 0.42854610085487366
GINE {1: 0.23792486637830734, 5: 0.3783542066812515, 10: 0.45796066522598267, 50: 0.6614490151405334} 0.31228435784578323
GCN {1: 0.25402503460645676, 5: 0.4440965950489044, 10: 0.5326475948095322, 50: 0.7428443431854248} 0.3486499786376953
GAT {1: 0.25223612785339355, 5: 0.440518781542778, 10: 0.5317531377077103, 50: 0.7307692468166351} 0.3462388962507248
GATE {1: 0.2616279050707817, 5: 0.44901609420776367, 10: 0.5344364941120148, 50: 0.7410554587841034} 0.3526886850595474

### Summary

In [21]:
list_exp

[['douban',
  'GCNRes',
  512,
  12,
  1,
  17.835656721959822,
  0.2808586762075134,
  0.26654740422964096,
  0.4539355933666229,
  0.5402504354715347,
  0.7406082451343536,
  0.3598587214946747],
 ['douban',
  'GIN',
  512,
  12,
  1,
  26.788133049965836,
  0.42486583184257604,
  0.3443649411201477,
  0.5156529396772385,
  0.5970482975244522,
  0.7902504205703735,
  0.43031586706638336],
 ['douban',
  'GINE',
  512,
  12,
  1,
  37.25843173393514,
  0.28622540250447226,
  0.22719141095876694,
  0.3649373948574066,
  0.447674423456192,
  0.6444543749094009,
  0.3002644404768944],
 ['douban',
  'GCN',
  512,
  12,
  1,
  7.7384405840421095,
  0.2182468694096601,
  0.2580500841140747,
  0.4414132535457611,
  0.5263863950967789,
  0.737030416727066,
  0.3491926044225693],
 ['douban',
  'GAT',
  512,
  12,
  1,
  14.210501609952189,
  0.2817531305903399,
  0.273255817592144,
  0.44991055130958557,
  0.5348837077617645,
  0.743291586637497,
  0.3622090443968773],
 ['douban',
  'GATE',
  512,
  12,
  1,
  15.04446490004193,
  0.28622540250447226,
  0.2723613604903221,
  0.45169946551322937,
  0.5335420221090317,
  0.7397137880325317,
  0.36160634458065033],
 ['douban',
  'GCNRes',
  512,
  12,
  2,
  11.550586584955454,
  0.2772808586762075,
  0.2759391814470291,
  0.460644006729126,
  0.5559033900499344,
  0.7598389983177185,
  0.3693704605102539],
 ['douban',
  'GIN',
  512,
  12,
  2,
  18.372277676011436,
  0.40429338103756707,
  0.32871198654174805,
  0.5089445412158966,
  0.5791592299938202,
  0.764311283826828,
  0.41680824756622314],
 ['douban',
  'GINE',
  512,
  12,
  2,
  30.005887640989386,
  0.28354203935599287,
  0.21109124273061752,
  0.3452593982219696,
  0.4217352271080017,
  0.6158318370580673,
  0.28306078910827637],
 ['douban',
  'GCN',
  512,
  12,
  2,
  7.084154918091372,
  0.22271914132379247,
  0.25581395626068115,
  0.43738819658756256,
  0.5272808521986008,
  0.7325581312179565,
  0.34486569464206696],
 ['douban',
  'GAT',
  512,
  12,
  2,
  22.08143561705947,
  0.28711985688729874,
  0.253577820956707,
  0.43828265368938446,
  0.5357781648635864,
  0.7482110857963562,
  0.34788139164447784],
 ['douban',
  'GATE',
  512,
  12,
  2,
  19.12587456603069,
  0.295169946332737,
  0.2822003588080406,
  0.4530411660671234,
  0.5474060773849487,
  0.756708413362503,
  0.36914557963609695],
 ['douban',
  'GCNRes',
  512,
  12,
  3,
  14.722129364963621,
  0.2817531305903399,
  0.2661001831293106,
  0.4633273631334305,
  0.5500894337892532,
  0.7544722855091095,
  0.36396025121212006],
 ['douban',
  'GIN',
  512,
  12,
  3,
  28.766182468039915,
  0.43559928443649376,
  0.348837211728096,
  0.5241502821445465,
  0.6010733395814896,
  0.7938282787799835,
  0.43559272587299347],
 ['douban',
  'GINE',
  512,
  12,
  3,
  45.59021860791836,
  0.29785330948121647,
  0.23255814611911774,
  0.3743291646242142,
  0.454830065369606,
  0.658318430185318,
  0.30737684667110443],
 ['douban',
  'GCN',
  512,
  12,
  3,
  6.324271605000831,
  0.21377459749552774,
  0.25581395626068115,
  0.43291591107845306,
  0.5147584974765778,
  0.7325581312179565,
  0.3451477587223053],
 ['douban',
  'GAT',
  512,
  12,
  3,
  21.201697165030055,
  0.3094812164579606,
  0.2652057185769081,
  0.43649373948574066,
  0.5299642235040665,
  0.743291586637497,
  0.35446450859308243],
 ['douban',
  'GATE',
  512,
  12,
  3,
  18.113431331003085,
  0.29785330948121647,
  0.26744186133146286,
  0.44543829560279846,
  0.5254919528961182,
  0.7392665445804596,
  0.35464541614055634],
 ['douban',
  'GCNRes',
  512,
  12,
  4,
  20.760976258083247,
  0.2898032200357782,
  0.2687835395336151,
  0.4512522369623184,
  0.5254919677972794,
  0.7338998019695282,
  0.359425887465477],
 ['douban',
  'GIN',
  512,
  12,
  4,
  27.773113737930544,
  0.4418604651162791,
  0.3497316688299179,
  0.5165474116802216,
  0.6033094674348831,
  0.7960644066333771,
  0.4351201355457306],
 ['douban',
  'GINE',
  512,
  12,
  4,
  57.94161463400815,
  0.3076923076923077,
  0.2419499158859253,
  0.38998210430145264,
  0.47182467579841614,
  0.6744185984134674,
  0.32008273899555206],
 ['douban',
  'GCN',
  512,
  12,
  4,
  6.31431209098082,
  0.2039355992844365,
  0.262522354722023,
  0.446332722902298,
  0.53220035135746,
  0.7517889142036438,
  0.35299427807331085],
 ['douban',
  'GAT',
  512,
  12,
  4,
  17.55601530300919,
  0.29695885509839,
  0.28264757990837097,
  0.4543828219175339,
  0.5384615510702133,
  0.7459749579429626,
  0.3706424832344055],
 ['douban',
  'GATE',
  512,
  12,
  4,
  11.918857265030965,
  0.27280858676207514,
  0.27549195289611816,
  0.44454382359981537,
  0.5317531228065491,
  0.7361359596252441,
  0.3614000752568245],
 ['douban',
  'GCNRes',
  512,
  12,
  5,
  14.697888863040134,
  0.2844364937388193,
  0.26744186133146286,
  0.4610912501811981,
  0.552325576543808,
  0.7549194991588593,
  0.36389027535915375],
 ['douban',
  'GIN',
  512,
  12,
  5,
  34.602622841950506,
  0.44364937388193204,
  0.3515205681324005,
  0.5237030386924744,
  0.6055456250905991,
  0.8076923191547394,
  0.4387364089488983],
 ['douban',
  'GINE',
  512,
  12,
  5,
  57.1481896310579,
  0.3112701252236136,
  0.23881931602954865,
  0.3940071612596512,
  0.4713774621486664,
  0.6690518856048584,
  0.317935511469841],
 ['douban',
  'GCN',
  512,
  12,
  5,
  4.55124503292609,
  0.21645796064400716,
  0.26833631098270416,
  0.4503577649593353,
  0.5375670790672302,
  0.7495527863502502,
  0.35933761298656464],
 ['douban',
  'GAT',
  512,
  12,
  5,
  20.537851719069295,
  0.29695885509839,
  0.25402504950761795,
  0.4449910670518875,
  0.5286225527524948,
  0.7406082153320312,
  0.34725096076726913],
 ['douban',
  'GATE',
  512,
  12,
  5,
  27.061176065006293,
  0.30590339892665475,
  0.2669946327805519,
  0.44454383850097656,
  0.5357781797647476,
  0.7531305849552155,
  0.3566078394651413],
 ['douban',
  'GCNRes',
  512,
  12,
  6,
  11.194082205998711,
  0.27996422182468694,
  0.27370304614305496,
  0.46645796298980713,
  0.5563506335020065,
  0.7598389983177185,
  0.3686443120241165],
 ['douban',
  'GIN',
  512,
  12,
  6,
  29.592588801984675,
  0.4329159212880143,
  0.33944544196128845,
  0.5187835395336151,
  0.5997316539287567,
  0.7974061071872711,
  0.43049682676792145],
 ['douban',
  'GINE',
  512,
  12,
  6,
  33.81232045905199,
  0.2880143112701252,
  0.22137745469808578,
  0.3568872958421707,
  0.43559928238391876,
  0.6296958923339844,
  0.2928014397621155],
 ['douban',
  'GCN',
  512,
  12,
  6,
  6.606100118020549,
  0.2146690518783542,
  0.26386404037475586,
  0.43649373948574066,
  0.5183363258838654,
  0.7374776303768158,
  0.34994925558567047],
 ['douban',
  'GAT',
  512,
  12,
  6,
  21.53945426410064,
  0.2924865831842576,
  0.26475849747657776,
  0.4472271800041199,
  0.5277280956506729,
  0.7455277144908905,
  0.35622725635766983],
 ['douban',
  'GATE',
  512,
  12,
  6,
  23.417986745014787,
  0.2826475849731664,
  0.26475849747657776,
  0.44007153809070587,
  0.5348837375640869,
  0.7437388300895691,
  0.3550638258457184],
 ['douban',
  'GCNRes',
  512,
  12,
  7,
  18.301729988888837,
  0.2853309481216458,
  0.2652057260274887,
  0.45169946551322937,
  0.534436509013176,
  0.7397137880325317,
  0.35744380950927734],
 ['douban',
  'GIN',
  512,
  12,
  7,
  34.605099078966305,
  0.4409660107334526,
  0.3506261110305786,
  0.5263864099979401,
  0.6086762249469757,
  0.8041144907474518,
  0.43826547265052795],
 ['douban',
  'GINE',
  512,
  12,
  7,
  42.50469804299064,
  0.29964221824686943,
  0.22987478226423264,
  0.3734347075223923,
  0.4481216371059418,
  0.6462433040142059,
  0.303539015352726],
 ['douban',
  'GCN',
  512,
  12,
  7,
  4.708019087091088,
  0.2110912343470483,
  0.2705724462866783,
  0.4512522369623184,
  0.5389087796211243,
  0.7468694150447845,
  0.36002175509929657],
 ['douban',
  'GAT',
  512,
  12,
  7,
  26.089180122013204,
  0.29874776386404295,
  0.2652057185769081,
  0.4432021379470825,
  0.5317531228065491,
  0.7477638721466064,
  0.3561154678463936],
 ['douban',
  'GATE',
  512,
  12,
  7,
  22.460247201961465,
  0.3023255813953488,
  0.2723613679409027,
  0.44543828070163727,
  0.5357781797647476,
  0.7571556568145752,
  0.3621862083673477],
 ['douban',
  'GCNRes',
  512,
  12,
  8,
  11.901647344930097,
  0.276386404293381,
  0.27549195289611816,
  0.47093023359775543,
  0.559481218457222,
  0.7634167969226837,
  0.3720323294401169],
 ['douban',
  'GIN',
  512,
  12,
  8,
  16.02927592000924,
  0.407871198568873,
  0.33586761355400085,
  0.512969583272934,
  0.5836315006017685,
  0.7705724537372589,
  0.42392732203006744],
 ['douban',
  'GINE',
  512,
  12,
  8,
  37.214391403016634,
  0.28622540250447226,
  0.22361359000205994,
  0.3658318519592285,
  0.4414132386445999,
  0.6408765614032745,
  0.2979065775871277],
 ['douban',
  'GCN',
  512,
  12,
  8,
  8.155258586979471,
  0.2146690518783542,
  0.2553667277097702,
  0.43917709589004517,
  0.5348837226629257,
  0.7495527863502502,
  0.34825216233730316],
 ['douban',
  'GAT',
  512,
  12,
  8,
  18.472737182979472,
  0.2853309481216458,
  0.2553667277097702,
  0.43470484018325806,
  0.5116278976202011,
  0.737030416727066,
  0.3445996344089508],
 ['douban',
  'GATE',
  512,
  12,
  8,
  19.534582399995998,
  0.27191413237924866,
  0.2562611773610115,
  0.4387298673391342,
  0.5259391814470291,
  0.7365831732749939,
  0.3481805622577667],
 ['douban',
  'GCNRes',
  512,
  12,
  9,
  13.871067223022692,
  0.278175313059034,
  0.2687835469841957,
  0.460196778178215,
  0.5567978620529175,
  0.7571556568145752,
  0.36502619087696075],
 ['douban',
  'GIN',
  512,
  12,
  9,
  21.124374459963292,
  0.4186046511627907,
  0.34123434126377106,
  0.5187835395336151,
  0.5948121696710587,
  0.7857781946659088,
  0.42790140211582184],
 ['douban',
  'GINE',
  512,
  12,
  9,
  37.232316624955274,
  0.29874776386404295,
  0.22719141095876694,
  0.3725402504205704,
  0.4472271800041199,
  0.6404293477535248,
  0.3014957755804062],
 ['douban',
  'GCN',
  512,
  12,
  9,
  4.661870735930279,
  0.20661896243291591,
  0.26744185388088226,
  0.44543829560279846,
  0.5335420519113541,
  0.7450805008411407,
  0.35800836980342865],
 ['douban',
  'GAT',
  512,
  12,
  9,
  15.024098486057483,
  0.295169946332737,
  0.28264757990837097,
  0.4597495496273041,
  0.5424865782260895,
  0.757602870464325,
  0.372799851000309],
 ['douban',
  'GATE',
  512,
  12,
  9,
  15.82571170607116,
  0.2701252236135957,
  0.26118067651987076,
  0.43738821148872375,
  0.5259391963481903,
  0.7401610016822815,
  0.3514101281762123],
 ['douban',
  'GCNRes',
  512,
  12,
  10,
  12.578911597956903,
  0.27996422182468694,
  0.27191413193941116,
  0.4660107344388962,
  0.5559034049510956,
  0.7616278827190399,
  0.3691936731338501],
 ['douban',
  'GIN',
  512,
  12,
  10,
  23.68878742097877,
  0.4409660107334526,
  0.34123434126377106,
  0.5138640403747559,
  0.5992844253778458,
  0.7830948233604431,
  0.42854610085487366],
 ['douban',
  'GINE',
  512,
  12,
  10,
  46.77400680095889,
  0.3005366726296959,
  0.23792486637830734,
  0.3783542066812515,
  0.45796066522598267,
  0.6614490151405334,
  0.31228435784578323],
 ['douban',
  'GCN',
  512,
  12,
  10,
  5.789369398029521,
  0.21556350626118068,
  0.25402503460645676,
  0.4440965950489044,
  0.5326475948095322,
  0.7428443431854248,
  0.3486499786376953],
 ['douban',
  'GAT',
  512,
  12,
  10,
  25.249482684070244,
  0.29874776386404295,
  0.25223612785339355,
  0.440518781542778,
  0.5317531377077103,
  0.7307692468166351,
  0.3462388962507248],
 ['douban',
  'GATE',
  512,
  12,
  10,
  26.744608992012218,
  0.29874776386404295,
  0.2616279050707817,
  0.44901609420776367,
  0.5344364941120148,
  0.7410554587841034,
  0.3526886850595474]]

In [22]:
columns = ["Dataset", "Encoder", "Dimension", "Layer", "Seed", "Runtime", "Accuracy"] + [f"Hits@{k}" for k in list(hits.keys())] +  ["MRR"]
df_summary = pd.DataFrame(list_exp, columns=columns)
df_summary.sort_values(by=["Encoder", "Seed"], inplace=True)
df_summary

,Dataset,Encoder,Dimension,Layer,Seed,Runtime,Accuracy,Hits@1,Hits@5,Hits@10,Hits@50,MRR
4,douban,GAT,512,12,1,14.210502,0.281753,0.273256,0.449911,0.534884,0.743292,0.362209
10,douban,GAT,512,12,2,22.081436,0.287120,0.253578,0.438283,0.535778,0.748211,0.347881
16,douban,GAT,512,12,3,21.201697,0.309481,0.265206,0.436494,0.529964,0.743292,0.354465
22,douban,GAT,512,12,4,17.556015,0.296959,0.282648,0.454383,0.538462,0.745975,0.370642
28,douban,GAT,512,12,5,20.537852,0.296959,0.254025,0.444991,0.528623,0.740608,0.347251
34,douban,GAT,512,12,6,21.539454,0.292487,0.264758,0.447227,0.527728,0.745528,0.356227
40,douban,GAT,512,12,7,26.089180,0.298748,0.265206,0.443202,0.531753,0.747764,0.356115
46,douban,GAT,512,12,8,18.472737,0.285331,0.255367,0.434705,0.511628,0.737030,0.344600
52,douban,GAT,512,12,9,15.024098,0.295170,0.282648,0.459750,0.542487,0.757603,0.372800
58,douban,GAT,512,12,10,25.249483,0.298748,0.252236,0.440519,0.531753,0.730769,0.346239
5,douban,GATE,512,12,1,15.044465,0.286225,0.272361,0.451699,0.533542,0.739714,0.361606
11,douban,GATE,512,12,2,19.125875,0.295170,0.282200,0.453041,0.547406,0.756708,0.369146
17,douban,GATE,512,12,3,18.113431,0.297853,0.267442,0.445438,0.525492,0.739267,0.354645
23,douban,GATE,512,12,4,11.918857,0.272809,0.275492,0.444544,0.531753,0.736136,0.361400
29,douban,GATE,512,12,5,27.061176,0.305903,0.266995,0.444544,0.535778,0.753131,0.356608
35,douban,GATE,512,12,6,23.417987,0.282648,0.264758,0.440072,0.534884,0.743739,0.355064
41,douban,GATE,512,12,7,22.460247,0.302326,0.272361,0.445438,0.535778,0.757156,0.362186
47,douban,GATE,512,12,8,19.534582,0.271914,0.256261,0.438730,0.525939,0.736583,0.348181
53,douban,GATE,512,12,9,15.825712,0.270125,0.261181,0.437388,0.525939,0.740161,0.351410
59,douban,GATE,512,12,10,26.744609,0.298748,0.261628,0.449016,0.534436,0.741055,0.352689
3,douban,GCN,512,12,1,7.738441,0.218247,0.258050,0.441413,0.526386,0.737030,0.349193
9,douban,GCN,512,12,2,7.084155,0.222719,0.255814,0.437388,0.527281,0.732558,0.344866
15,douban,GCN,512,12,3,6.324272,0.213775,0.255814,0.432916,0.514758,0.732558,0.345148
21,douban,GCN,512,12,4,6.314312,0.203936,0.262522,0.446333,0.532200,0.751789,0.352994
27,douban,GCN,512,12,5,4.551245,0.216458,0.268336,0.450358,0.537567,0.749553,0.359338
33,douban,GCN,512,12,6,6.606100,0.214669,0.263864,0.436494,0.518336,0.737478,0.349949
39,douban,GCN,512,12,7,4.708019,0.211091,0.270572,0.451252,0.538909,0.746869,0.360022
45,douban,GCN,512,12,8,8.155259,0.214669,0.255367,0.439177,0.534884,0.749553,0.348252
51,douban,GCN,512,12,9,4.661871,0.206619,0.267442,0.445438,0.533542,0.745081,0.358008
57,douban,GCN,512,12,10,5.789369,0.215564,0.254025,0.444097,0.532648,0.742844,0.348650
0,douban,GCNRes,512,12,1,17.835657,0.280859,0.266547,0.453936,0.540250,0.740608,0.359859
6,douban,GCNRes,512,12,2,11.550587,0.277281,0.275939,0.460644,0.555903,0.759839,0.369370
12,douban,GCNRes,512,12,3,14.722129,0.281753,0.266100,0.463327,0.550089,0.754472,0.363960
18,douban,GCNRes,512,12,4,20.760976,0.289803,0.268784,0.451252,0.525492,0.733900,0.359426
24,douban,GCNRes,512,12,5,14.697889,0.284436,0.267442,0.461091,0.552326,0.754919,0.363890
30,douban,GCNRes,512,12,6,11.194082,0.279964,0.273703,0.466458,0.556351,0.759839,0.368644
36,douban,GCNRes,512,12,7,18.301730,0.285331,0.265206,0.451699,0.534437,0.739714,0.357444
42,douban,GCNRes,512,12,8,11.901647,0.276386,0.275492,0.470930,0.559481,0.763417,0.372032
48,douban,GCNRes,512,12,9,13.871067,0.278175,0.268784,0.460197,0.556798,0.757156,0.365026
54,douban,GCNRes,512,12,10,12.578912,0.279964,0.271914,0.466011,0.555903,0.761628,0.369194
1,douban,GIN,512,12,1,26.788133,0.424866,0.344365,0.515653,0.597048,0.790250,0.430316
7,douban,GIN,512,12,2,18.372278,0.404293,0.328712,0.508945,0.579159,0.764311,0.416808
13,douban,GIN,512,12,3,28.766182,0.435599,0.348837,0.524150,0.601073,0.793828,0.435593
19,douban,GIN,512,12,4,27.773114,0.441860,0.349732,0.516547,0.603309,0.796064,0.435120
25,douban,GIN,512,12,5,34.602623,0.443649,0.351521,0.523703,0.605546,0.807692,0.438736
31,douban,GIN,512,12,6,29.592589,0.432916,0.339445,0.518784,0.599732,0.797406,0.430497
37,douban,GIN,512,12,7,34.605099,0.440966,0.350626,0.526386,0.608676,0.804114,0.438265
43,douban,GIN,512,12,8,16.029276,0.407871,0.335868,0.512970,0.583632,0.770572,0.423927
49,douban,GIN,512,12,9,21.124374,0.418605,0.341234,0.518784,0.594812,0.785778,0.427901
55,douban,GIN,512,12,10,23.688787,0.440966,0.341234,0.513864,0.599284,0.783095,0.428546
2,douban,GINE,512,12,1,37.258432,0.286225,0.227191,0.364937,0.447674,0.644454,0.300264
8,douban,GINE,512,12,2,30.005888,0.283542,0.211091,0.345259,0.421735,0.615832,0.283061
14,douban,GINE,512,12,3,45.590219,0.297853,0.232558,0.374329,0.454830,0.658318,0.307377
20,douban,GINE,512,12,4,57.941615,0.307692,0.241950,0.389982,0.471825,0.674419,0.320083
26,douban,GINE,512,12,5,57.148190,0.311270,0.238819,0.394007,0.471377,0.669052,0.317936
32,douban,GINE,512,12,6,33.812320,0.288014,0.221377,0.356887,0.435599,0.629696,0.292801
38,douban,GINE,512,12,7,42.504698,0.299642,0.229875,0.373435,0.448122,0.646243,0.303539
44,douban,GINE,512,12,8,37.214391,0.286225,0.223614,0.365832,0.441413,0.640877,0.297907
50,douban,GINE,512,12,9,37.232317,0.298748,0.227191,0.372540,0.447227,0.640429,0.301496
56,douban,GINE,512,12,10,46.774007,0.300537,0.237925,0.378354,0.457961,0.661449,0.312284

In [23]:
df_text = df_summary.map(lambda x: f"{x}".replace(".", ","))
df_text

,Dataset,Encoder,Dimension,Layer,Seed,Runtime,Accuracy,Hits@1,Hits@5,Hits@10,Hits@50,MRR
4,douban,GAT,512,12,1,"14,210501609952189","0,2817531305903399","0,273255817592144","0,44991055130958557","0,5348837077617645","0,743291586637497","0,3622090443968773"
10,douban,GAT,512,12,2,"22,08143561705947","0,28711985688729874","0,253577820956707","0,43828265368938446","0,5357781648635864","0,7482110857963562","0,34788139164447784"
16,douban,GAT,512,12,3,"21,201697165030055","0,3094812164579606","0,2652057185769081","0,43649373948574066","0,5299642235040665","0,743291586637497","0,35446450859308243"
22,douban,GAT,512,12,4,"17,55601530300919","0,29695885509839","0,28264757990837097","0,4543828219175339","0,5384615510702133","0,7459749579429626","0,3706424832344055"
28,douban,GAT,512,12,5,"20,537851719069295","0,29695885509839","0,25402504950761795","0,4449910670518875","0,5286225527524948","0,7406082153320312","0,34725096076726913"
34,douban,GAT,512,12,6,"21,53945426410064","0,2924865831842576","0,26475849747657776","0,4472271800041199","0,5277280956506729","0,7455277144908905","0,35622725635766983"
40,douban,GAT,512,12,7,"26,089180122013204","0,29874776386404295","0,2652057185769081","0,4432021379470825","0,5317531228065491","0,7477638721466064","0,3561154678463936"
46,douban,GAT,512,12,8,"18,472737182979472","0,2853309481216458","0,2553667277097702","0,43470484018325806","0,5116278976202011","0,737030416727066","0,3445996344089508"
52,douban,GAT,512,12,9,"15,024098486057483","0,295169946332737","0,28264757990837097","0,4597495496273041","0,5424865782260895","0,757602870464325","0,372799851000309"
58,douban,GAT,512,12,10,"25,249482684070244","0,29874776386404295","0,25223612785339355","0,440518781542778","0,5317531377077103","0,7307692468166351","0,3462388962507248"
5,douban,GATE,512,12,1,"15,04446490004193","0,28622540250447226","0,2723613604903221","0,45169946551322937","0,5335420221090317","0,7397137880325317","0,36160634458065033"
11,douban,GATE,512,12,2,"19,12587456603069","0,295169946332737","0,2822003588080406","0,4530411660671234","0,5474060773849487","0,756708413362503","0,36914557963609695"
17,douban,GATE,512,12,3,"18,113431331003085","0,29785330948121647","0,26744186133146286","0,44543829560279846","0,5254919528961182","0,7392665445804596","0,35464541614055634"
23,douban,GATE,512,12,4,"11,918857265030965","0,27280858676207514","0,27549195289611816","0,44454382359981537","0,5317531228065491","0,7361359596252441","0,3614000752568245"
29,douban,GATE,512,12,5,"27,061176065006293","0,30590339892665475","0,2669946327805519","0,44454383850097656","0,5357781797647476","0,7531305849552155","0,3566078394651413"
35,douban,GATE,512,12,6,"23,417986745014787","0,2826475849731664","0,26475849747657776","0,44007153809070587","0,5348837375640869","0,7437388300895691","0,3550638258457184"
41,douban,GATE,512,12,7,"22,460247201961465","0,3023255813953488","0,2723613679409027","0,44543828070163727","0,5357781797647476","0,7571556568145752","0,3621862083673477"
47,douban,GATE,512,12,8,"19,534582399995998","0,27191413237924866","0,2562611773610115","0,4387298673391342","0,5259391814470291","0,7365831732749939","0,3481805622577667"
53,douban,GATE,512,12,9,"15,82571170607116","0,2701252236135957","0,26118067651987076","0,43738821148872375","0,5259391963481903","0,7401610016822815","0,3514101281762123"
59,douban,GATE,512,12,10,"26,744608992012218","0,29874776386404295","0,2616279050707817","0,44901609420776367","0,5344364941120148","0,7410554587841034","0,3526886850595474"
3,douban,GCN,512,12,1,"7,7384405840421095","0,2182468694096601","0,2580500841140747","0,4414132535457611","0,5263863950967789","0,737030416727066","0,3491926044225693"
9,douban,GCN,512,12,2,"7,084154918091372","0,22271914132379247","0,25581395626068115","0,43738819658756256","0,5272808521986008","0,7325581312179565","0,34486569464206696"
15,douban,GCN,512,12,3,"6,324271605000831","0,21377459749552774","0,25581395626068115","0,43291591107845306","0,5147584974765778","0,7325581312179565","0,3451477587223053"
21,douban,GCN,512,12,4,"6,31431209098082","0,2039355992844365","0,262522354722023","0,446332722902298","0,53220035135746","0,7517889142036438","0,35299427807331085"
27,douban,GCN,512,12,5,"4,55124503292609","0,21645796064400716","0,26833631098270416","0,4503577649593353","0,5375670790672302","0,7495527863502502","0,35933761298656464"
33,douban,GCN,512,12,6,"6,606100118020549","0,2146690518783542","0,26386404037475586","0,43649373948574066","0,5183363258838654","0,7374776303768158","0,34994925558567047"
39,douban,GCN,512,12,7,"4,708019087091088","0,2110912343470483","0,2705724462866783","0,4512522369623184","0,5389087796211243","0,7468694150447845","0,36002175509929657"
45,douban,GCN,512,12,8,"8,155258586979471","0,2146690518783542","0,2553667277097702","0,43917709589004517","0,5348837226629257","0,7495527863502502","0,34825216233730316"
51,douban,GCN,512,12,9,"4,661870735930279","0,20661896243291591","0,26744185388088226","0,44543829560279846","0,5335420519113541","0,7450805008411407","0,35800836980342865"
57,douban,GCN,512,12,10,"5,789369398029521","0,21556350626118068","0,25402503460645676","0,4440965950489044","0,5326475948095322","0,7428443431854248","0,3486499786376953"
0,douban,GCNRes,512,12,1,"17,835656721959822","0,2808586762075134","0,26654740422964096","0,4539355933666229","0,5402504354715347","0,7406082451343536","0,3598587214946747"
6,douban,GCNRes,512,12,2,"11,550586584955454","0,2772808586762075","0,2759391814470291","0,460644006729126","0,5559033900499344","0,7598389983177185","0,3693704605102539"
12,douban,GCNRes,512,12,3,"14,722129364963621","0,2817531305903399","0,2661001831293106","0,4633273631334305","0,5500894337892532","0,7544722855091095","0,36396025121212006"
18,douban,GCNRes,512,12,4,"20,760976258083247","0,2898032200357782","0,2687835395336151","0,4512522369623184","0,5254919677972794","0,7338998019695282","0,359425887465477"
24,douban,GCNRes,512,12,5,"14,697888863040134","0,2844364937388193","0,26744186133146286","0,4610912501811981","0,552325576543808","0,7549194991588593","0,36389027535915375"
30,douban,GCNRes,512,12,6,"11,194082205998711","0,27996422182468694","0,27370304614305496","0,46645796298980713","0,5563506335020065","0,7598389983177185","0,3686443120241165"
36,douban,GCNRes,512,12,7,"18,301729988888837","0,2853309481216458","0,2652057260274887","0,45169946551322937","0,534436509013176","0,7397137880325317","0,35744380950927734"
42,douban,GCNRes,512,12,8,"11,901647344930097","0,276386404293381","0,27549195289611816","0,47093023359775543","0,559481218457222","0,7634167969226837","0,3720323294401169"
48,douban,GCNRes,512,12,9,"13,871067223022692","0,278175313059034","0,2687835469841957","0,460196778178215","0,5567978620529175","0,7571556568145752","0,36502619087696075"
54,douban,GCNRes,512,12,10,"12,578911597956903","0,27996422182468694","0,27191413193941116","0,4660107344388962","0,5559034049510956","0,7616278827190399","0,3691936731338501"
1,douban,GIN,512,12,1,"26,788133049965836","0,42486583184257604","0,3443649411201477","0,5156529396772385","0,5970482975244522","0,7902504205703735","0,43031586706638336"
7,douban,GIN,512,12,2,"18,372277676011436","0,40429338103756707","0,32871198654174805","0,5089445412158966","0,5791592299938202","0,764311283826828","0,41680824756622314"
13,douban,GIN,512,12,3,"28,766182468039915","0,43559928443649376","0,348837211728096","0,5241502821445465","0,6010733395814896","0,7938282787799835","0,43559272587299347"
19,douban,GIN,512,12,4,"27,773113737930544","0,4418604651162791","0,3497316688299179","0,5165474116802216","0,6033094674348831","0,7960644066333771","0,4351201355457306"
25,douban,GIN,512,12,5,"34,602622841950506","0,44364937388193204","0,3515205681324005","0,5237030386924744","0,6055456250905991","0,8076923191547394","0,4387364089488983"
31,douban,GIN,512,12,6,"29,592588801984675","0,4329159212880143","0,33944544196128845","0,5187835395336151","0,5997316539287567","0,7974061071872711","0,43049682676792145"
37,douban,GIN,512,12,7,"34,605099078966305","0,4409660107334526","0,3506261110305786","0,5263864099979401","0,6086762249469757","0,8041144907474518","0,43826547265052795"
43,douban,GIN,512,12,8,"16,02927592000924","0,407871198568873","0,33586761355400085","0,512969583272934","0,5836315006017685","0,7705724537372589","0,42392732203006744"
49,douban,GIN,512,12,9,"21,124374459963292","0,4186046511627907","0,34123434126377106","0,5187835395336151","0,5948121696710587","0,7857781946659088","0,42790140211582184"
55,douban,GIN,512,12,10,"23,68878742097877","0,4409660107334526","0,34123434126377106","0,5138640403747559","0,5992844253778458","0,7830948233604431","0,42854610085487366"
2,douban,GINE,512,12,1,"37,25843173393514","0,28622540250447226","0,22719141095876694","0,3649373948574066","0,447674423456192","0,6444543749094009","0,3002644404768944"
8,douban,GINE,512,12,2,"30,005887640989386","0,28354203935599287","0,21109124273061752","0,3452593982219696","0,4217352271080017","0,6158318370580673","0,28306078910827637"
14,douban,GINE,512,12,3,"45,59021860791836","0,29785330948121647","0,23255814611911774","0,3743291646242142","0,454830065369606","0,658318430185318","0,30737684667110443"
20,douban,GINE,512,12,4,"57,94161463400815","0,3076923076923077","0,2419499158859253","0,38998210430145264","0,47182467579841614","0,6744185984134674","0,32008273899555206"
26,douban,GINE,512,12,5,"57,1481896310579","0,3112701252236136","0,23881931602954865","0,3940071612596512","0,4713774621486664","0,6690518856048584","0,317935511469841"
32,douban,GINE,512,12,6,"33,81232045905199","0,2880143112701252","0,22137745469808578","0,3568872958421707","0,43559928238391876","0,6296958923339844","0,2928014397621155"
38,douban,GINE,512,12,7,"42,50469804299064","0,29964221824686943","0,22987478226423264","0,3734347075223923","0,4481216371059418","0,6462433040142059","0,303539015352726"
44,douban,GINE,512,12,8,"37,214391403016634","0,28622540250447226","0,22361359000205994","0,3658318519592285","0,4414132386445999","0,6408765614032745","0,2979065775871277"
50,douban,GINE,512,12,9,"37,232316624955274","0,29874776386404295","0,22719141095876694","0,3725402504205704","0,4472271800041199","0,6404293477535248","0,3014957755804062"
56,douban,GINE,512,12,10,"46,77400680095889","0,3005366726296959","0,23792486637830734","0,3783542066812515","0,45796066522598267","0,6614490151405334","0,31228435784578323"

In [24]:
print(NUM_HIDDEN_LAYERS)
print(HIDDEN_DIM)
print(output_feature_size)

12
[1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024]
512