In [1]:
# Torch version
!python -c "import torch; print(torch.__version__)"

# Cuda version
!python -c "import torch; print(torch.version.cuda)"

2.6.0+cu124
12.4

In [2]:
# Uninstall
# !pip uninstall torch-scatter torch-sparse torch-cluster torch-spline-conv pyg-lib -y

In [3]:
# Update Torch
# !pip install torch==2.6.0 torchvision==0.21.0 torchaudio==2.6.0 --index-url https://download.pytorch.org/whl/cu124

In [4]:
# Install PyG (automatic)
# !pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-{torch.__version__}.html
# !pip install torch_geometric

In [5]:
# Verify instalation
import torch
import torch_geometric
import torch_scatter

print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.is_available())
print(torch_scatter.__version__)
print(torch_geometric.__version__)

2.6.0+cu124
12.4
True
2.1.2+pt26cu124
2.7.0

In [6]:
from model_PyG import *
from utils import *

In [7]:
import json
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
import pandas as pd
import time
import torch
import torch.nn.functional as F
import torch_geometric.transforms as T

from mpl_toolkits.mplot3d import Axes3D
from sklearn.decomposition import PCA
from sklearn.neighbors import NearestNeighbors
from torch_geometric.data import InMemoryDataset, Data
from torch_geometric.nn.conv.gcn_conv import gcn_norm
from torch_geometric.transforms import Compose
from torch_geometric.utils import dense_to_sparse, negative_sampling
from torch.nn.functional import binary_cross_entropy_with_logits
from torch.optim import Adam

In [8]:
import torch_geometric
print(torch_geometric.__version__)

np.random.seed(0)
torch.manual_seed(0)
torch.cuda.manual_seed(0)
torch.cuda.manual_seed_all(0)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

2.7.0

### Parameters

In [9]:
file = open("exp.json")
experiment = json.load(file)
exp = experiment["exp"] # Change to static, e.g. "exp1"

file = open("experiments/output/{}/parameters.json".format(exp))
params = json.load(file)

print("Exp:\t\t", exp)

raw_data_file = params["raw_data_file"]
print("Raw data:\t", raw_data_file)

methods = params["methods"]
print("Methods:\t", methods)

apply_transformation = params["apply_transformation"]
print("Has transformation:", apply_transformation)

dimension = params["dimension"]
print("Dimension:\t", dimension)

groups_id = params["groups_id"]
print("Groups id:\t", groups_id)

subgroups_id = params["subgroups_id"]
print("Subgroups id:\t", subgroups_id)

cuda = params["cuda"]
print("Cuda:\t", cuda)

epochs = params["epochs"]
print("Epochs:\t", epochs)

lr = params["lr"]
print("Lr:\t", lr)

Exp:		 exp100
Raw data:	 ACM_DBLP
Methods:	 ['t-gae']
Has transformation: False
Dimension:	 16
Groups id:	 ['ACM_DBLP']
Subgroups id:	 {'ACM_DBLP': ['1', '2']}
Cuda:	 1
Epochs:	 500
Lr:	 0.0001

### Setup

In [10]:
# Parameters models

dataset = exp
encoders = ["ORI", "GIN", "GINE"] # ["GIN", "GINE"] # ["GIN", "GINE"] # ["GIN", "GINE"] # Change
device = torch.device(f"cuda:{cuda}" if torch.cuda.is_available() else "cpu")
# device = torch.device("cpu")

NUM_HIDDEN_LAYERS = 12
HIDDEN_DIM = [1024] * NUM_HIDDEN_LAYERS + [1024]
output_feature_size = dimension # 128
# lr = 0.001
# epochs = 100

In [11]:
# Create datasets (groups and subgroups)

list_train_set = []

for group_id in groups_id:
	train_set = []
	for subgroup_id in subgroups_id[group_id]:
		train_set.append("{}_{}".format(group_id, subgroup_id))
	list_train_set.append(train_set)
list_train_set

[['ACM_DBLP_1', 'ACM_DBLP_2']]

### Create Data (PyG)

In [12]:
# Only for GIN
""" transform = Compose([
	# T.NormalizeFeatures(),
	T.ToUndirected(reduce="mean"),
	T.AddSelfLoops(fill_value=1.0),
	T.ToDevice(device)
]) """

# For GIN and GINE
transform = T.Compose([
	# T.NormalizeFeatures(),
	T.ToUndirected(reduce="mean"),
	# T.AddSelfLoops(attr="edge_attr", fill_value="mean"),
	# T.AddLaplacianEigenvectorPE(k=3, attr_name=None, is_undirected=True),
	# T.AddRandomWalkPE(walk_length=8, attr_name=None),
	T.ToDevice(device)
])

In [13]:
print("Loading training datasets")
has_edge_attributes = False
with_mean1 = True
with_mean2 = True

list_train_loader = []

if raw_data_file == "ACM_DBLP":
	group_id = groups_id[0]
	
	# Read dataset
	b = np.load("data/ACM-DBLP.npz")

	# Node matching
	test_pairs = b["test_pairs"].astype(np.int32)
	pos_pairs = b["pos_pairs"].astype(np.int32)
	df_node_alignment_truth = pd.DataFrame(np.concatenate((test_pairs, pos_pairs), axis=0))
	df_node_alignment_truth

	# Data preparation
	subgroup_id = 1
	edge_index1 = torch.tensor(b[f"edge_index{subgroup_id}"], dtype=torch.long)
	x1 = torch.tensor(b[f"x{subgroup_id}"], dtype=torch.float)

	subgroup_id = 2
	edge_index2 = torch.tensor(b[f"edge_index{subgroup_id}"], dtype=torch.long)
	x2 = torch.tensor(b[f"x{subgroup_id}"], dtype=torch.float)

elif raw_data_file == "Douban Online_Offline":
	group_id = groups_id[0]
	
	# Read dataset
	a1, f1, a2, f2, test_pairs = load_douban()

	# Node matching
	test_pairs = torch.tensor(np.array(test_pairs, dtype=int)) - 1
	test_pairs = test_pairs.numpy()
	df_node_alignment_truth = pd.DataFrame(test_pairs.T)
	df_node_alignment_truth

	# Create data
	edge_index1, _ = dense_to_sparse(torch.from_numpy(a1.toarray()))
	x1 = torch.from_numpy(f1.toarray()).float()

	edge_index2, _= dense_to_sparse(torch.from_numpy(a2.toarray()))
	x2 = torch.from_numpy(f2.toarray()).float()

	with_mean1 = False
	with_mean2 = False

elif raw_data_file == "Cora1-Cora2":
	group_id = groups_id[0]
		
	# Read dataset
	loader = load_npz("data/cora.npz")
	data = loader["adj_matrix"]
	samples = data.shape[0]
	features = data.shape[1]
	values = data.data
	coo_data = data.tocoo()
	# indices = torch.LongTensor([coo_data.row, coo_data.col])
	indices = np.array([coo_data.row, coo_data.col])

	# Node matching
	N = 2708
	test_pairs = [[i, i] for i in range(N)]
	df_node_alignment_truth = pd.DataFrame(test_pairs)
	df_node_alignment_truth

	# Create data
	node_features = loader["node_attr"]
	node_features = node_features.toarray()

	edge_index1 = torch.tensor(indices, dtype=torch.long)
	x1 = torch.tensor(node_features, dtype=torch.float)

	edge_index2 = torch.tensor(indices, dtype=torch.long)
	x2 = torch.tensor(node_features, dtype=torch.float)

	with_mean1 = False
	with_mean2 = True

elif raw_data_file == "flickr-lastfm":
	# https://github.com/yq-leo/PlanetAlign/blob/main/PlanetAlign/datasets/flickr_lastfm.py
	data = torch.load("data/flickr-lastfm.pt")
	edges = data["edges"]
	node_features = data["node_attributes"]
	edges_attributes = data["edge_attributes"]
	
	# Node matching
	test_pairs = data["anchor_links"].cpu().numpy()
	df_node_alignment_truth = pd.DataFrame(test_pairs)
	df_node_alignment_truth

	# Create data
	edge_index1 = edges[0]
	x1 = torch.tensor(node_features[0].cpu().numpy(), dtype=torch.float)
	edge_attr1 = torch.tensor(edges_attributes[0].cpu().numpy(), dtype=torch.float)

	edge_index2 = edges[1]
	x2 = torch.tensor(node_features[1].cpu().numpy(), dtype=torch.float)
	edge_attr2 = torch.tensor(edges_attributes[1].cpu().numpy(), dtype=torch.float)

	has_edge_attributes = True
	with_mean1 = False
	with_mean2 = False

elif raw_data_file == "douban":
	# https://github.com/yq-leo/PlanetAlign/blob/main/PlanetAlign/datasets/flickr_lastfm.py
	data = torch.load("data/douban.pt")
	edges = data["edges"]
	node_features = data["node_attributes"]
	edges_attributes = data["edge_attributes"]
	
	# Node matching
	test_pairs = data["anchor_links"].cpu().numpy()
	df_node_alignment_truth = pd.DataFrame(test_pairs)
	df_node_alignment_truth

	# Create data
	edge_index1 = edges[0]
	x1 = torch.tensor(node_features[0].cpu().numpy(), dtype=torch.float)
	edge_attr1 = torch.tensor(edges_attributes[0].cpu().numpy(), dtype=torch.float)

	edge_index2 = edges[1]
	x2 = torch.tensor(node_features[1].cpu().numpy(), dtype=torch.float)
	edge_attr2 = torch.tensor(edges_attributes[1].cpu().numpy(), dtype=torch.float)

	has_edge_attributes = True
	with_mean1 = False
	with_mean2 = False

elif raw_data_file == "flickr-myspace":
	# https://github.com/yq-leo/PlanetAlign/blob/main/PlanetAlign/datasets/flickr_lastfm.py
	data = torch.load("data/flickr-myspace.pt")
	edges = data["edges"]
	node_features = data["node_attributes"]
	edges_attributes = data["edge_attributes"]
	
	# Node matching
	test_pairs = data["anchor_links"].cpu().numpy()
	df_node_alignment_truth = pd.DataFrame(test_pairs)
	df_node_alignment_truth

	# Create data
	edge_index1 = edges[0]
	x1 = torch.tensor(node_features[0].cpu().numpy(), dtype=torch.float)
	edge_attr1 = torch.tensor(edges_attributes[0].cpu().numpy(), dtype=torch.float)

	edge_index2 = edges[1]
	x2 = torch.tensor(node_features[1].cpu().numpy(), dtype=torch.float)
	edge_attr2 = torch.tensor(edges_attributes[1].cpu().numpy(), dtype=torch.float)

	has_edge_attributes = True
	with_mean1 = False
	with_mean2 = False

elif raw_data_file == "ACM-DBLP":
	# https://github.com/yq-leo/PlanetAlign/blob/main/PlanetAlign/datasets/flickr_lastfm.py
	data = torch.load("data/ACM-DBLP.pt")
	edges = data["edges"]
	node_features = data["node_attributes"]
	# edges_attributes = data["edge_attributes"]
	
	# Node matching
	test_pairs = data["anchor_links"].cpu().numpy()
	df_node_alignment_truth = pd.DataFrame(test_pairs)
	df_node_alignment_truth

	# Create data
	edge_index1 = edges[0]
	x1 = torch.tensor(node_features[0].cpu().numpy(), dtype=torch.float)
	# edge_attr1 = torch.tensor(edges_attributes[0].cpu().numpy(), dtype=torch.float)

	edge_index2 = edges[1]
	x2 = torch.tensor(node_features[1].cpu().numpy(), dtype=torch.float)
	# edge_attr2 = torch.tensor(edges_attributes[1].cpu().numpy(), dtype=torch.float)

	has_edge_attributes = False
	with_mean1 = True
	with_mean2 = True
	
# Create data
train_loader = {}

# Include edge_attr
subgroup_id = 1
data1 = Data(x=x1, edge_index=edge_index1)
if has_edge_attributes:
    data1.edge_attr = edge_attr1
else:
	data1 = add_edge_attributes(data1)
print(subgroup_id, data1)
info_data(data1, include_vectors=True)

subgroup_id = 2
data2 = Data(x=x2, edge_index=edge_index2)
if has_edge_attributes:
    data2.edge_attr = edge_attr2
else:
	data2 = add_edge_attributes(data2)
print(subgroup_id, data2)
info_data(data2, include_vectors=True)

# Normalize
normalize_node_edge_features(data1, data2, with_mean1=with_mean1, with_mean2=with_mean2) # Important

# Apply transform
subgroup_id = 1
data1 = transform(data1)
print(subgroup_id, data1)
# info(data1)

subgroup_id = 2
data2 = transform(data2)
print(subgroup_id, data2)
# info(data2)

# Include edge_weight
subgroup_id = 1
edge_index_norm1, edge_weight_norm1 = gcn_norm(
	data1.edge_index, num_nodes=data1.num_nodes, add_self_loops=False
)
data1.edge_index = edge_index_norm1
data1.edge_weight = edge_weight_norm1
train_loader[f"{group_id}_{subgroup_id}"] = data1
print(1, data1)

subgroup_id = 2
edge_index_norm2, edge_weight_norm2 = gcn_norm(
	data2.edge_index, num_nodes=data2.num_nodes, add_self_loops=False
)
data2.edge_index = edge_index_norm2
data2.edge_weight = edge_weight_norm2
train_loader[f"{group_id}_{subgroup_id}"] = data2
print(2, data2)

info_data(data1, include_vectors=True)
info_data(data2, include_vectors=True)

list_train_loader.append(train_loader)

Loading training datasets
1 Data(x=[9872, 17], edge_index=[2, 79122], edge_attr=[79122, 4])
Validate:	 True
Num. nodes:	 9872
Num. edges:	 79122
Num. features:	 17
Has isolated:	 False
Has loops:	 False
Is directed:	 False
Is undirected:	 True
tensor([[   0,    0,    0,  ..., 9870, 9870, 9871],
        [   1,    2,    3,  ..., 1586, 2482, 4454]])
tensor([[61., 42., 16.,  ..., 14.,  1., 22.],
        [54., 18., 12.,  ..., 11.,  0., 16.],
        [54., 61.,  9.,  ..., 10.,  0., 39.],
        ...,
        [ 0.,  0.,  0.,  ...,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  ...,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  ...,  0.,  0.,  1.]])
tensor([[5.0000e+00, 1.3661e-02, 1.9170e+00, 9.2901e-01],
        [3.2000e+01, 1.0667e-01, 1.0993e+01, 9.5597e-01],
        [1.4000e+01, 4.4304e-02, 4.1508e+00, 8.7719e-01],
        ...,
        [3.0000e+00, 2.1429e-01, 1.1592e+00, 8.1650e-01],
        [3.0000e+00, 2.7273e-01, 1.1148e+00, 1.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 4.0825e-01]])
2 Data(x=[9916, 17], edge_index=[2, 89616], edge_attr=[89616, 4])
Validate:	 True
Num. nodes:	 9916
Num. edges:	 89616
Num. features:	 17
Has isolated:	 False
Has loops:	 False
Is directed:	 False
Is undirected:	 True
tensor([[   0,    0,    0,  ..., 9915, 9915, 9915],
        [ 450, 4031, 4447,  ..., 2565, 3529, 5843]])
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 4., 1.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 1., 0., 0.]])
tensor([[3.0000, 0.3000, 1.4871, 0.9045],
        [4.0000, 0.5000, 2.0085, 1.0000],
        [5.0000, 0.4545, 2.7328, 0.6667],
        ...,
        [4.0000, 0.6667, 1.8064, 1.0000],
        [4.0000, 0.1739, 2.1043, 0.5774],
        [4.0000, 0.5000, 1.9139, 0.8944]])
1 Data(x=[9872, 17], edge_index=[2, 79122], edge_attr=[79122, 4])
2 Data(x=[9916, 17], edge_index=[2, 89616], edge_attr=[89616, 4])
1 Data(x=[9872, 17], edge_index=[2, 79122], edge_attr=[79122, 4], edge_weight=[79122])
2 Data(x=[9916, 17], edge_index=[2, 89616], edge_attr=[89616, 4], edge_weight=[89616])
Validate:	 True
Num. nodes:	 9872
Num. edges:	 79122
Num. features:	 17
Has isolated:	 False
Has loops:	 False
Is directed:	 False
Is undirected:	 True
tensor([[   0,    0,    0,  ..., 9870, 9870, 9871],
        [   1,    2,    3,  ..., 1586, 2482, 4454]], device='cuda:1')
tensor([[35.9977, 29.8167, 16.9089,  ..., 11.3303,  0.9390, 11.2458],
        [31.8366, 12.6461, 12.6217,  ...,  8.8336, -0.1510,  8.0856],
        [31.8366, 43.4100,  9.4064,  ...,  8.0014, -0.1510, 20.1998],
        ...,
        [-0.2625, -0.2318, -0.2396,  ..., -0.3209, -0.1510, -0.3417],
        [-0.2625, -0.2318, -0.2396,  ...,  0.5113, -0.1510, -0.3417],
        [-0.2625, -0.2318, -0.2396,  ..., -0.3209, -0.1510,  0.1850]],
       device='cuda:1')
tensor([[-0.2277, -1.1920, -0.3072,  0.8449],
        [ 3.7580, -0.8807,  4.2052,  0.9504],
        [ 1.1009, -1.0894,  0.8035,  0.6423],
        ...,
        [-0.5230, -0.5204, -0.6839,  0.4049],
        [-0.5230, -0.3248, -0.7060,  1.1226],
        [-0.9658, -1.2377, -1.2603, -1.1918]], device='cuda:1')
Validate:	 True
Num. nodes:	 9916
Num. edges:	 89616
Num. features:	 17
Has isolated:	 False
Has loops:	 False
Is directed:	 False
Is undirected:	 True
tensor([[   0,    0,    0,  ..., 9915, 9915, 9915],
        [ 450, 4031, 4447,  ..., 2565, 3529, 5843]], device='cuda:1')
tensor([[-0.2625, -0.2318, -0.2396,  ..., -0.3209, -0.1510, -0.3417],
        [-0.2625, -0.2318, -0.2396,  ..., -0.3209, -0.1510, -0.3417],
        [-0.2625, -0.2318, -0.2396,  ..., -0.3209, -0.1510, -0.3417],
        ...,
        [-0.2625, -0.2318, -0.2396,  ..., -0.3209,  4.2091,  0.1850],
        [-0.2625, -0.2318, -0.2396,  ..., -0.3209, -0.1510, -0.3417],
        [-0.2625, -0.2318, -0.2396,  ...,  0.5113, -0.1510, -0.3417]],
       device='cuda:1')
tensor([[-0.5230, -0.2335, -0.5209,  0.7492],
        [-0.3753,  0.4360, -0.2617,  1.1226],
        [-0.2277,  0.2838,  0.0984, -0.1811],
        ...,
        [-0.3753,  0.9939, -0.3621,  1.1226],
        [-0.3753, -0.6556, -0.2141, -0.5305],
        [-0.3753,  0.4360, -0.3087,  0.7097]], device='cuda:1')

### Train

In [14]:
def fit_TGAE_subgraph_(encoder, dataset, no_samples, model, epochs, train_loader, lr, test_pairs=None):
	best_hitAtOne = 0
	best_hitAtFive = 0
	best_hitAtTen = 0
	best_hitAtFifty = 0
	list_loss = []

	optimizer = Adam(model.parameters(), lr=lr,weight_decay=5e-4)
	
	# Initialize early stopping
	patience = 10
	delta = 1e-4 # 1e-4
	warmup = 10
	early_stopping = EarlyStopping(patience=patience, delta=delta, warmup=warmup, verbose=True)

	loop_obj = tqdm(range(1, epochs + 1))
	for epoch in loop_obj:
		loop_obj.set_description(f"Epoch: {epoch}")
		
		# Train
		model.train()
		loss = 0.0
		
		for ts in random.sample(train_set, k=len(train_set)): # shuffle train_set
			data = train_loader[ts]

			# Encoder
			if encoder == "GIN":
				z = model(data.x, data.edge_index)
				# z = F.normalize(z, dim=1)
			elif encoder == "GINE":
				z = model(data.x, data.edge_index, data.edge_attr)

			# Positive edges
			pos_edge_index = data.edge_index
			
			# Negative edges
			# option 1
			neg_edge_index = negative_sampling(
				edge_index=data.edge_index,
				num_nodes=z.size(0),
				num_neg_samples=pos_edge_index.size(1), # Change 2 to other value if needed
				method="sparse"
			)

			# option 2 Negative edges (dynamic)
			""" ratio = neg_ratio_schedule(epoch, epochs)
			num_neg = compute_num_neg_samples(
				edge_index=edge_index,
				num_nodes=z.size(0),
				ratio=ratio
			)
			neg_edge_index = negative_sampling(
				edge_index=edge_index,
				num_nodes=z.size(0),
				num_neg_samples=num_neg,
				method="sparse"
			) """
			
			# Decoder
			# option 1
			pos_logits = (z[pos_edge_index[0]] * z[pos_edge_index[1]]).sum(dim=1)
			neg_logits = (z[neg_edge_index[0]] * z[neg_edge_index[1]]).sum(dim=1)
			
			# option 2
			""" pos_logits = F.cosine_similarity(
				z[pos_edge_index[0]],
				z[pos_edge_index[1]],
				dim=1
			)
			neg_logits = F.cosine_similarity(
				z[neg_edge_index[0]],
				z[neg_edge_index[1]],
				dim=1
			) """

			# Loss
			pos_labels = torch.ones_like(pos_logits)
			neg_labels = torch.zeros_like(neg_logits)

			# option 1
			""" loss_pos = binary_cross_entropy_with_logits(pos_logits, pos_labels)
			loss_neg = binary_cross_entropy_with_logits(neg_logits, neg_labels)
			loss += loss_pos + loss_neg """

			# option 2
			# num_pos = pos_edge_index.size(1)
			# num_neg = neg_edge_index.size(1)
			# pos_weight = torch.tensor([num_neg / num_pos], device=device)
			logits = torch.cat([pos_logits, neg_logits], dim=0)
			labels = torch.cat([pos_labels, neg_labels], dim=0)
			loss_temp = F.binary_cross_entropy_with_logits(logits, labels) #, pos_weight=pos_weight) # with pos_weight
			loss += loss_temp
			
		optimizer.zero_grad()
		loss = loss / no_samples
		loss.backward()
		optimizer.step()

		loop_obj.set_postfix_str(f"Loss: {loss.item():.4f}")
		list_loss.append(loss.item())

		# Check early stopping condition
		early_stopping.check_early_stop(loss.item(), epoch)
		if early_stopping.stop_training:
			print(f"Early stopping at epoch {epoch}")
			break

		# Evaluation (for firts dataset)
		""" model.eval()
		with torch.no_grad():
			keys = list(train_loader.keys())
			data1 = train_loader[keys[0]]
			data2 = train_loader[keys[1]]

			z1 = model(data1.x, data1.edge_index).detach()
			z2 = model(data2.x, data2.edge_index).detach()
			
			# Similarity matrix
			# option 1
			D = torch.cdist(z1, z2, 2)

			# option 2 (GPU problem)
			# D = 1 - F.cosine_similarity(z1.unsqueeze(1), z2.unsqueeze(0), dim=-1)

			# option 3 (Decoder cosine similarity)
			" "" z1n = F.normalize(z1, dim=1)
			z2n = F.normalize(z2, dim=1)
			D = 1 - (z1n @ z2n.T) " ""

			if dataset == "ACM_DBLP":
				test_idx = test_pairs[:, 0].astype(int)
				labels = test_pairs[:, 1].astype(int)
			else:
				test_idx = test_pairs[0, :].astype(int)
				labels = test_pairs[1, :].astype(int)
				
			hitAtOne = 0
			hitAtFive = 0
			hitAtTen = 0
			hitAtFifty = 0
			hitAtHundred = 0
			for i in range(len(test_idx)):
				dist_list = D[test_idx[i]]
				sorted_neighbors = torch.argsort(dist_list).cpu()
				label = labels[i]
				for j in range(100):
					if (sorted_neighbors[j].item() == label):
						if (j == 0):
							hitAtOne += 1
							hitAtFive += 1
							hitAtTen += 1
							hitAtFifty += 1
							hitAtHundred += 1
							break
						elif (j <= 4):
							hitAtFive += 1
							hitAtTen += 1
							hitAtFifty += 1
							hitAtHundred += 1
							break
						elif (j <= 9):
							hitAtTen += 1
							hitAtFifty += 1
							hitAtHundred += 1
							break
						elif (j <= 49):
							hitAtFifty += 1
							hitAtHundred += 1
							break
						elif (j <= 100):
							hitAtHundred += 1
							break
			cur_hitAtOne = hitAtOne / len(test_idx)
			cur_hitAtFive = hitAtFive / len(test_idx)
			cur_hitAtTen = hitAtTen / len(test_idx)
			cur_hitAtFifty = hitAtFifty / len(test_idx)

			if(cur_hitAtOne > best_hitAtOne): best_hitAtOne = cur_hitAtOne
			if (cur_hitAtFive > best_hitAtFive): best_hitAtFive = cur_hitAtFive
			if (cur_hitAtTen > best_hitAtTen): best_hitAtTen = cur_hitAtTen
			if (cur_hitAtFifty > best_hitAtFifty): best_hitAtFifty = cur_hitAtFifty

	print("The best results achieved:")
	print("Hit@1: ", end="")
	print(best_hitAtOne)
	print("Hit@5: ", end="")
	print(best_hitAtFive)
	print("Hit@10: ", end="")
	print(best_hitAtTen)
	print("Hit@50: ", end="")
	print(best_hitAtFifty) """

	# Evaluation (for others dataset)
	dict_node_embeddings = {}
	model.eval()
	with torch.no_grad():
		for ts in train_set:
			data = train_loader[ts]
			if encoder == "GIN":
				z = model(data.x, data.edge_index)
			elif encoder == "GINE":
				z = model(data.x, data.edge_index, data.edge_attr)
			dict_node_embeddings[ts] = z.cpu().numpy()

	del loss, z
	# torch.cuda.synchronize()
	torch.cuda.empty_cache()
	
	return dict_node_embeddings, list_loss

In [15]:
def fit_TGAE_subgraph(model, encoder, exp, group_id, subgroups_id, train_loader, train_set, no_samples, epochs, lr):
	list_loss = []

	optimizer = Adam(model.parameters(), lr=lr, weight_decay=5e-4)
	
	# Initialize early stopping
	patience = 10
	delta = 1e-4
	warmup = 10
	early_stopping = EarlyStopping(patience=patience, delta=delta, warmup=warmup, verbose=True)

	loop_obj = tqdm(range(1, epochs + 1))
	
	# Train mode
	model.train() # Set the model to training mode (enables dropout and BN updates)
	
	for epoch in loop_obj:
		loop_obj.set_description(f"Epoch: {epoch}")
		
		optimizer.zero_grad() # Reset accumulated gradients before backpropagation
		
		loss = torch.tensor(0.0, device=device)
		
		for ts in random.sample(train_set, k=len(train_set)): # shuffle train_set
			data = train_loader[ts]

			# Encoder
			if encoder == "GIN":
				z = model(data.x, data.edge_index)
				# z = F.normalize(z, dim=1)
			elif encoder == "GINE":
				z = model(data.x, data.edge_index, data.edge_attr)
			elif encoder == "ORI":
				z = model(data.x, data.edge_index, data.edge_weight)

			# Positive edges
			pos_edge_index = data.edge_index
			
			# Negative edges
			# option 1
			neg_edge_index = negative_sampling(
				edge_index=data.edge_index,
				num_nodes=z.size(0),
				num_neg_samples=pos_edge_index.size(1), # Change 2 to other value if needed
				method="sparse"
			)

			# option 2 Negative edges (dynamic)
			""" ratio = neg_ratio_schedule(epoch, epochs)
			num_neg = compute_num_neg_samples(
				edge_index=edge_index,
				num_nodes=z.size(0),
				ratio=ratio
			)
			neg_edge_index = negative_sampling(
				edge_index=edge_index,
				num_nodes=z.size(0),
				num_neg_samples=num_neg,
				method="sparse"
			) """
			
			# Decoder
			# option 1
			pos_logits = (z[pos_edge_index[0]] * z[pos_edge_index[1]]).sum(dim=1)
			neg_logits = (z[neg_edge_index[0]] * z[neg_edge_index[1]]).sum(dim=1)
			
			# option 2
			""" pos_logits = F.cosine_similarity(
				z[pos_edge_index[0]],
				z[pos_edge_index[1]],
				dim=1
			)
			neg_logits = F.cosine_similarity(
				z[neg_edge_index[0]],
				z[neg_edge_index[1]],
				dim=1
			) """

			# Loss
			pos_labels = torch.ones_like(pos_logits)
			neg_labels = torch.zeros_like(neg_logits)

			# option 1
			""" loss_pos = binary_cross_entropy_with_logits(pos_logits, pos_labels)
			loss_neg = binary_cross_entropy_with_logits(neg_logits, neg_labels)
			loss += loss_pos + loss_neg """

			# option 2
			# num_pos = pos_edge_index.size(1)
			# num_neg = neg_edge_index.size(1)
			# pos_weight = torch.tensor([num_neg / num_pos], device=device)
			logits = torch.cat([pos_logits, neg_logits], dim=0)
			labels = torch.cat([pos_labels, neg_labels], dim=0)
			loss_temp = F.binary_cross_entropy_with_logits(logits, labels) #, pos_weight=pos_weight) # with pos_weight
			loss += loss_temp
			
		loss = loss / no_samples
		loss.backward() # Compute gradients of the loss w.r.t. model parameters
		optimizer.step() # Update model parameters using computed gradients

		loop_obj.set_postfix_str(f"Loss: {loss.item():.4f}")
		list_loss.append(loss.item())

		# Check early stopping condition
		early_stopping.check_early_stop(loss.item(), epoch)
		if early_stopping.stop_training:
			print(f"Early stopping at epoch {epoch}")
			break
		# torch.cuda.empty_cache()
	# Evaluation (for others dataset)
	list_df_node_embeddings = []

	model.eval() # Set the model to evaluation mode (disables dropout and BN updates)
	with torch.no_grad():
		for subgroup_id in subgroups_id:

			# Get node embeddings
			data = train_loader[f"{group_id}_{subgroup_id}"]
			if encoder == "GIN":
				z = model(data.x, data.edge_index)
			elif encoder == "GINE":
				z = model(data.x, data.edge_index, data.edge_attr)
			elif encoder == "ORI":
				z = model(data.x, data.edge_index, data.edge_weight)
			
			df_node_embeddings = pd.DataFrame(z.cpu().numpy())
			df_node_embeddings["subgroup_id"] = [subgroup_id] * len(df_node_embeddings)
			
			# Get node ids to replace original Id (this is only for MS data)
			""" df_nodes = pd.read_csv(f"experiments/output/{exp}/preprocessing/graphs_data/nodes_{group_id}_{subgroup_id}.csv")
			# idx, id, mz, rt, intensity_mean, intensity_cv
			df_node_embeddings.insert(0, "Id", df_nodes["id"].values) """

			df_node_embeddings.insert(0, "Id", range(len(df_node_embeddings))) # this is only for no MS data
			list_df_node_embeddings.append(df_node_embeddings)

		# Concat node embeddings
		df_node_embeddings_concat = pd.concat(list_df_node_embeddings, ignore_index=True)
		
		# Save node embeddings
		df_node_embeddings_concat.to_csv(f"experiments/output/{exp}/node_embeddings/{encoder}_{group_id}.csv", index=False)
	
	# Save loss
	np.save(f"experiments/output/{exp}/loss/{encoder}_{group_id}.npy", np.array(list_loss))

	del loss, z
	# torch.cuda.synchronize()
	torch.cuda.empty_cache()

In [16]:
encoders

['ORI', 'GIN', 'GINE']

In [17]:
list_train_set

[['ACM_DBLP_1', 'ACM_DBLP_2']]

In [18]:
list_train_loader

[{'ACM_DBLP_1': Data(x=[9872, 17], edge_index=[2, 79122], edge_attr=[79122, 4], edge_weight=[79122]),
  'ACM_DBLP_2': Data(x=[9916, 17], edge_index=[2, 89616], edge_attr=[89616, 4], edge_weight=[89616])}]

In [ ]:
num_exp = 10 # Change

list_exp = []

for n_exp in range(num_exp):
	print(n_exp)
	#---
	# Train
	#---
	for encoder in encoders:
		for i, train_loader in enumerate(list_train_loader):
			np.random.seed(0)
			torch.manual_seed(0)
			torch.cuda.manual_seed(0)
			torch.cuda.manual_seed_all(0)
			torch.backends.cudnn.deterministic = True
			torch.backends.cudnn.benchmark = False

			group_id = groups_id[i]
			subgroup_id = subgroups_id[group_id]

			train_set = list_train_set[i]

			no_samples = len(train_set) # * (1 + 1)  # num datasets * num of samples by dataset 
			input_dim = train_loader[train_set[0]].num_node_features

			if encoder == "GIN":
				model = TGAE_GIN(NUM_HIDDEN_LAYERS, 
							input_dim,
							HIDDEN_DIM,
							output_feature_size).to(device)
			elif encoder == "GINE":
				edge_dim = train_loader[train_set[0]].edge_attr.size(1)

				model = TGAE_GINE(NUM_HIDDEN_LAYERS,
							input_dim,
							HIDDEN_DIM,
							output_feature_size, edge_dim).to(device)
			elif encoder == "ORI":
				model = TGAE_Original(NUM_HIDDEN_LAYERS,
							input_dim,
							HIDDEN_DIM,
							output_feature_size).to(device)

			print("Fitting model")
			print(encoder, dataset, train_set, lr, epochs, input_dim, output_feature_size, no_samples)

			# Calculate elapsed time
			start_time = time.perf_counter()
			
			fit_TGAE_subgraph(model, encoder, dataset, group_id, subgroup_id, train_loader, train_set, no_samples, epochs, lr)

			end_time = time.perf_counter()
			execution_time = end_time - start_time

			list_exp.append([raw_data_file, encoder, execution_time])

	#---
	# Similarity analysis
	#---
	k = 1 # Change
	for encoder in encoders:
		for group_id in groups_id:
			df_node_embeddings_concat = pd.read_csv(f"experiments/output/{exp}/node_embeddings/{encoder}_{group_id}.csv", dtype={"subgroup_id": "string"})
			# Id, 0, 1,	2, ..., subgroup_id

			subgroups_id_ = subgroups_id[group_id]

			# Calculate distance matrix (KNN)
			knn = NearestNeighbors(n_neighbors=k, metric="euclidean")

			df_node_embeddings = df_node_embeddings_concat[df_node_embeddings_concat["subgroup_id"] == subgroups_id_[0]]
			x = df_node_embeddings.iloc[:, 1:-1].values

			df_node_alignment = pd.DataFrame()
			df_node_alignment[f"{group_id}_{subgroups_id_[0]}"] = df_node_embeddings["Id"].values

			for subgroup_id in subgroups_id_[1:]:
				df_node_embeddings = df_node_embeddings_concat[df_node_embeddings_concat["subgroup_id"] == subgroup_id]
				y = df_node_embeddings.iloc[:, 1:-1].values

				knn.fit(y)
				distances, indices = knn.kneighbors(x)
				indices = indices.squeeze() # (N,)

				df_node_alignment[f"{group_id}_{subgroup_id}"] = df_node_embeddings["Id"].values[indices]
				
				""" df_node_alignment[f"distances"] = distances
				avg_distances = df_node_alignment["distances"].mean()
				df_node_alignment = df_node_alignment[df_node_alignment["distances"] <= avg_distances].iloc[:, :-1]
				df_node_alignment """
			
			# Save previus node alignment
			df_node_alignment.to_csv(f"experiments/output/{exp}/filter_raw/node_alignment_{encoder}_{group_id}.csv")
			display(df_node_alignment)

			# Find node alignment for all datasets
			""" df_node_alignment_filter = df_node_alignment[df_node_alignment.nunique(axis=1) == 1]
			list_count_meta.append([encoder, group_id, len(df_node_alignment_filter), len(df_node_alignment)])
			# print(len(df_node_alignment_filter))
			# display(df_node_alignment_filter)
			print(f"{encoder}-{group_id}: {len(df_node_alignment_filter)}")
			
			# Save common node id
			# common_node_id = df_node_alignment_filter.iloc[:, 0].values
			# np.save(f"experiments/output/{exp}/common_nodes/{encoder}_{group_id}.npy", np.array(common_node_id)) """

			# Save common node id as .csv
			df_common_node_id = df_node_alignment.iloc[:, [0, 1]].copy() # df_common_node_id = df_node_alignment_filter.iloc[:, [0, 1]].copy()
			df_common_node_id.sort_values(by=df_common_node_id.columns[0], inplace=True)
			df_common_node_id.to_csv(f"experiments/output/{exp}/common_nodes/{encoder}_{group_id}.csv", index=False, header=False)

	# Intersection and Union
	""" list_common_node_id = []
	for encoder in encoders:
		for group_id in groups_id:
			# Read common node
			common_node_id = np.load(f"experiments/output/{exp}/common_nodes/{encoder}_{group_id}.npy")
			list_common_node_id.append(common_node_id)

		common_node_id_union = list(set.union(*map(set, list_common_node_id)))
		common_node_id_intersection = list(set.intersection(*map(set, list_common_node_id)))

		# Save common node id
		np.save(f"experiments/output/{exp}/common_nodes/{encoder}_union.npy", np.array(common_node_id_union))
		np.save(f"experiments/output/{exp}/common_nodes/{encoder}_intersection.npy", np.array(common_node_id_intersection)) """

	#---
	# Evaluation
	#---
	# list_accuracy = []
	# list_encoder = []

	for j, encoder in enumerate(encoders):
		for group_id in groups_id:
			# Read node alignment
			df_common_node_id = pd.read_csv(f"experiments/output/{exp}/common_nodes/{encoder}_{group_id}.csv", header=None)
			# df_common_node_id[[0, 1]] = np.sort(df_common_node_id[[0, 1]], axis=1)

			# Evaluation
			df_matching = df_common_node_id.merge(df_node_alignment_truth, on=[0, 1], how="inner")

			# Accuracy
			accuracy = len(df_matching) / len(df_node_alignment_truth)
			
			list_exp[len(encoders) * n_exp + j].append(accuracy)
			# list_accuracy.append(accuracy)
			# list_encoder.append(encoder)

	#---
	# Evaluation (based on PlanetAlign)
	#---

	# Get node embeddings
	dict_node_embeddings = {}
	for encoder in encoders:
		list_node_embeddings = []
		for group_id in groups_id:
			df_node_embeddings_concat = pd.read_csv(f"experiments/output/{exp}/node_embeddings/{encoder}_{group_id}.csv", dtype={"subgroup_id": "string"})
			# Id, 0, 1,	2, ..., subgroup_id

			for subgroup_id in subgroups_id[group_id]:
				df_node_embeddings = df_node_embeddings_concat[df_node_embeddings_concat["subgroup_id"] == subgroup_id]
				list_node_embeddings.append(df_node_embeddings)
		dict_node_embeddings[encoder] = list_node_embeddings

	# Evaluation
	# list_metrics = []

	df_node_alignment_truth_ = torch.tensor(df_node_alignment_truth.values)

	for j, encoder in enumerate(encoders):
		list_node_embeddings = dict_node_embeddings[encoder]
		# Id, 0, 1,	2, ..., subgroup_id

		emb1 = list_node_embeddings[0].iloc[:, 1:-1]
		emb2 = list_node_embeddings[1].iloc[:, 1:-1]

		emb1_ = torch.tensor(emb1.values)
		emb2_ = torch.tensor(emb2.values)

		# Similarity matrix
		# Option 1
		# S = pairwise_cosine_similarity(emb1_, emb2_)

		# Option 2
		""" S = cosine_similarity(emb1, emb2)
		S = torch.tensor(S) """

		# Option 3
		S = pairwise_distances(emb1, emb2, metric="euclidean")
		S = torch.tensor(S)
		S = -S # convert distances matrix to similarity matrix
		
		# Option 4
		""" S = torch.cdist(emb1_, emb2_, 2)
		S = -S # convert distances matrix to similarity matrix """

		hits = hits_ks_scores(S, df_node_alignment_truth_, mode="mean")
		mrr = mrr_score(S, df_node_alignment_truth_, mode="mean")
		print(encoder, hits, mrr)

		list_exp[len(encoders) * n_exp + j] += list(hits.values()) + [mrr]

0
Fitting model
ORI exp100 ['ACM_DBLP_1', 'ACM_DBLP_2'] 0.0001 500 17 16 2

Epoch: 115:  23%|██▎       | 114/500 [00:38<02:11,  2.93it/s, Loss: 0.4205]

Stopping early as no improvement has been observed.
Early stopping at epoch 115
Fitting model
GIN exp100 ['ACM_DBLP_1', 'ACM_DBLP_2'] 0.0001 500 17 16 2

Epoch: 109:  22%|██▏       | 108/500 [01:35<05:47,  1.13it/s, Loss: 0.4253]

Stopping early as no improvement has been observed.
Early stopping at epoch 109
Fitting model
GINE exp100 ['ACM_DBLP_1', 'ACM_DBLP_2'] 0.0001 500 17 16 2

Epoch: 199:  40%|███▉      | 198/500 [03:22<05:08,  1.02s/it, Loss: 0.4291]

Stopping early as no improvement has been observed.
Early stopping at epoch 199

      ACM_DBLP_1  ACM_DBLP_2
0              0        6829
1              1         601
2              2        3102
3              3        3584
4              4        3744
...          ...         ...
9867        9867        3057
9868        9868        9011
9869        9869        5642
9870        9870        5284
9871        9871        2962

[9872 rows x 2 columns]

      ACM_DBLP_1  ACM_DBLP_2
0              0        6829
1              1         601
2              2        3102
3              3        3584
4              4        3744
...          ...         ...
9867        9867        3057
9868        9868        9011
9869        9869        3304
9870        9870        7502
9871        9871        1367

[9872 rows x 2 columns]

      ACM_DBLP_1  ACM_DBLP_2
0              0        6829
1              1         601
2              2        3102
3              3        3584
4              4        3744
...          ...         ...
9867        9867        7214
9868        9868        9011
9869        9869        7661
9870        9870        7665
9871        9871        5465

[9872 rows x 2 columns]

ORI {1: 0.5190513730049133, 10: 0.8341501951217651, 30: 0.8932806551456451, 50: 0.916679859161377} 0.6254389882087708
GIN {1: 0.5041897147893906, 10: 0.8092489838600159, 30: 0.8762845993041992, 50: 0.8977074921131134} 0.6072947680950165
GINE {1: 0.5215810239315033, 10: 0.8181818127632141, 30: 0.8755731284618378, 50: 0.8945454657077789} 0.6213705539703369
1
Fitting model
ORI exp100 ['ACM_DBLP_1', 'ACM_DBLP_2'] 0.0001 500 17 16 2

Epoch: 126:  25%|██▌       | 125/500 [00:43<02:09,  2.91it/s, Loss: 0.4233]

Stopping early as no improvement has been observed.
Early stopping at epoch 126
Fitting model
GIN exp100 ['ACM_DBLP_1', 'ACM_DBLP_2'] 0.0001 500 17 16 2

Epoch: 159:  32%|███▏      | 158/500 [02:20<05:05,  1.12it/s, Loss: 0.4185]

Stopping early as no improvement has been observed.
Early stopping at epoch 159
Fitting model
GINE exp100 ['ACM_DBLP_1', 'ACM_DBLP_2'] 0.0001 500 17 16 2

Epoch: 186:  37%|███▋      | 185/500 [03:09<05:22,  1.02s/it, Loss: 0.4320]

Stopping early as no improvement has been observed.
Early stopping at epoch 186

      ACM_DBLP_1  ACM_DBLP_2
0              0        6829
1              1         601
2              2        3102
3              3        3584
4              4        3744
...          ...         ...
9867        9867        3057
9868        9868        9011
9869        9869        5642
9870        9870        5284
9871        9871        2962

[9872 rows x 2 columns]

      ACM_DBLP_1  ACM_DBLP_2
0              0        6829
1              1         601
2              2        3102
3              3        3584
4              4        3744
...          ...         ...
9867        9867        2155
9868        9868        9011
9869        9869        3304
9870        9870        7502
9871        9871        7124

[9872 rows x 2 columns]

      ACM_DBLP_1  ACM_DBLP_2
0              0        6829
1              1         601
2              2        3102
3              3        3584
4              4        3744
...          ...         ...
9867        9867        7214
9868        9868        9011
9869        9869        7661
9870        9870        7665
9871        9871        2368

[9872 rows x 2 columns]

ORI {1: 0.5191304385662079, 10: 0.8324110507965088, 30: 0.8943873345851898, 50: 0.9171541333198547} 0.6251451969146729
GIN {1: 0.49375493824481964, 10: 0.8114624619483948, 30: 0.8760474324226379, 50: 0.9012648165225983} 0.5997831523418427
GINE {1: 0.5226877331733704, 10: 0.8173913061618805, 30: 0.8738340139389038, 50: 0.8928063213825226} 0.6219363212585449
2
Fitting model
ORI exp100 ['ACM_DBLP_1', 'ACM_DBLP_2'] 0.0001 500 17 16 2

Epoch: 113:  22%|██▏       | 112/500 [00:38<02:14,  2.89it/s, Loss: 0.4251]

Stopping early as no improvement has been observed.
Early stopping at epoch 113
Fitting model
GIN exp100 ['ACM_DBLP_1', 'ACM_DBLP_2'] 0.0001 500 17 16 2

Epoch: 157:  31%|███       | 156/500 [02:19<05:06,  1.12it/s, Loss: 0.4183]

Stopping early as no improvement has been observed.
Early stopping at epoch 157
Fitting model
GINE exp100 ['ACM_DBLP_1', 'ACM_DBLP_2'] 0.0001 500 17 16 2

Epoch: 238:  47%|████▋     | 237/500 [04:03<04:29,  1.03s/it, Loss: 0.4253]

Stopping early as no improvement has been observed.
Early stopping at epoch 238

      ACM_DBLP_1  ACM_DBLP_2
0              0        6829
1              1         601
2              2        3102
3              3        3584
4              4        3744
...          ...         ...
9867        9867        3057
9868        9868        9011
9869        9869        3304
9870        9870        5284
9871        9871        2962

[9872 rows x 2 columns]

      ACM_DBLP_1  ACM_DBLP_2
0              0        6829
1              1         601
2              2        3102
3              3        3584
4              4        3744
...          ...         ...
9867        9867        2155
9868        9868        9011
9869        9869        3304
9870        9870        7502
9871        9871        7124

[9872 rows x 2 columns]

      ACM_DBLP_1  ACM_DBLP_2
0              0        6829
1              1         601
2              2        3102
3              3        3584
4              4        3744
...          ...         ...
9867        9867        7214
9868        9868        9011
9869        9869        7661
9870        9870        7665
9871        9871        5465

[9872 rows x 2 columns]

ORI {1: 0.5210276544094086, 10: 0.8313834071159363, 30: 0.8937549293041229, 50: 0.9153359532356262} 0.6263130903244019
GIN {1: 0.49596837162971497, 10: 0.8128063380718231, 30: 0.8772332072257996, 50: 0.9036363661289215} 0.6023340225219727
GINE {1: 0.5236363410949707, 10: 0.8205533623695374, 30: 0.8796047568321228, 50: 0.8993675708770752} 0.6236039996147156
3
Fitting model
ORI exp100 ['ACM_DBLP_1', 'ACM_DBLP_2'] 0.0001 500 17 16 2

Epoch: 133:  26%|██▋       | 132/500 [00:45<02:07,  2.89it/s, Loss: 0.4210]

Stopping early as no improvement has been observed.
Early stopping at epoch 133
Fitting model
GIN exp100 ['ACM_DBLP_1', 'ACM_DBLP_2'] 0.0001 500 17 16 2

Epoch: 136:  27%|██▋       | 135/500 [02:00<05:25,  1.12it/s, Loss: 0.4198]

Stopping early as no improvement has been observed.
Early stopping at epoch 136
Fitting model
GINE exp100 ['ACM_DBLP_1', 'ACM_DBLP_2'] 0.0001 500 17 16 2

Epoch: 186:  37%|███▋      | 185/500 [03:09<05:21,  1.02s/it, Loss: 0.4304]

Stopping early as no improvement has been observed.
Early stopping at epoch 186

      ACM_DBLP_1  ACM_DBLP_2
0              0        6829
1              1         601
2              2        3102
3              3        3584
4              4        3744
...          ...         ...
9867        9867        3057
9868        9868        9011
9869        9869        5642
9870        9870        5284
9871        9871        2962

[9872 rows x 2 columns]

      ACM_DBLP_1  ACM_DBLP_2
0              0        6829
1              1         601
2              2        3102
3              3        3584
4              4        3744
...          ...         ...
9867        9867        1031
9868        9868        9011
9869        9869        3304
9870        9870        7502
9871        9871        1367

[9872 rows x 2 columns]

      ACM_DBLP_1  ACM_DBLP_2
0              0        6829
1              1         601
2              2        3102
3              3        3584
4              4        3744
...          ...         ...
9867        9867        7214
9868        9868        9011
9869        9869        7661
9870        9870        7665
9871        9871        5465

[9872 rows x 2 columns]

ORI {1: 0.5134387314319611, 10: 0.8313043415546417, 30: 0.8936758935451508, 50: 0.9147035479545593} 0.6210787892341614
GIN {1: 0.49992094933986664, 10: 0.8138339817523956, 30: 0.8789723515510559, 50: 0.9028458297252655} 0.6055343151092529
GINE {1: 0.52173912525177, 10: 0.8173913061618805, 30: 0.8741501867771149, 50: 0.8929644227027893} 0.6212469637393951
4
Fitting model
ORI exp100 ['ACM_DBLP_1', 'ACM_DBLP_2'] 0.0001 500 17 16 2

Epoch: 112:  22%|██▏       | 111/500 [00:38<02:14,  2.88it/s, Loss: 0.4220]

Stopping early as no improvement has been observed.
Early stopping at epoch 112
Fitting model
GIN exp100 ['ACM_DBLP_1', 'ACM_DBLP_2'] 0.0001 500 17 16 2

Epoch: 161:  32%|███▏      | 160/500 [02:22<05:02,  1.12it/s, Loss: 0.4229]

Stopping early as no improvement has been observed.
Early stopping at epoch 161
Fitting model
GINE exp100 ['ACM_DBLP_1', 'ACM_DBLP_2'] 0.0001 500 17 16 2

Epoch: 248:  49%|████▉     | 247/500 [04:12<04:18,  1.02s/it, Loss: 0.4258]

Stopping early as no improvement has been observed.
Early stopping at epoch 248

      ACM_DBLP_1  ACM_DBLP_2
0              0        6829
1              1         601
2              2        3102
3              3        3584
4              4        3744
...          ...         ...
9867        9867        3057
9868        9868        9011
9869        9869        5642
9870        9870        5284
9871        9871        2962

[9872 rows x 2 columns]

      ACM_DBLP_1  ACM_DBLP_2
0              0        6829
1              1         601
2              2        3102
3              3        3584
4              4        3744
...          ...         ...
9867        9867        2155
9868        9868        9011
9869        9869        3304
9870        9870        7502
9871        9871        7124

[9872 rows x 2 columns]

      ACM_DBLP_1  ACM_DBLP_2
0              0        6829
1              1         601
2              2        3102
3              3        3584
4              4        3744
...          ...         ...
9867        9867        1522
9868        9868        9011
9869        9869        7661
9870        9870        7665
9871        9871        5465

[9872 rows x 2 columns]

ORI {1: 0.5215019881725311, 10: 0.833675891160965, 30: 0.893517792224884, 50: 0.9156521856784821} 0.6271790862083435
GIN {1: 0.493833988904953, 10: 0.8105928897857666, 30: 0.8760474324226379, 50: 0.8993676006793976} 0.5996083319187164
GINE {1: 0.5225296318531036, 10: 0.8227668106555939, 30: 0.8802371323108673, 50: 0.9008695483207703} 0.6227788627147675
5
Fitting model
ORI exp100 ['ACM_DBLP_1', 'ACM_DBLP_2'] 0.0001 500 17 16 2

Epoch: 118:  23%|██▎       | 117/500 [00:40<02:11,  2.91it/s, Loss: 0.4198]

Stopping early as no improvement has been observed.
Early stopping at epoch 118
Fitting model
GIN exp100 ['ACM_DBLP_1', 'ACM_DBLP_2'] 0.0001 500 17 16 2

Epoch: 175:  35%|███▍      | 174/500 [02:35<04:50,  1.12it/s, Loss: 0.4139]

Stopping early as no improvement has been observed.
Early stopping at epoch 175
Fitting model
GINE exp100 ['ACM_DBLP_1', 'ACM_DBLP_2'] 0.0001 500 17 16 2

Epoch: 259:  52%|█████▏    | 258/500 [04:23<04:06,  1.02s/it, Loss: 0.4240]

Stopping early as no improvement has been observed.
Early stopping at epoch 259

      ACM_DBLP_1  ACM_DBLP_2
0              0        6829
1              1         601
2              2        3102
3              3        3584
4              4        3744
...          ...         ...
9867        9867        3057
9868        9868        9011
9869        9869        3304
9870        9870        5284
9871        9871        2962

[9872 rows x 2 columns]

      ACM_DBLP_1  ACM_DBLP_2
0              0        6829
1              1         601
2              2        3102
3              3        3584
4              4        3744
...          ...         ...
9867        9867        2155
9868        9868        9011
9869        9869        3304
9870        9870        7502
9871        9871        1367

[9872 rows x 2 columns]

      ACM_DBLP_1  ACM_DBLP_2
0              0        6829
1              1         601
2              2        3102
3              3        3584
4              4        3744
...          ...         ...
9867        9867        1522
9868        9868        9011
9869        9869        7661
9870        9870        7665
9871        9871        5465

[9872 rows x 2 columns]

ORI {1: 0.5127272605895996, 10: 0.8303557336330414, 30: 0.8920948803424835, 50: 0.9146245121955872} 0.6200829744338989
GIN {1: 0.49391303956508636, 10: 0.8105928599834442, 30: 0.8757312297821045, 50: 0.9005533456802368} 0.5998557806015015
GINE {1: 0.5207114517688751, 10: 0.8225296437740326, 30: 0.881581038236618, 50: 0.9026086926460266} 0.6218880712985992
6
Fitting model
ORI exp100 ['ACM_DBLP_1', 'ACM_DBLP_2'] 0.0001 500 17 16 2

Epoch: 139:  28%|██▊       | 138/500 [00:47<02:04,  2.90it/s, Loss: 0.4207]

Stopping early as no improvement has been observed.
Early stopping at epoch 139
Fitting model
GIN exp100 ['ACM_DBLP_1', 'ACM_DBLP_2'] 0.0001 500 17 16 2

Epoch: 155:  31%|███       | 154/500 [02:17<05:09,  1.12it/s, Loss: 0.4167]

Stopping early as no improvement has been observed.
Early stopping at epoch 155
Fitting model
GINE exp100 ['ACM_DBLP_1', 'ACM_DBLP_2'] 0.0001 500 17 16 2

Epoch: 227:  45%|████▌     | 226/500 [03:50<04:39,  1.02s/it, Loss: 0.4263]

Stopping early as no improvement has been observed.
Early stopping at epoch 227

      ACM_DBLP_1  ACM_DBLP_2
0              0        6829
1              1         601
2              2        3102
3              3        3584
4              4        3744
...          ...         ...
9867        9867        3057
9868        9868        9011
9869        9869        5642
9870        9870        5284
9871        9871        2962

[9872 rows x 2 columns]

      ACM_DBLP_1  ACM_DBLP_2
0              0        6829
1              1         601
2              2        3102
3              3        3584
4              4        3744
...          ...         ...
9867        9867        2155
9868        9868        9011
9869        9869        2894
9870        9870        7502
9871        9871        7124

[9872 rows x 2 columns]

      ACM_DBLP_1  ACM_DBLP_2
0              0        6829
1              1         601
2              2        3102
3              3        3584
4              4        3744
...          ...         ...
9867        9867        7214
9868        9868        9011
9869        9869        7661
9870        9870        7665
9871        9871        5465

[9872 rows x 2 columns]

ORI {1: 0.5085375607013702, 10: 0.8288537561893463, 30: 0.8911462426185608, 50: 0.9142292439937592} 0.6168765723705292
GIN {1: 0.49438735842704773, 10: 0.8100395202636719, 30: 0.8750988245010376, 50: 0.9011067152023315} 0.6001426577568054
GINE {1: 0.5233201682567596, 10: 0.8210276663303375, 30: 0.8773912787437439, 50: 0.8980237245559692} 0.6232152879238129
7
Fitting model
ORI exp100 ['ACM_DBLP_1', 'ACM_DBLP_2'] 0.0001 500 17 16 2

Epoch: 111:  22%|██▏       | 110/500 [00:37<02:13,  2.92it/s, Loss: 0.4242]

Stopping early as no improvement has been observed.
Early stopping at epoch 111
Fitting model
GIN exp100 ['ACM_DBLP_1', 'ACM_DBLP_2'] 0.0001 500 17 16 2

Epoch: 127:  25%|██▌       | 126/500 [01:52<05:33,  1.12it/s, Loss: 0.4222]

Stopping early as no improvement has been observed.
Early stopping at epoch 127
Fitting model
GINE exp100 ['ACM_DBLP_1', 'ACM_DBLP_2'] 0.0001 500 17 16 2

Epoch: 207:  41%|████      | 206/500 [03:30<05:00,  1.02s/it, Loss: 0.4284]

Stopping early as no improvement has been observed.
Early stopping at epoch 207

      ACM_DBLP_1  ACM_DBLP_2
0              0        6829
1              1         601
2              2        3102
3              3        3584
4              4        3744
...          ...         ...
9867        9867        3057
9868        9868        9011
9869        9869        3304
9870        9870        5284
9871        9871        2962

[9872 rows x 2 columns]

      ACM_DBLP_1  ACM_DBLP_2
0              0        6829
1              1         601
2              2        3102
3              3        3584
4              4        3744
...          ...         ...
9867        9867        3057
9868        9868        9011
9869        9869        3304
9870        9870        7502
9871        9871        1367

[9872 rows x 2 columns]

      ACM_DBLP_1  ACM_DBLP_2
0              0        6829
1              1         601
2              2        3102
3              3        3584
4              4        3744
...          ...         ...
9867        9867        7214
9868        9868        9011
9869        9869        7661
9870        9870        7665
9871        9871        5465

[9872 rows x 2 columns]

ORI {1: 0.5181818306446075, 10: 0.8346244990825653, 30: 0.8933596909046173, 50: 0.9160474240779877} 0.624901533126831
GIN {1: 0.5041897296905518, 10: 0.8114624619483948, 30: 0.8751778900623322, 50: 0.8997628390789032} 0.6074695289134979
GINE {1: 0.5233992040157318, 10: 0.820000022649765, 30: 0.8762055337429047, 50: 0.8959683775901794} 0.6225695013999939
8
Fitting model
ORI exp100 ['ACM_DBLP_1', 'ACM_DBLP_2'] 0.0001 500 17 16 2

Epoch: 102:  20%|██        | 101/500 [00:34<02:17,  2.90it/s, Loss: 0.4240]

Stopping early as no improvement has been observed.
Early stopping at epoch 102
Fitting model
GIN exp100 ['ACM_DBLP_1', 'ACM_DBLP_2'] 0.0001 500 17 16 2

Epoch: 29:   6%|▌         | 28/500 [00:24<06:56,  1.13it/s, Loss: 0.4868]

##### Summary

In [ ]:
list_exp

In [ ]:
columns = ["Dataset", "Encoder", "Runtime", "Accuracy"] + [f"Hits@{k}" for k in list(hits.keys())] +  ["MRR"]
df_summary = pd.DataFrame(list_exp, columns=columns)
df_summary.sort_values(by=["Encoder"], inplace=True)
df_summary

In [ ]:
df_text = df_summary.map(lambda x: f"{x}".replace(".", ","))
df_text

In [ ]:
print(NUM_HIDDEN_LAYERS)
print(HIDDEN_DIM)
print(output_feature_size)