In [1]:
# Torch version
!python -c "import torch; print(torch.__version__)"

# Cuda version
!python -c "import torch; print(torch.version.cuda)"

2.6.0+cu124
12.4

In [2]:
# Uninstall
# !pip uninstall torch-scatter torch-sparse torch-cluster torch-spline-conv pyg-lib -y

In [3]:
# Update Torch
# !pip install torch==2.6.0 torchvision==0.21.0 torchaudio==2.6.0 --index-url https://download.pytorch.org/whl/cu124

In [4]:
# Install PyG (automatic)
# !pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-{torch.__version__}.html
# !pip install torch_geometric

In [5]:
# Verify instalation
import torch
import torch_geometric
import torch_scatter

print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.is_available())
print(torch_scatter.__version__)
print(torch_geometric.__version__)

2.6.0+cu124
12.4
True
2.1.2+pt26cu124
2.7.0

In [6]:
from model_PyG import *
from utils import *

In [7]:
import json
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
import pandas as pd
import time
import torch
import torch.nn.functional as F
import torch_geometric.transforms as T

from mpl_toolkits.mplot3d import Axes3D
from sklearn.decomposition import PCA
from sklearn.neighbors import NearestNeighbors
from torch_geometric.data import InMemoryDataset, Data
from torch_geometric.nn.conv.gcn_conv import gcn_norm
from torch_geometric.transforms import Compose
from torch_geometric.utils import dense_to_sparse, negative_sampling
from torch.nn.functional import binary_cross_entropy_with_logits
from torch.optim import Adam

In [8]:
import torch_geometric
print(torch_geometric.__version__)

np.random.seed(0)
torch.manual_seed(0)
torch.cuda.manual_seed(0)
torch.cuda.manual_seed_all(0)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

2.7.0

### Parameters

In [9]:
file = open("exp.json")
experiment = json.load(file)
exp = experiment["exp"] # Change to static, e.g. "exp1"

file = open("experiments/output/{}/parameters.json".format(exp))
params = json.load(file)

print("Exp:\t\t", exp)

raw_data_file = params["raw_data_file"]
print("Raw data:\t", raw_data_file)

methods = params["methods"]
print("Methods:\t", methods)

apply_transformation = params["apply_transformation"]
print("Has transformation:", apply_transformation)

dimension = params["dimension"]
print("Dimension:\t", dimension)

groups_id = params["groups_id"]
print("Groups id:\t", groups_id)

subgroups_id = params["subgroups_id"]
print("Subgroups id:\t", subgroups_id)

epochs = params["epochs"]
print("Epochs:\t", epochs)

cuda = params["cuda"]
print("Cuda:\t", cuda)

weight_decay = params["weight_decay"]
print("Weight decay:\t", weight_decay)

lr = params["lr"]
print("Lr:\t", lr)

Exp:		 exp104
Raw data:	 douban
Methods:	 ['t-gae']
Has transformation: False
Dimension:	 512
Groups id:	 ['douban']
Subgroups id:	 {'douban': ['1', '2']}
Epochs:	 500
Cuda:	 1
Weight decay:	 0.0001
Lr:	 0.0001

### Setup

In [10]:
# Parameters models

dataset = exp
encoders = ["GCNRes", "GIN", "GINE", "GCN", "GAT", "GATE"] # ["GIN", "GINE"] # ["GIN", "GINE"] # ["GIN", "GINE"] # Change
device = torch.device(f"cuda:{cuda}" if torch.cuda.is_available() else "cpu")
# device = torch.device("cpu")

NUM_HIDDEN_LAYERS = 12
HIDDEN_DIM = [1024] * NUM_HIDDEN_LAYERS + [1024]
output_feature_size = dimension # 128
# lr = 0.001
# epochs = 100

In [11]:
# Create datasets (groups and subgroups)

list_train_set = []

for group_id in groups_id:
	train_set = []
	for subgroup_id in subgroups_id[group_id]:
		train_set.append("{}_{}".format(group_id, subgroup_id))
	list_train_set.append(train_set)
list_train_set

[['douban_1', 'douban_2']]

### Create Data (PyG)

In [12]:
# Only for GIN
""" transform = Compose([
	# T.NormalizeFeatures(),
	T.ToUndirected(reduce="mean"),
	T.AddSelfLoops(fill_value=1.0),
	T.ToDevice(device)
]) """

# For GIN and GINE
transform = T.Compose([
	# T.NormalizeFeatures(),
	T.ToUndirected(reduce="mean"),
	# T.AddSelfLoops(attr="edge_attr", fill_value="mean"),
	# T.AddLaplacianEigenvectorPE(k=3, attr_name=None, is_undirected=True),
	# T.AddRandomWalkPE(walk_length=8, attr_name=None),
	T.ToDevice(device)
])

In [ ]:
print("Loading training datasets")
has_edge_attributes = False
with_mean1 = True
with_mean2 = True

list_train_loader = []

if raw_data_file == "ACM_DBLP":
	group_id = groups_id[0]
	
	# Read dataset
	b = np.load("data/ACM-DBLP.npz")

	# Node matching
	test_pairs = b["test_pairs"].astype(np.int32)
	pos_pairs = b["pos_pairs"].astype(np.int32)
	df_node_alignment_truth = pd.DataFrame(np.concatenate((test_pairs, pos_pairs), axis=0))
	df_node_alignment_truth

	# Data preparation
	subgroup_id = 1
	edge_index1 = torch.tensor(b[f"edge_index{subgroup_id}"], dtype=torch.long)
	x1 = torch.tensor(b[f"x{subgroup_id}"], dtype=torch.float)

	subgroup_id = 2
	edge_index2 = torch.tensor(b[f"edge_index{subgroup_id}"], dtype=torch.long)
	x2 = torch.tensor(b[f"x{subgroup_id}"], dtype=torch.float)

elif raw_data_file == "Douban Online_Offline":
	group_id = groups_id[0]
	
	# Read dataset
	a1, f1, a2, f2, test_pairs = load_douban()

	# Node matching
	test_pairs = torch.tensor(np.array(test_pairs, dtype=int)) - 1
	test_pairs = test_pairs.numpy()
	df_node_alignment_truth = pd.DataFrame(test_pairs.T)
	df_node_alignment_truth

	# Create data
	edge_index1, _ = dense_to_sparse(torch.from_numpy(a1.toarray()))
	x1 = torch.from_numpy(f1.toarray()).float()

	edge_index2, _= dense_to_sparse(torch.from_numpy(a2.toarray()))
	x2 = torch.from_numpy(f2.toarray()).float()

	with_mean1 = False
	with_mean2 = False

elif raw_data_file == "Cora1-Cora2":
	group_id = groups_id[0]
		
	# Read dataset
	loader = load_npz("data/cora.npz")
	data = loader["adj_matrix"]
	samples = data.shape[0]
	features = data.shape[1]
	values = data.data
	coo_data = data.tocoo()
	# indices = torch.LongTensor([coo_data.row, coo_data.col])
	indices = np.array([coo_data.row, coo_data.col])

	# Node matching
	N = 2708
	test_pairs = [[i, i] for i in range(N)]
	df_node_alignment_truth = pd.DataFrame(test_pairs)
	df_node_alignment_truth

	# Create data
	node_features = loader["node_attr"]
	node_features = node_features.toarray()

	edge_index1 = torch.tensor(indices, dtype=torch.long)
	x1 = torch.tensor(node_features, dtype=torch.float)

	edge_index2 = torch.tensor(indices, dtype=torch.long)
	x2 = torch.tensor(node_features, dtype=torch.float)

	with_mean1 = False
	with_mean2 = True

elif raw_data_file == "flickr-lastfm":
	# https://github.com/yq-leo/PlanetAlign/blob/main/PlanetAlign/datasets/flickr_lastfm.py
	data = torch.load("data/flickr-lastfm.pt")
	edges = data["edges"]
	node_features = data["node_attributes"]
	edges_attributes = data["edge_attributes"]
	
	# Node matching
	test_pairs = data["anchor_links"].cpu().numpy()
	df_node_alignment_truth = pd.DataFrame(test_pairs)
	df_node_alignment_truth

	# Create data
	edge_index1 = edges[0]
	x1 = torch.tensor(node_features[0].cpu().numpy(), dtype=torch.float)
	edge_attr1 = torch.tensor(edges_attributes[0].cpu().numpy(), dtype=torch.float)

	edge_index2 = edges[1]
	x2 = torch.tensor(node_features[1].cpu().numpy(), dtype=torch.float)
	edge_attr2 = torch.tensor(edges_attributes[1].cpu().numpy(), dtype=torch.float)

	has_edge_attributes = True
	with_mean1 = False
	with_mean2 = False

elif raw_data_file == "douban":
	# https://github.com/yq-leo/PlanetAlign/blob/main/PlanetAlign/datasets/flickr_lastfm.py
	data = torch.load("data/douban.pt")
	edges = data["edges"]
	node_features = data["node_attributes"]
	edges_attributes = data["edge_attributes"]
	
	# Node matching
	test_pairs = data["anchor_links"].cpu().numpy()
	df_node_alignment_truth = pd.DataFrame(test_pairs)
	df_node_alignment_truth

	# Create data
	edge_index1 = edges[0]
	x1 = torch.tensor(node_features[0].cpu().numpy(), dtype=torch.float)
	edge_attr1 = torch.tensor(edges_attributes[0].cpu().numpy(), dtype=torch.float)

	edge_index2 = edges[1]
	x2 = torch.tensor(node_features[1].cpu().numpy(), dtype=torch.float)
	edge_attr2 = torch.tensor(edges_attributes[1].cpu().numpy(), dtype=torch.float)

	has_edge_attributes = True
	with_mean1 = False
	with_mean2 = False

elif raw_data_file == "flickr-myspace":
	# https://github.com/yq-leo/PlanetAlign/blob/main/PlanetAlign/datasets/flickr_lastfm.py
	data = torch.load("data/flickr-myspace.pt")
	edges = data["edges"]
	node_features = data["node_attributes"]
	edges_attributes = data["edge_attributes"]
	
	# Node matching
	test_pairs = data["anchor_links"].cpu().numpy()
	df_node_alignment_truth = pd.DataFrame(test_pairs)
	df_node_alignment_truth

	# Create data
	edge_index1 = edges[0]
	x1 = torch.tensor(node_features[0].cpu().numpy(), dtype=torch.float)
	edge_attr1 = torch.tensor(edges_attributes[0].cpu().numpy(), dtype=torch.float)

	edge_index2 = edges[1]
	x2 = torch.tensor(node_features[1].cpu().numpy(), dtype=torch.float)
	edge_attr2 = torch.tensor(edges_attributes[1].cpu().numpy(), dtype=torch.float)

	has_edge_attributes = True
	with_mean1 = False
	with_mean2 = False

elif raw_data_file == "ACM-DBLP":
	# https://github.com/yq-leo/PlanetAlign/blob/main/PlanetAlign/datasets/flickr_lastfm.py
	data = torch.load("data/ACM-DBLP.pt")
	edges = data["edges"]
	node_features = data["node_attributes"]
	# edges_attributes = data["edge_attributes"]
	
	# Node matching
	test_pairs = data["anchor_links"].cpu().numpy()
	df_node_alignment_truth = pd.DataFrame(test_pairs)
	df_node_alignment_truth

	# Create data
	edge_index1 = edges[0]
	x1 = torch.tensor(node_features[0].cpu().numpy(), dtype=torch.float)
	# edge_attr1 = torch.tensor(edges_attributes[0].cpu().numpy(), dtype=torch.float)

	edge_index2 = edges[1]
	x2 = torch.tensor(node_features[1].cpu().numpy(), dtype=torch.float)
	# edge_attr2 = torch.tensor(edges_attributes[1].cpu().numpy(), dtype=torch.float)

	has_edge_attributes = False
	with_mean1 = True
	with_mean2 = True

elif raw_data_file == "cora":
	# https://github.com/yq-leo/PlanetAlign/blob/main/PlanetAlign/datasets/flickr_lastfm.py
	data = torch.load("data/cora.pt")
	edges = data["edges"]
	node_features = data["node_attributes"]
	# edges_attributes = data["edge_attributes"]
	
	# Node matching
	test_pairs = data["anchor_links"].cpu().numpy()
	df_node_alignment_truth = pd.DataFrame(test_pairs)
	df_node_alignment_truth

	# Create data
	edge_index1 = edges[0]
	x1 = torch.tensor(node_features[0].cpu().numpy(), dtype=torch.float)
	# edge_attr1 = torch.tensor(edges_attributes[0].cpu().numpy(), dtype=torch.float)

	edge_index2 = edges[1]
	x2 = torch.tensor(node_features[1].cpu().numpy(), dtype=torch.float)
	# edge_attr2 = torch.tensor(edges_attributes[1].cpu().numpy(), dtype=torch.float)

	has_edge_attributes = False
	with_mean1 = False
	with_mean2 = True

# Create data
train_loader = {}

# Include edge_attr
subgroup_id = 1
data1 = Data(x=x1, edge_index=edge_index1)
if has_edge_attributes:
    data1.edge_attr = edge_attr1
else:
	data1 = add_edge_attributes(data1)
print(subgroup_id, data1)
info_data(data1, include_vectors=True)

subgroup_id = 2
data2 = Data(x=x2, edge_index=edge_index2)
if has_edge_attributes:
    data2.edge_attr = edge_attr2
else:
	data2 = add_edge_attributes(data2)
print(subgroup_id, data2)
info_data(data2, include_vectors=True)

# Normalize
normalize_node_edge_features(data1, data2, with_mean1=with_mean1, with_mean2=with_mean2) # Important

# Apply transform
subgroup_id = 1
data1 = transform(data1)
print(subgroup_id, data1)
# info(data1)

subgroup_id = 2
data2 = transform(data2)
print(subgroup_id, data2)
# info(data2)

# Include edge_weight
subgroup_id = 1
edge_index_norm1, edge_weight_norm1 = gcn_norm(
	data1.edge_index, num_nodes=data1.num_nodes, add_self_loops=False
)
data1.edge_index = edge_index_norm1
data1.edge_weight = edge_weight_norm1
train_loader[f"{group_id}_{subgroup_id}"] = data1
print(1, data1)

subgroup_id = 2
edge_index_norm2, edge_weight_norm2 = gcn_norm(
	data2.edge_index, num_nodes=data2.num_nodes, add_self_loops=False
)
data2.edge_index = edge_index_norm2
data2.edge_weight = edge_weight_norm2
train_loader[f"{group_id}_{subgroup_id}"] = data2
print(2, data2)

info_data(data1, include_vectors=True)
info_data(data2, include_vectors=True)

list_train_loader.append(train_loader)

Loading training datasets
1 Data(x=[3906, 538], edge_index=[2, 16328], edge_attr=[16328, 2])
Validate:	 True
Num. nodes:	 3906
Num. edges:	 16328
Num. features:	 538
Has isolated:	 False
Has loops:	 False
Is directed:	 True
Is undirected:	 False
tensor([[   0,    0,    1,  ..., 3904, 3905, 3905],
        [ 728, 3714,  160,  ..., 3671, 2166, 3790]])
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
tensor([[0., 1.],
        [0., 1.],
        [0., 1.],
        ...,
        [1., 0.],
        [0., 1.],
        [0., 1.]])
2 Data(x=[1118, 538], edge_index=[2, 3022], edge_attr=[3022, 2])
Validate:	 True
Num. nodes:	 1118
Num. edges:	 3022
Num. features:	 538
Has isolated:	 False
Has loops:	 False
Is directed:	 False
Is undirected:	 True
tensor([[   0,    1,    1,  ..., 1117, 1117, 1117],
        [ 819,  268,  592,  ...,  538,  836,  896]])
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
tensor([[0., 1.],
        [0., 1.],
        [0., 1.],
        ...,
        [0., 1.],
        [0., 1.],
        [0., 1.]])
1 Data(x=[3906, 538], edge_index=[2, 16328], edge_attr=[16328, 2])
2 Data(x=[1118, 538], edge_index=[2, 3022], edge_attr=[3022, 2])
1 Data(x=[3906, 538], edge_index=[2, 16328], edge_attr=[16328, 2], edge_weight=[16328])
2 Data(x=[1118, 538], edge_index=[2, 3022], edge_attr=[3022, 2], edge_weight=[3022])
Validate:	 True
Num. nodes:	 3906
Num. edges:	 16328
Num. features:	 538
Has isolated:	 False
Has loops:	 False
Is directed:	 False
Is undirected:	 True
tensor([[   0,    0,    1,  ..., 3904, 3905, 3905],
        [ 728, 3714,  160,  ..., 3671, 2166, 3790]], device='cuda:1')
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:1')
tensor([[0.0000, 2.3112],
        [1.1556, 1.1556],
        [0.0000, 2.3112],
        ...,
        [1.1556, 1.1556],
        [1.1556, 1.1556],
        [0.0000, 2.3112]], device='cuda:1')
Validate:	 True
Num. nodes:	 1118
Num. edges:	 3022
Num. features:	 538
Has isolated:	 False
Has loops:	 False
Is directed:	 False
Is undirected:	 True
tensor([[   0,    1,    1,  ..., 1117, 1117, 1117],
        [ 819,  268,  592,  ...,  538,  836,  896]], device='cuda:1')
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:1')
tensor([[0.0000, 2.3112],
        [0.0000, 2.3112],
        [0.0000, 2.3112],
        ...,
        [0.0000, 2.3112],
        [0.0000, 2.3112],
        [0.0000, 2.3112]], device='cuda:1')

In [14]:
df_node_alignment_truth

         0    1
0      831  322
1     1033  537
2     3328  453
3     2535  795
4     3115  612
...    ...  ...
1113  3309  473
1114  1051  325
1115  2819  396
1116  2869  757
1117  3342    3

[1118 rows x 2 columns]

### Train

In [15]:
def fit_TGAE_subgraph_(encoder, dataset, no_samples, model, epochs, train_loader, lr, test_pairs=None):
	best_hitAtOne = 0
	best_hitAtFive = 0
	best_hitAtTen = 0
	best_hitAtFifty = 0
	list_loss = []

	optimizer = Adam(model.parameters(), lr=lr,weight_decay=5e-4)
	
	# Initialize early stopping
	patience = 50 # Change 
	delta = 1e-4 # 1e-4
	warmup = 10
	early_stopping = EarlyStopping(patience=patience, delta=delta, warmup=warmup, verbose=True)

	loop_obj = tqdm(range(1, epochs + 1))
	for epoch in loop_obj:
		loop_obj.set_description(f"Epoch: {epoch}")
		
		# Train
		model.train()
		loss = 0.0
		
		for ts in random.sample(train_set, k=len(train_set)): # shuffle train_set
			data = train_loader[ts]

			# Encoder
			if encoder == "GIN":
				z = model(data.x, data.edge_index)
				# z = F.normalize(z, dim=1)
			elif encoder == "GINE":
				z = model(data.x, data.edge_index, data.edge_attr)

			# Positive edges
			pos_edge_index = data.edge_index
			
			# Negative edges
			# option 1
			neg_edge_index = negative_sampling(
				edge_index=data.edge_index,
				num_nodes=z.size(0),
				num_neg_samples=pos_edge_index.size(1), # Change 2 to other value if needed
				method="sparse"
			)

			# option 2 Negative edges (dynamic)
			""" ratio = neg_ratio_schedule(epoch, epochs)
			num_neg = compute_num_neg_samples(
				edge_index=edge_index,
				num_nodes=z.size(0),
				ratio=ratio
			)
			neg_edge_index = negative_sampling(
				edge_index=edge_index,
				num_nodes=z.size(0),
				num_neg_samples=num_neg,
				method="sparse"
			) """
			
			# Decoder
			# option 1
			pos_logits = (z[pos_edge_index[0]] * z[pos_edge_index[1]]).sum(dim=1)
			neg_logits = (z[neg_edge_index[0]] * z[neg_edge_index[1]]).sum(dim=1)
			
			# option 2
			""" pos_logits = F.cosine_similarity(
				z[pos_edge_index[0]],
				z[pos_edge_index[1]],
				dim=1
			)
			neg_logits = F.cosine_similarity(
				z[neg_edge_index[0]],
				z[neg_edge_index[1]],
				dim=1
			) """

			# Loss
			pos_labels = torch.ones_like(pos_logits)
			neg_labels = torch.zeros_like(neg_logits)

			# option 1
			""" loss_pos = binary_cross_entropy_with_logits(pos_logits, pos_labels)
			loss_neg = binary_cross_entropy_with_logits(neg_logits, neg_labels)
			loss += loss_pos + loss_neg """

			# option 2
			# num_pos = pos_edge_index.size(1)
			# num_neg = neg_edge_index.size(1)
			# pos_weight = torch.tensor([num_neg / num_pos], device=device)
			logits = torch.cat([pos_logits, neg_logits], dim=0)
			labels = torch.cat([pos_labels, neg_labels], dim=0)
			loss_temp = F.binary_cross_entropy_with_logits(logits, labels) #, pos_weight=pos_weight) # with pos_weight
			loss += loss_temp
			
		optimizer.zero_grad()
		loss = loss / no_samples
		loss.backward()
		optimizer.step()

		loop_obj.set_postfix_str(f"Loss: {loss.item():.4f}")
		list_loss.append(loss.item())

		# Check early stopping condition
		early_stopping.check_early_stop(loss.item(), epoch)
		if early_stopping.stop_training:
			print(f"Early stopping at epoch {epoch}")
			break

		# Evaluation (for firts dataset)
		""" model.eval()
		with torch.no_grad():
			keys = list(train_loader.keys())
			data1 = train_loader[keys[0]]
			data2 = train_loader[keys[1]]

			z1 = model(data1.x, data1.edge_index).detach()
			z2 = model(data2.x, data2.edge_index).detach()
			
			# Similarity matrix
			# option 1
			D = torch.cdist(z1, z2, 2)

			# option 2 (GPU problem)
			# D = 1 - F.cosine_similarity(z1.unsqueeze(1), z2.unsqueeze(0), dim=-1)

			# option 3 (Decoder cosine similarity)
			" "" z1n = F.normalize(z1, dim=1)
			z2n = F.normalize(z2, dim=1)
			D = 1 - (z1n @ z2n.T) " ""

			if dataset == "ACM_DBLP":
				test_idx = test_pairs[:, 0].astype(int)
				labels = test_pairs[:, 1].astype(int)
			else:
				test_idx = test_pairs[0, :].astype(int)
				labels = test_pairs[1, :].astype(int)
				
			hitAtOne = 0
			hitAtFive = 0
			hitAtTen = 0
			hitAtFifty = 0
			hitAtHundred = 0
			for i in range(len(test_idx)):
				dist_list = D[test_idx[i]]
				sorted_neighbors = torch.argsort(dist_list).cpu()
				label = labels[i]
				for j in range(100):
					if (sorted_neighbors[j].item() == label):
						if (j == 0):
							hitAtOne += 1
							hitAtFive += 1
							hitAtTen += 1
							hitAtFifty += 1
							hitAtHundred += 1
							break
						elif (j <= 4):
							hitAtFive += 1
							hitAtTen += 1
							hitAtFifty += 1
							hitAtHundred += 1
							break
						elif (j <= 9):
							hitAtTen += 1
							hitAtFifty += 1
							hitAtHundred += 1
							break
						elif (j <= 49):
							hitAtFifty += 1
							hitAtHundred += 1
							break
						elif (j <= 100):
							hitAtHundred += 1
							break
			cur_hitAtOne = hitAtOne / len(test_idx)
			cur_hitAtFive = hitAtFive / len(test_idx)
			cur_hitAtTen = hitAtTen / len(test_idx)
			cur_hitAtFifty = hitAtFifty / len(test_idx)

			if(cur_hitAtOne > best_hitAtOne): best_hitAtOne = cur_hitAtOne
			if (cur_hitAtFive > best_hitAtFive): best_hitAtFive = cur_hitAtFive
			if (cur_hitAtTen > best_hitAtTen): best_hitAtTen = cur_hitAtTen
			if (cur_hitAtFifty > best_hitAtFifty): best_hitAtFifty = cur_hitAtFifty

	print("The best results achieved:")
	print("Hit@1: ", end="")
	print(best_hitAtOne)
	print("Hit@5: ", end="")
	print(best_hitAtFive)
	print("Hit@10: ", end="")
	print(best_hitAtTen)
	print("Hit@50: ", end="")
	print(best_hitAtFifty) """

	# Evaluation (for others dataset)
	dict_node_embeddings = {}
	model.eval()
	with torch.no_grad():
		for ts in train_set:
			data = train_loader[ts]
			if encoder == "GIN":
				z = model(data.x, data.edge_index)
			elif encoder == "GINE":
				z = model(data.x, data.edge_index, data.edge_attr)
			dict_node_embeddings[ts] = z.cpu().numpy()

	del loss, z
	# torch.cuda.synchronize()
	torch.cuda.empty_cache()
	
	return dict_node_embeddings, list_loss

In [ ]:
def fit_TGAE_subgraph(model, encoder, exp, group_id, subgroups_id, train_loader, train_set, no_samples, epochs, lr, weight_decay):
	list_loss = []

	optimizer = Adam(model.parameters(), lr=lr, weight_decay=weight_decay)
	
	# Initialize early stopping
	patience = 10 # Change
	delta = 1e-4
	warmup = 10
	early_stopping = EarlyStopping(patience=patience, delta=delta, warmup=warmup, verbose=True)

	loop_obj = tqdm(range(1, epochs + 1))
	
	# Train mode
	model.train() # Set the model to training mode (enables dropout and BN updates)
	
	for epoch in loop_obj:
		loop_obj.set_description(f"Epoch: {epoch}")
		
		optimizer.zero_grad() # Reset accumulated gradients before backpropagation
		
		loss = torch.tensor(0.0, device=device)
		
		for ts in random.sample(train_set, k=len(train_set)): # shuffle train_set
			data = train_loader[ts]

			# Encoder
			if encoder == "GIN":
				z = model(data.x, data.edge_index)
				# z = F.normalize(z, dim=1)
			elif encoder == "GINE":
				z = model(data.x, data.edge_index, data.edge_attr)
			elif encoder == "GCNRes":
				z = model(data.x, data.edge_index, data.edge_weight)
			elif encoder == "GCN":
				z = model(data.x, data.edge_index, data.edge_weight)
			elif encoder == "GAT":
				z = model(data.x, data.edge_index)
			elif encoder == "GATE":
				z = model(data.x, data.edge_index, data.edge_attr)

			# Positive edges
			pos_edge_index = data.edge_index
			
			# Negative edges
			# option 1
			neg_edge_index = negative_sampling(
				edge_index=data.edge_index,
				num_nodes=z.size(0),
				num_neg_samples=pos_edge_index.size(1), # Change 2 to other value if needed
				method="sparse"
			)

			# option 2 Negative edges (dynamic)
			""" ratio = neg_ratio_schedule(epoch, epochs)
			num_neg = compute_num_neg_samples(
				edge_index=edge_index,
				num_nodes=z.size(0),
				ratio=ratio
			)
			neg_edge_index = negative_sampling(
				edge_index=edge_index,
				num_nodes=z.size(0),
				num_neg_samples=num_neg,
				method="sparse"
			) """
			
			# Decoder
			# option 1
			pos_logits = (z[pos_edge_index[0]] * z[pos_edge_index[1]]).sum(dim=1)
			neg_logits = (z[neg_edge_index[0]] * z[neg_edge_index[1]]).sum(dim=1)
			
			# option 2
			""" pos_logits = F.cosine_similarity(
				z[pos_edge_index[0]],
				z[pos_edge_index[1]],
				dim=1
			)
			neg_logits = F.cosine_similarity(
				z[neg_edge_index[0]],
				z[neg_edge_index[1]],
				dim=1
			) """

			# Loss
			pos_labels = torch.ones_like(pos_logits)
			neg_labels = torch.zeros_like(neg_logits)

			# option 1
			""" loss_pos = binary_cross_entropy_with_logits(pos_logits, pos_labels)
			loss_neg = binary_cross_entropy_with_logits(neg_logits, neg_labels)
			loss += loss_pos + loss_neg """

			# option 2
			# num_pos = pos_edge_index.size(1)
			# num_neg = neg_edge_index.size(1)
			# pos_weight = torch.tensor([num_neg / num_pos], device=device)
			logits = torch.cat([pos_logits, neg_logits], dim=0)
			labels = torch.cat([pos_labels, neg_labels], dim=0)
			loss_temp = F.binary_cross_entropy_with_logits(logits, labels) #, pos_weight=pos_weight) # with pos_weight
			loss += loss_temp
			
		loss = loss / no_samples
		loss.backward() # Compute gradients of the loss w.r.t. model parameters
		optimizer.step() # Update model parameters using computed gradients

		loop_obj.set_postfix_str(f"Loss: {loss.item():.4f}")
		list_loss.append(loss.item())

		# Check early stopping condition
		early_stopping.check_early_stop(loss.item(), epoch)
		if early_stopping.stop_training:
			print(f"Early stopping at epoch {epoch}")
			break
		# torch.cuda.empty_cache()
	# Evaluation (for others dataset)
	list_df_node_embeddings = []

	model.eval() # Set the model to evaluation mode (disables dropout and BN updates)
	with torch.no_grad():
		for subgroup_id in subgroups_id:

			# Get node embeddings
			data = train_loader[f"{group_id}_{subgroup_id}"]
			if encoder == "GIN":
				z = model(data.x, data.edge_index)
			elif encoder == "GINE":
				z = model(data.x, data.edge_index, data.edge_attr)
			elif encoder == "GCNRes":
				z = model(data.x, data.edge_index, data.edge_weight)
			elif encoder == "GCN":
				z = model(data.x, data.edge_index, data.edge_weight)
			elif encoder == "GAT":
				z = model(data.x, data.edge_index)
			elif encoder == "GATE":
				z = model(data.x, data.edge_index, data.edge_attr)

			df_node_embeddings = pd.DataFrame(z.cpu().numpy())
			df_node_embeddings["subgroup_id"] = [subgroup_id] * len(df_node_embeddings)
			
			# Get node ids to replace original Id (this is only for MS data)
			""" df_nodes = pd.read_csv(f"experiments/output/{exp}/preprocessing/graphs_data/nodes_{group_id}_{subgroup_id}.csv")
			# idx, id, mz, rt, intensity_mean, intensity_cv
			df_node_embeddings.insert(0, "Id", df_nodes["id"].values) """

			df_node_embeddings.insert(0, "Id", range(len(df_node_embeddings))) # this is only for no MS data
			list_df_node_embeddings.append(df_node_embeddings)

		# Concat node embeddings
		df_node_embeddings_concat = pd.concat(list_df_node_embeddings, ignore_index=True)
		
		# Save node embeddings
		df_node_embeddings_concat.to_csv(f"experiments/output/{exp}/node_embeddings/{encoder}_{group_id}.csv", index=False)
	
	# Save loss
	np.save(f"experiments/output/{exp}/loss/{encoder}_{group_id}.npy", np.array(list_loss))

	del loss, z
	# torch.cuda.synchronize()
	torch.cuda.empty_cache()

In [17]:
encoders

['GCNRes', 'GIN', 'GINE', 'GCN', 'GAT', 'GATE']

In [18]:
list_train_set

[['douban_1', 'douban_2']]

In [19]:
list_train_loader

[{'douban_1': Data(x=[3906, 538], edge_index=[2, 16328], edge_attr=[16328, 2], edge_weight=[16328]),
  'douban_2': Data(x=[1118, 538], edge_index=[2, 3022], edge_attr=[3022, 2], edge_weight=[3022])}]

In [20]:
num_exp = 10 # Change

list_exp = []

for n_exp in range(num_exp):
	print(n_exp)
	#---
	# Train
	#---
	for encoder in encoders:
		for i, train_loader in enumerate(list_train_loader):
			""" np.random.seed(0)
			torch.manual_seed(0)
			torch.cuda.manual_seed(0)
			torch.cuda.manual_seed_all(0)
			torch.backends.cudnn.deterministic = True
			torch.backends.cudnn.benchmark = False """

			group_id = groups_id[i]
			subgroup_id = subgroups_id[group_id]

			train_set = list_train_set[i]

			no_samples = len(train_set) # * (1 + 1)  # num datasets * num of samples by dataset 
			input_dim = train_loader[train_set[0]].num_node_features

			if encoder == "GIN":
				model = TGAE_GIN(NUM_HIDDEN_LAYERS, 
							input_dim,
							HIDDEN_DIM,
							output_feature_size).to(device)
			elif encoder == "GINE":
				edge_dim = train_loader[train_set[0]].edge_attr.size(1)
				model = TGAE_GINE(NUM_HIDDEN_LAYERS,
							input_dim,
							HIDDEN_DIM,
							output_feature_size, edge_dim).to(device)
			elif encoder == "GCNRes":
				model = TGAE_GCNRes(NUM_HIDDEN_LAYERS,
							input_dim,
							HIDDEN_DIM,
							output_feature_size).to(device)
			elif encoder == "GCN":
				model = TGAE_GCN(NUM_HIDDEN_LAYERS,
							input_dim,
							HIDDEN_DIM,
							output_feature_size).to(device)
			elif encoder == "GAT":
				model = TGAE_GATv2(NUM_HIDDEN_LAYERS, 
							input_dim,
							HIDDEN_DIM,
							output_feature_size).to(device)
			elif encoder == "GATE":
				edge_dim = train_loader[train_set[0]].edge_attr.size(1)
				model = TGAE_GATv2E(NUM_HIDDEN_LAYERS,
							input_dim,
							HIDDEN_DIM,
							output_feature_size, edge_dim).to(device)
			print("Fitting model")
			print(encoder, dataset, train_set, lr, epochs, input_dim, output_feature_size, no_samples)

			# Calculate elapsed time
			start_time = time.perf_counter()
			
			fit_TGAE_subgraph(model, encoder, dataset, group_id, subgroup_id, train_loader, train_set, no_samples, epochs, lr, weight_decay)

			end_time = time.perf_counter()
			execution_time = end_time - start_time

			list_exp.append([raw_data_file, encoder, execution_time])

	#---
	# Similarity analysis
	#---
	k = 1 # Change
	for encoder in encoders:
		for group_id in groups_id:
			df_node_embeddings_concat = pd.read_csv(f"experiments/output/{exp}/node_embeddings/{encoder}_{group_id}.csv", dtype={"subgroup_id": "string"})
			# Id, 0, 1,	2, ..., subgroup_id

			subgroups_id_ = subgroups_id[group_id]

			# Calculate distance matrix (KNN)
			knn = NearestNeighbors(n_neighbors=k, metric="euclidean")

			df_node_embeddings = df_node_embeddings_concat[df_node_embeddings_concat["subgroup_id"] == subgroups_id_[0]]
			x = df_node_embeddings.iloc[:, 1:-1].values

			df_node_alignment = pd.DataFrame()
			df_node_alignment[f"{group_id}_{subgroups_id_[0]}"] = df_node_embeddings["Id"].values

			for subgroup_id in subgroups_id_[1:]:
				df_node_embeddings = df_node_embeddings_concat[df_node_embeddings_concat["subgroup_id"] == subgroup_id]
				y = df_node_embeddings.iloc[:, 1:-1].values

				knn.fit(y)
				distances, indices = knn.kneighbors(x)
				indices = indices.squeeze() # (N,)

				df_node_alignment[f"{group_id}_{subgroup_id}"] = df_node_embeddings["Id"].values[indices]
				
				""" df_node_alignment[f"distances"] = distances
				avg_distances = df_node_alignment["distances"].mean()
				df_node_alignment = df_node_alignment[df_node_alignment["distances"] <= avg_distances].iloc[:, :-1]
				df_node_alignment """
			
			# Save previus node alignment
			df_node_alignment.to_csv(f"experiments/output/{exp}/filter_raw/node_alignment_{encoder}_{group_id}.csv")
			# display(df_node_alignment)

			# Find node alignment for all datasets
			""" df_node_alignment_filter = df_node_alignment[df_node_alignment.nunique(axis=1) == 1]
			list_count_meta.append([encoder, group_id, len(df_node_alignment_filter), len(df_node_alignment)])
			# print(len(df_node_alignment_filter))
			# display(df_node_alignment_filter)
			print(f"{encoder}-{group_id}: {len(df_node_alignment_filter)}")
			
			# Save common node id
			# common_node_id = df_node_alignment_filter.iloc[:, 0].values
			# np.save(f"experiments/output/{exp}/common_nodes/{encoder}_{group_id}.npy", np.array(common_node_id)) """

			# Save common node id as .csv
			df_common_node_id = df_node_alignment.iloc[:, [0, 1]].copy() # df_common_node_id = df_node_alignment_filter.iloc[:, [0, 1]].copy()
			df_common_node_id.sort_values(by=df_common_node_id.columns[0], inplace=True)
			df_common_node_id.to_csv(f"experiments/output/{exp}/common_nodes/{encoder}_{group_id}.csv", index=False, header=False)

	# Intersection and Union
	""" list_common_node_id = []
	for encoder in encoders:
		for group_id in groups_id:
			# Read common node
			common_node_id = np.load(f"experiments/output/{exp}/common_nodes/{encoder}_{group_id}.npy")
			list_common_node_id.append(common_node_id)

		common_node_id_union = list(set.union(*map(set, list_common_node_id)))
		common_node_id_intersection = list(set.intersection(*map(set, list_common_node_id)))

		# Save common node id
		np.save(f"experiments/output/{exp}/common_nodes/{encoder}_union.npy", np.array(common_node_id_union))
		np.save(f"experiments/output/{exp}/common_nodes/{encoder}_intersection.npy", np.array(common_node_id_intersection)) """

	#---
	# Evaluation
	#---
	# list_accuracy = []
	# list_encoder = []

	for j, encoder in enumerate(encoders):
		for group_id in groups_id:
			# Read node alignment
			df_common_node_id = pd.read_csv(f"experiments/output/{exp}/common_nodes/{encoder}_{group_id}.csv", header=None)
			# df_common_node_id[[0, 1]] = np.sort(df_common_node_id[[0, 1]], axis=1)

			# Evaluation
			df_matching = df_common_node_id.merge(df_node_alignment_truth, on=[0, 1], how="inner")

			# Accuracy
			accuracy = len(df_matching) / len(df_node_alignment_truth)
			
			list_exp[len(encoders) * n_exp + j].append(accuracy)
			# list_accuracy.append(accuracy)
			# list_encoder.append(encoder)

	#---
	# Evaluation (based on PlanetAlign)
	#---

	# Get node embeddings
	dict_node_embeddings = {}
	for encoder in encoders:
		list_node_embeddings = []
		for group_id in groups_id:
			df_node_embeddings_concat = pd.read_csv(f"experiments/output/{exp}/node_embeddings/{encoder}_{group_id}.csv", dtype={"subgroup_id": "string"})
			# Id, 0, 1,	2, ..., subgroup_id

			for subgroup_id in subgroups_id[group_id]:
				df_node_embeddings = df_node_embeddings_concat[df_node_embeddings_concat["subgroup_id"] == subgroup_id]
				list_node_embeddings.append(df_node_embeddings)
		dict_node_embeddings[encoder] = list_node_embeddings

	# Evaluation
	# list_metrics = []

	df_node_alignment_truth_ = torch.tensor(df_node_alignment_truth.values)

	for j, encoder in enumerate(encoders):
		list_node_embeddings = dict_node_embeddings[encoder]
		# Id, 0, 1,	2, ..., subgroup_id

		emb1 = list_node_embeddings[0].iloc[:, 1:-1]
		emb2 = list_node_embeddings[1].iloc[:, 1:-1]

		emb1_ = torch.tensor(emb1.values)
		emb2_ = torch.tensor(emb2.values)

		# Similarity matrix
		# Option 1
		# S = pairwise_cosine_similarity(emb1_, emb2_)

		# Option 2
		""" S = cosine_similarity(emb1, emb2)
		S = torch.tensor(S) """

		# Option 3
		S = pairwise_distances(emb1, emb2, metric="euclidean")
		S = torch.tensor(S)
		S = -S # convert distances matrix to similarity matrix
		
		# Option 4
		""" S = torch.cdist(emb1_, emb2_, 2)
		S = -S # convert distances matrix to similarity matrix """

		hits = hits_ks_scores(S, df_node_alignment_truth_, mode="mean")
		mrr = mrr_score(S, df_node_alignment_truth_, mode="mean")
		print(encoder, hits, mrr)

		list_exp[len(encoders) * n_exp + j] += list(hits.values()) + [mrr]

0

Fitting model
GCNRes exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 422:  84%|████████▍ | 421/500 [00:39<00:07, 10.54it/s, Loss: 0.4015]

Stopping early as no improvement has been observed.
Early stopping at epoch 422
Fitting model
GIN exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 500: 100%|██████████| 500/500 [02:13<00:00,  3.75it/s, Loss: 0.3753]

Fitting model
GINE exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 500: 100%|██████████| 500/500 [02:24<00:00,  3.46it/s, Loss: 0.4358]

Fitting model
GCN exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 500: 100%|██████████| 500/500 [00:48<00:00, 10.41it/s, Loss: 0.4535]

Fitting model
GAT exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 350:  70%|██████▉   | 349/500 [01:04<00:27,  5.41it/s, Loss: 0.3816]

Stopping early as no improvement has been observed.
Early stopping at epoch 350
Fitting model
GATE exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 317:  63%|██████▎   | 316/500 [01:01<00:36,  5.10it/s, Loss: 0.3810]

Stopping early as no improvement has been observed.
Early stopping at epoch 317
GCNRes {1: 0.27549194544553757, 10: 0.5585867613554001, 30: 0.6838103830814362, 50: 0.730322003364563} 0.3728313148021698
GIN {1: 0.3720930218696594, 10: 0.643559917807579, 30: 0.7669946253299713, 50: 0.8161896169185638} 0.4631369262933731
GINE {1: 0.293381042778492, 10: 0.5536672621965408, 30: 0.683363139629364, 50: 0.7392665445804596} 0.37890709936618805
GCN {1: 0.25, 10: 0.5286225378513336, 30: 0.6677101850509644, 50: 0.7271914184093475} 0.34506766498088837
GAT {1: 0.2285330891609192, 10: 0.4521466940641403, 30: 0.5612701177597046, 50: 0.6055456250905991} 0.30208031088113785
GATE {1: 0.2553667202591896, 10: 0.4856887310743332, 30: 0.5983899831771851, 50: 0.6466905176639557} 0.33010953664779663
1
Fitting model
GCNRes exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 315:  63%|██████▎   | 314/500 [00:30<00:17, 10.38it/s, Loss: 0.4080]

Stopping early as no improvement has been observed.
Early stopping at epoch 315
Fitting model
GIN exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 345:  69%|██████▉   | 344/500 [01:31<00:41,  3.75it/s, Loss: 0.3792]

Stopping early as no improvement has been observed.
Early stopping at epoch 345
Fitting model
GINE exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 334:  67%|██████▋   | 333/500 [01:36<00:48,  3.45it/s, Loss: 0.4634]

Stopping early as no improvement has been observed.
Early stopping at epoch 334
Fitting model
GCN exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 359:  72%|███████▏  | 358/500 [00:34<00:13, 10.37it/s, Loss: 0.4425]

Stopping early as no improvement has been observed.
Early stopping at epoch 359
Fitting model
GAT exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 437:  87%|████████▋ | 436/500 [01:20<00:11,  5.42it/s, Loss: 0.3757]

Stopping early as no improvement has been observed.
Early stopping at epoch 437
Fitting model
GATE exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 388:  77%|███████▋  | 387/500 [01:15<00:22,  5.09it/s, Loss: 0.3780]

Stopping early as no improvement has been observed.
Early stopping at epoch 388
GCNRes {1: 0.273255817592144, 10: 0.5576923191547394, 30: 0.6855992674827576, 50: 0.7397137880325317} 0.3705652058124542
GIN {1: 0.3796958923339844, 10: 0.6444543898105621, 30: 0.7763864099979401, 50: 0.8251341581344604} 0.4710496515035629
GINE {1: 0.2607334479689598, 10: 0.5192307680845261, 30: 0.6556350588798523, 50: 0.717352420091629} 0.34620673954486847
GCN {1: 0.2473166286945343, 10: 0.5250447243452072, 30: 0.6721824705600739, 50: 0.7280858755111694} 0.3419524133205414
GAT {1: 0.246422179043293, 10: 0.4785330891609192, 30: 0.5961538404226303, 50: 0.6305903494358063} 0.32440412789583206
GATE {1: 0.22898032516241074, 10: 0.46556350588798523, 30: 0.5800536721944809, 50: 0.6305903494358063} 0.3076993599534035
2
Fitting model
GCNRes exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 294:  59%|█████▊    | 293/500 [00:28<00:19, 10.39it/s, Loss: 0.4109]

Stopping early as no improvement has been observed.
Early stopping at epoch 294
Fitting model
GIN exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 298:  59%|█████▉    | 297/500 [01:19<00:54,  3.75it/s, Loss: 0.3819]

Stopping early as no improvement has been observed.
Early stopping at epoch 298
Fitting model
GINE exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 436:  87%|████████▋ | 435/500 [02:05<00:18,  3.46it/s, Loss: 0.4405]

Stopping early as no improvement has been observed.
Early stopping at epoch 436
Fitting model
GCN exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 500: 100%|██████████| 500/500 [00:48<00:00, 10.39it/s, Loss: 0.4246]

Fitting model
GAT exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 315:  63%|██████▎   | 314/500 [00:57<00:34,  5.43it/s, Loss: 0.3820]

Stopping early as no improvement has been observed.
Early stopping at epoch 315
Fitting model
GATE exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 482:  96%|█████████▌| 481/500 [01:34<00:03,  5.09it/s, Loss: 0.3785]

Stopping early as no improvement has been observed.
Early stopping at epoch 482
GCNRes {1: 0.27280858159065247, 10: 0.5541144758462906, 30: 0.6811270117759705, 50: 0.7325581312179565} 0.3688468039035797
GIN {1: 0.3752236068248749, 10: 0.6346153914928436, 30: 0.7643112540245056, 50: 0.8206619024276733} 0.46314747631549835
GINE {1: 0.28220035135746, 10: 0.5371198654174805, 30: 0.6654740571975708, 50: 0.7245080471038818} 0.36512307822704315
GCN {1: 0.24865831434726715, 10: 0.5228085964918137, 30: 0.6672629714012146, 50: 0.7258497178554535} 0.34248024225234985
GAT {1: 0.2276386395096779, 10: 0.4633273631334305, 30: 0.5818425863981247, 50: 0.6211985647678375} 0.30765416473150253
GATE {1: 0.24060823023319244, 10: 0.4695885479450226, 30: 0.586762085556984, 50: 0.6288014501333237} 0.3163716271519661
3
Fitting model
GCNRes exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 404:  81%|████████  | 403/500 [00:38<00:09, 10.40it/s, Loss: 0.4085]

Stopping early as no improvement has been observed.
Early stopping at epoch 404
Fitting model
GIN exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 355:  71%|███████   | 354/500 [01:34<00:38,  3.75it/s, Loss: 0.3754]

Stopping early as no improvement has been observed.
Early stopping at epoch 355
Fitting model
GINE exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 500: 100%|██████████| 500/500 [02:24<00:00,  3.47it/s, Loss: 0.4277]

Fitting model
GCN exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 279:  56%|█████▌    | 278/500 [00:26<00:21, 10.36it/s, Loss: 0.4458]

Stopping early as no improvement has been observed.
Early stopping at epoch 279
Fitting model
GAT exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 359:  72%|███████▏  | 358/500 [01:06<00:26,  5.42it/s, Loss: 0.3800]

Stopping early as no improvement has been observed.
Early stopping at epoch 359
Fitting model
GATE exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 281:  56%|█████▌    | 280/500 [00:54<00:43,  5.10it/s, Loss: 0.3855]

Stopping early as no improvement has been observed.
Early stopping at epoch 281
GCNRes {1: 0.2848837152123451, 10: 0.5545617192983627, 30: 0.6824686825275421, 50: 0.7285330891609192} 0.37852054834365845
GIN {1: 0.3720930218696594, 10: 0.6395348757505417, 30: 0.768336296081543, 50: 0.8175312876701355} 0.46054360270500183
GINE {1: 0.2830948084592819, 10: 0.5420393645763397, 30: 0.6694991290569305, 50: 0.7222719192504883} 0.36879587173461914
GCN {1: 0.24776386469602585, 10: 0.5286225378513336, 30: 0.6699463427066803, 50: 0.7289803326129913} 0.34055760502815247
GAT {1: 0.2383720949292183, 10: 0.47898030281066895, 30: 0.5997316539287567, 50: 0.650715559720993} 0.32108350843191147
GATE {1: 0.2419499158859253, 10: 0.47719141840934753, 30: 0.5903398990631104, 50: 0.6328264772891998} 0.3191495016217232
4
Fitting model
GCNRes exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 347:  69%|██████▉   | 346/500 [00:33<00:14, 10.40it/s, Loss: 0.4224]

Stopping early as no improvement has been observed.
Early stopping at epoch 347
Fitting model
GIN exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 332:  66%|██████▌   | 331/500 [01:28<00:45,  3.75it/s, Loss: 0.3805]

Stopping early as no improvement has been observed.
Early stopping at epoch 332
Fitting model
GINE exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 472:  94%|█████████▍| 471/500 [02:18<00:08,  3.40it/s, Loss: 0.4501]

Stopping early as no improvement has been observed.
Early stopping at epoch 472
Fitting model
GCN exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 323:  64%|██████▍   | 322/500 [00:33<00:18,  9.56it/s, Loss: 0.4353]

Stopping early as no improvement has been observed.
Early stopping at epoch 323
Fitting model
GAT exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 285:  57%|█████▋    | 284/500 [00:54<00:41,  5.21it/s, Loss: 0.3877]

Stopping early as no improvement has been observed.
Early stopping at epoch 285
Fitting model
GATE exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 298:  59%|█████▉    | 297/500 [01:00<00:41,  4.88it/s, Loss: 0.3826]

Stopping early as no improvement has been observed.
Early stopping at epoch 298
GCNRes {1: 0.27370304614305496, 10: 0.566636860370636, 30: 0.6954382956027985, 50: 0.743291586637497} 0.3722268044948578
GIN {1: 0.3796958774328232, 10: 0.6457960605621338, 30: 0.7772808372974396, 50: 0.8175313174724579} 0.46956275403499603
GINE {1: 0.2804114446043968, 10: 0.5469588488340378, 30: 0.6762075126171112, 50: 0.7379248440265656} 0.3674219846725464
GCN {1: 0.24239713698625565, 10: 0.5295169800519943, 30: 0.6708407998085022, 50: 0.7298747897148132} 0.33899901807308197
GAT {1: 0.23881932348012924, 10: 0.47719143331050873, 30: 0.6015205532312393, 50: 0.6453488320112228} 0.31928853690624237
GATE {1: 0.226744182407856, 10: 0.45885510742664337, 30: 0.5697674453258514, 50: 0.6162790656089783} 0.30369362235069275
5
Fitting model
GCNRes exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 406:  81%|████████  | 405/500 [00:41<00:09,  9.69it/s, Loss: 0.4031]

Stopping early as no improvement has been observed.
Early stopping at epoch 406
Fitting model
GIN exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 374:  75%|███████▍  | 373/500 [01:40<00:34,  3.70it/s, Loss: 0.3795]

Stopping early as no improvement has been observed.
Early stopping at epoch 374
Fitting model
GINE exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 485:  97%|█████████▋| 484/500 [02:19<00:04,  3.46it/s, Loss: 0.4513]

Stopping early as no improvement has been observed.
Early stopping at epoch 485
Fitting model
GCN exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 500: 100%|██████████| 500/500 [00:47<00:00, 10.43it/s, Loss: 0.4278]

Fitting model
GAT exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 312:  62%|██████▏   | 311/500 [00:57<00:34,  5.42it/s, Loss: 0.3837]

Stopping early as no improvement has been observed.
Early stopping at epoch 312
Fitting model
GATE exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 278:  55%|█████▌    | 277/500 [00:54<00:43,  5.10it/s, Loss: 0.3848]

Stopping early as no improvement has been observed.
Early stopping at epoch 278
GCNRes {1: 0.27549195289611816, 10: 0.5545617192983627, 30: 0.6820214688777924, 50: 0.7254025042057037} 0.37321729958057404
GIN {1: 0.37835419178009033, 10: 0.6431127041578293, 30: 0.7822003364562988, 50: 0.8242397010326385} 0.46685388684272766
GINE {1: 0.26610017567873, 10: 0.5196779817342758, 30: 0.6533989310264587, 50: 0.7142218351364136} 0.35128098726272583
GCN {1: 0.2508944645524025, 10: 0.5232558250427246, 30: 0.6659212708473206, 50: 0.7222719192504883} 0.3452857583761215
GAT {1: 0.23345259577035904, 10: 0.4633273631334305, 30: 0.5822898000478745, 50: 0.6301431059837341} 0.3097710683941841
GATE {1: 0.23434704542160034, 10: 0.4704830050468445, 30: 0.5934704840183258, 50: 0.645348846912384} 0.3144524171948433
6
Fitting model
GCNRes exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 288:  57%|█████▋    | 287/500 [00:27<00:20, 10.41it/s, Loss: 0.4205]

Stopping early as no improvement has been observed.
Early stopping at epoch 288
Fitting model
GIN exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 416:  83%|████████▎ | 415/500 [01:50<00:22,  3.75it/s, Loss: 0.3790]

Stopping early as no improvement has been observed.
Early stopping at epoch 416
Fitting model
GINE exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 500: 100%|██████████| 500/500 [02:24<00:00,  3.46it/s, Loss: 0.4354]

Fitting model
GCN exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 488:  97%|█████████▋| 487/500 [00:46<00:01, 10.37it/s, Loss: 0.4393]

Stopping early as no improvement has been observed.
Early stopping at epoch 488
Fitting model
GAT exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 500: 100%|██████████| 500/500 [01:31<00:00,  5.44it/s, Loss: 0.3763]

Fitting model
GATE exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 470:  94%|█████████▍| 469/500 [01:32<00:06,  5.10it/s, Loss: 0.3796]

Stopping early as no improvement has been observed.
Early stopping at epoch 470
GCNRes {1: 0.26386404037475586, 10: 0.5684257596731186, 30: 0.6878354251384735, 50: 0.7401610016822815} 0.36394691467285156
GIN {1: 0.36806797981262207, 10: 0.6310375779867172, 30: 0.7687835395336151, 50: 0.8135062754154205} 0.45900997519493103
GINE {1: 0.27996423095464706, 10: 0.5357781797647476, 30: 0.6627906858921051, 50: 0.7236135900020599} 0.36672377586364746
GCN {1: 0.2500000074505806, 10: 0.5228085964918137, 30: 0.6699463427066803, 50: 0.7231663763523102} 0.34276337921619415
GAT {1: 0.23434704542160034, 10: 0.4633273631334305, 30: 0.5858676135540009, 50: 0.6314847767353058} 0.31230997294187546
GATE {1: 0.25223614275455475, 10: 0.466010719537735, 30: 0.5966010838747025, 50: 0.6413237899541855} 0.3267769068479538
7
Fitting model
GCNRes exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 485:  97%|█████████▋| 484/500 [00:46<00:01, 10.39it/s, Loss: 0.4023]

Stopping early as no improvement has been observed.
Early stopping at epoch 485
Fitting model
GIN exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 430:  86%|████████▌ | 429/500 [01:54<00:18,  3.74it/s, Loss: 0.3746]

Stopping early as no improvement has been observed.
Early stopping at epoch 430
Fitting model
GINE exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 387:  77%|███████▋  | 386/500 [01:51<00:32,  3.46it/s, Loss: 0.4560]

Stopping early as no improvement has been observed.
Early stopping at epoch 387
Fitting model
GCN exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 500: 100%|██████████| 500/500 [00:48<00:00, 10.40it/s, Loss: 0.4317]

Fitting model
GAT exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 368:  73%|███████▎  | 367/500 [01:07<00:24,  5.44it/s, Loss: 0.3829]

Stopping early as no improvement has been observed.
Early stopping at epoch 368
Fitting model
GATE exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 431:  86%|████████▌ | 430/500 [01:24<00:13,  5.10it/s, Loss: 0.3795]

Stopping early as no improvement has been observed.
Early stopping at epoch 431
GCNRes {1: 0.289803221821785, 10: 0.5621645599603653, 30: 0.6829158961772919, 50: 0.7307692468166351} 0.38334499299526215
GIN {1: 0.3729874789714813, 10: 0.6377459764480591, 30: 0.768336296081543, 50: 0.8170841038227081} 0.4633578658103943
GINE {1: 0.2652057260274887, 10: 0.5187835246324539, 30: 0.656976729631424, 50: 0.717352420091629} 0.3509138226509094
GCN {1: 0.25134167820215225, 10: 0.5241502672433853, 30: 0.6708407700061798, 50: 0.7254025042057037} 0.3444097340106964
GAT {1: 0.23076922446489334, 10: 0.45796065032482147, 30: 0.5943649411201477, 50: 0.6265652924776077} 0.30642150342464447
GATE {1: 0.22003577649593353, 10: 0.4619856923818588, 30: 0.5876565128564835, 50: 0.6292486637830734} 0.3012288361787796
8
Fitting model
GCNRes exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 424:  85%|████████▍ | 423/500 [00:40<00:07, 10.38it/s, Loss: 0.4072]

Stopping early as no improvement has been observed.
Early stopping at epoch 424
Fitting model
GIN exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 374:  75%|███████▍  | 373/500 [01:39<00:33,  3.75it/s, Loss: 0.3755]

Stopping early as no improvement has been observed.
Early stopping at epoch 374
Fitting model
GINE exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 500: 100%|██████████| 500/500 [02:24<00:00,  3.47it/s, Loss: 0.4329]

Fitting model
GCN exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 272:  54%|█████▍    | 271/500 [00:26<00:22, 10.38it/s, Loss: 0.4490]

Stopping early as no improvement has been observed.
Early stopping at epoch 272
Fitting model
GAT exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 333:  66%|██████▋   | 332/500 [01:01<00:30,  5.42it/s, Loss: 0.3880]

Stopping early as no improvement has been observed.
Early stopping at epoch 333
Fitting model
GATE exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 500: 100%|██████████| 500/500 [01:37<00:00,  5.11it/s, Loss: 0.3772]

GCNRes {1: 0.2839892655611038, 10: 0.5603756755590439, 30: 0.6824686825275421, 50: 0.7330053746700287} 0.3787339776754379
GIN {1: 0.37164580821990967, 10: 0.6332737058401108, 30: 0.7687835395336151, 50: 0.8076923191547394} 0.46026308834552765
GINE {1: 0.3166368529200554, 10: 0.5706619024276733, 30: 0.6887298822402954, 50: 0.7410554587841034} 0.4003170430660248
GCN {1: 0.24060823023319244, 10: 0.5237030535936356, 30: 0.6659213006496429, 50: 0.7258497178554535} 0.336276113986969
GAT {1: 0.23703041672706604, 10: 0.4767441898584366, 30: 0.5894454419612885, 50: 0.6413237899541855} 0.31726374477148056
GATE {1: 0.22406082600355148, 10: 0.44812165200710297, 30: 0.5742397010326385, 50: 0.6211985498666763} 0.3013870418071747
9
Fitting model
GCNRes exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 500: 100%|██████████| 500/500 [00:48<00:00, 10.41it/s, Loss: 0.4026]

Fitting model
GIN exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 403:  80%|████████  | 402/500 [01:47<00:26,  3.75it/s, Loss: 0.3802]

Stopping early as no improvement has been observed.
Early stopping at epoch 403
Fitting model
GINE exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 323:  64%|██████▍   | 322/500 [01:33<00:51,  3.45it/s, Loss: 0.4634]

Stopping early as no improvement has been observed.
Early stopping at epoch 323
Fitting model
GCN exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 363:  72%|███████▏  | 362/500 [00:34<00:13, 10.36it/s, Loss: 0.4392]

Stopping early as no improvement has been observed.
Early stopping at epoch 363
Fitting model
GAT exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 360:  72%|███████▏  | 359/500 [01:08<00:27,  5.20it/s, Loss: 0.3845]

Stopping early as no improvement has been observed.
Early stopping at epoch 360
Fitting model
GATE exp104 ['douban_1', 'douban_2'] 0.0001 500 538 512 2

Epoch: 324:  65%|██████▍   | 323/500 [01:05<00:36,  4.91it/s, Loss: 0.3819]

Stopping early as no improvement has been observed.
Early stopping at epoch 324
GCNRes {1: 0.28085867315530777, 10: 0.5608229041099548, 30: 0.677996426820755, 50: 0.7254025042057037} 0.3772132396697998
GIN {1: 0.37924864888191223, 10: 0.6475849747657776, 30: 0.7737030386924744, 50: 0.8188729882240295} 0.46715156733989716
GINE {1: 0.2661001831293106, 10: 0.5187835395336151, 30: 0.6578711867332458, 50: 0.7155635058879852} 0.34978561103343964
GCN {1: 0.24597495794296265, 10: 0.5299642086029053, 30: 0.6663685142993927, 50: 0.730322003364563} 0.3399896174669266
GAT {1: 0.2312164530158043, 10: 0.47182467579841614, 30: 0.5903399139642715, 50: 0.6310375779867172} 0.31097232550382614
GATE {1: 0.22271913290023804, 10: 0.4440966099500656, 30: 0.5670840889215469, 50: 0.6118068099021912} 0.29584281891584396

### Summary

In [21]:
list_exp

[['douban',
  'GCNRes',
  41.14593847002834,
  0.3220035778175313,
  0.27549194544553757,
  0.5585867613554001,
  0.6838103830814362,
  0.730322003364563,
  0.3728313148021698],
 ['douban',
  'GIN',
  134.58563818701077,
  0.4803220035778175,
  0.3720930218696594,
  0.643559917807579,
  0.7669946253299713,
  0.8161896169185638,
  0.4631369262933731],
 ['douban',
  'GINE',
  145.83719494903926,
  0.38372093023255816,
  0.293381042778492,
  0.5536672621965408,
  0.683363139629364,
  0.7392665445804596,
  0.37890709936618805],
 ['douban',
  'GCN',
  49.283824522048235,
  0.27280858676207514,
  0.25,
  0.5286225378513336,
  0.6677101850509644,
  0.7271914184093475,
  0.34506766498088837],
 ['douban',
  'GAT',
  65.86117903899867,
  0.3112701252236136,
  0.2285330891609192,
  0.4521466940641403,
  0.5612701177597046,
  0.6055456250905991,
  0.30208031088113785],
 ['douban',
  'GATE',
  63.26291971094906,
  0.3434704830053667,
  0.2553667202591896,
  0.4856887310743332,
  0.5983899831771851,
  0.6466905176639557,
  0.33010953664779663],
 ['douban',
  'GCNRes',
  31.522314138012007,
  0.315742397137746,
  0.273255817592144,
  0.5576923191547394,
  0.6855992674827576,
  0.7397137880325317,
  0.3705652058124542],
 ['douban',
  'GIN',
  93.16128183493856,
  0.4883720930232558,
  0.3796958923339844,
  0.6444543898105621,
  0.7763864099979401,
  0.8251341581344604,
  0.4710496515035629],
 ['douban',
  'GINE',
  97.69911717309151,
  0.33094812164579607,
  0.2607334479689598,
  0.5192307680845261,
  0.6556350588798523,
  0.717352420091629,
  0.34620673954486847],
 ['douban',
  'GCN',
  35.770540507975966,
  0.26565295169946335,
  0.2473166286945343,
  0.5250447243452072,
  0.6721824705600739,
  0.7280858755111694,
  0.3419524133205414],
 ['douban',
  'GAT',
  81.60719460202381,
  0.3282647584973166,
  0.246422179043293,
  0.4785330891609192,
  0.5961538404226303,
  0.6305903494358063,
  0.32440412789583206],
 ['douban',
  'GATE',
  77.3159135010792,
  0.3076923076923077,
  0.22898032516241074,
  0.46556350588798523,
  0.5800536721944809,
  0.6305903494358063,
  0.3076993599534035],
 ['douban',
  'GCNRes',
  29.44738344103098,
  0.3112701252236136,
  0.27280858159065247,
  0.5541144758462906,
  0.6811270117759705,
  0.7325581312179565,
  0.3688468039035797],
 ['douban',
  'GIN',
  80.59354053798597,
  0.4740608228980322,
  0.3752236068248749,
  0.6346153914928436,
  0.7643112540245056,
  0.8206619024276733,
  0.46314747631549835],
 ['douban',
  'GINE',
  127.24084780097473,
  0.35688729874776387,
  0.28220035135746,
  0.5371198654174805,
  0.6654740571975708,
  0.7245080471038818,
  0.36512307822704315],
 ['douban',
  'GCN',
  49.31771487998776,
  0.26565295169946335,
  0.24865831434726715,
  0.5228085964918137,
  0.6672629714012146,
  0.7258497178554535,
  0.34248024225234985],
 ['douban',
  'GAT',
  59.141835197922774,
  0.31753130590339895,
  0.2276386395096779,
  0.4633273631334305,
  0.5818425863981247,
  0.6211985647678375,
  0.30765416473150253],
 ['douban',
  'GATE',
  95.71639519301243,
  0.3363148479427549,
  0.24060823023319244,
  0.4695885479450226,
  0.586762085556984,
  0.6288014501333237,
  0.3163716271519661],
 ['douban',
  'GCNRes',
  40.027503510937095,
  0.32558139534883723,
  0.2848837152123451,
  0.5545617192983627,
  0.6824686825275421,
  0.7285330891609192,
  0.37852054834365845],
 ['douban',
  'GIN',
  95.81602980801836,
  0.4740608228980322,
  0.3720930218696594,
  0.6395348757505417,
  0.768336296081543,
  0.8175312876701355,
  0.46054360270500183],
 ['douban',
  'GINE',
  145.5066596189281,
  0.3685152057245081,
  0.2830948084592819,
  0.5420393645763397,
  0.6694991290569305,
  0.7222719192504883,
  0.36879587173461914],
 ['douban',
  'GCN',
  28.15905365801882,
  0.2692307692307692,
  0.24776386469602585,
  0.5286225378513336,
  0.6699463427066803,
  0.7289803326129913,
  0.34055760502815247],
 ['douban',
  'GAT',
  67.24456865200773,
  0.32021466905187834,
  0.2383720949292183,
  0.47898030281066895,
  0.5997316539287567,
  0.650715559720993,
  0.32108350843191147],
 ['douban',
  'GATE',
  56.36291240202263,
  0.32737030411449014,
  0.2419499158859253,
  0.47719141840934753,
  0.5903398990631104,
  0.6328264772891998,
  0.3191495016217232],
 ['douban',
  'GCNRes',
  34.47419836896006,
  0.31216457960644006,
  0.27370304614305496,
  0.566636860370636,
  0.6954382956027985,
  0.743291586637497,
  0.3722268044948578],
 ['douban',
  'GIN',
  89.63527378102299,
  0.49016100178890876,
  0.3796958774328232,
  0.6457960605621338,
  0.7772808372974396,
  0.8175313174724579,
  0.46956275403499603],
 ['douban',
  'GINE',
  140.5077504250221,
  0.3542039355992844,
  0.2804114446043968,
  0.5469588488340378,
  0.6762075126171112,
  0.7379248440265656,
  0.3674219846725464],
 ['douban',
  'GCN',
  35.23308474197984,
  0.26028622540250446,
  0.24239713698625565,
  0.5295169800519943,
  0.6708407998085022,
  0.7298747897148132,
  0.33899901807308197],
 ['douban',
  'GAT',
  56.32363300397992,
  0.32468694096601075,
  0.23881932348012924,
  0.47719143331050873,
  0.6015205532312393,
  0.6453488320112228,
  0.31928853690624237],
 ['douban',
  'GATE',
  62.544644698966295,
  0.3076923076923077,
  0.226744182407856,
  0.45885510742664337,
  0.5697674453258514,
  0.6162790656089783,
  0.30369362235069275],
 ['douban',
  'GCNRes',
  43.42078360798769,
  0.31216457960644006,
  0.27549195289611816,
  0.5545617192983627,
  0.6820214688777924,
  0.7254025042057037,
  0.37321729958057404],
 ['douban',
  'GIN',
  102.07362897193525,
  0.4874776386404293,
  0.37835419178009033,
  0.6431127041578293,
  0.7822003364562988,
  0.8242397010326385,
  0.46685388684272766],
 ['douban',
  'GINE',
  141.23094863910228,
  0.33989266547406083,
  0.26610017567873,
  0.5196779817342758,
  0.6533989310264587,
  0.7142218351364136,
  0.35128098726272583],
 ['douban',
  'GCN',
  49.18918947794009,
  0.2737030411449016,
  0.2508944645524025,
  0.5232558250427246,
  0.6659212708473206,
  0.7222719192504883,
  0.3452857583761215],
 ['douban',
  'GAT',
  58.70718479703646,
  0.315742397137746,
  0.23345259577035904,
  0.4633273631334305,
  0.5822898000478745,
  0.6301431059837341,
  0.3097710683941841],
 ['douban',
  'GATE',
  55.58866814500652,
  0.30590339892665475,
  0.23434704542160034,
  0.4704830050468445,
  0.5934704840183258,
  0.645348846912384,
  0.3144524171948433],
 ['douban',
  'GCNRes',
  28.997821904020384,
  0.3041144901610018,
  0.26386404037475586,
  0.5684257596731186,
  0.6878354251384735,
  0.7401610016822815,
  0.36394691467285156],
 ['douban',
  'GIN',
  112.10085244395304,
  0.47227191413237923,
  0.36806797981262207,
  0.6310375779867172,
  0.7687835395336151,
  0.8135062754154205,
  0.45900997519493103],
 ['douban',
  'GINE',
  145.83659301605076,
  0.35778175313059035,
  0.27996423095464706,
  0.5357781797647476,
  0.6627906858921051,
  0.7236135900020599,
  0.36672377586364746],
 ['douban',
  'GCN',
  48.19900579703972,
  0.2737030411449016,
  0.2500000074505806,
  0.5228085964918137,
  0.6699463427066803,
  0.7231663763523102,
  0.34276337921619415],
 ['douban',
  'GAT',
  93.26368343096692,
  0.32021466905187834,
  0.23434704542160034,
  0.4633273631334305,
  0.5858676135540009,
  0.6314847767353058,
  0.31230997294187546],
 ['douban',
  'GATE',
  93.2969895619899,
  0.34525939177101966,
  0.25223614275455475,
  0.466010719537735,
  0.5966010838747025,
  0.6413237899541855,
  0.3267769068479538],
 ['douban',
  'GCNRes',
  47.85518110205885,
  0.3282647584973166,
  0.289803221821785,
  0.5621645599603653,
  0.6829158961772919,
  0.7307692468166351,
  0.38334499299526215],
 ['douban',
  'GIN',
  115.86052292899694,
  0.47584973166368516,
  0.3729874789714813,
  0.6377459764480591,
  0.768336296081543,
  0.8170841038227081,
  0.4633578658103943],
 ['douban',
  'GINE',
  112.87722695292905,
  0.3372093023255814,
  0.2652057260274887,
  0.5187835246324539,
  0.656976729631424,
  0.717352420091629,
  0.3509138226509094],
 ['douban',
  'GCN',
  49.456520744017325,
  0.2737030411449016,
  0.25134167820215225,
  0.5241502672433853,
  0.6708407700061798,
  0.7254025042057037,
  0.3444097340106964],
 ['douban',
  'GAT',
  68.74688189500012,
  0.31216457960644006,
  0.23076922446489334,
  0.45796065032482147,
  0.5943649411201477,
  0.6265652924776077,
  0.30642150342464447],
 ['douban',
  'GATE',
  85.64109240402468,
  0.29338103756708406,
  0.22003577649593353,
  0.4619856923818588,
  0.5876565128564835,
  0.6292486637830734,
  0.3012288361787796],
 ['douban',
  'GCNRes',
  42.09196905500721,
  0.32558139534883723,
  0.2839892655611038,
  0.5603756755590439,
  0.6824686825275421,
  0.7330053746700287,
  0.3787339776754379],
 ['douban',
  'GIN',
  100.91351173701696,
  0.47227191413237923,
  0.37164580821990967,
  0.6332737058401108,
  0.7687835395336151,
  0.8076923191547394,
  0.46026308834552765],
 ['douban',
  'GINE',
  145.4466855879873,
  0.39803220035778175,
  0.3166368529200554,
  0.5706619024276733,
  0.6887298822402954,
  0.7410554587841034,
  0.4003170430660248],
 ['douban',
  'GCN',
  27.344524814048782,
  0.259391771019678,
  0.24060823023319244,
  0.5237030535936356,
  0.6659213006496429,
  0.7258497178554535,
  0.336276113986969],
 ['douban',
  'GAT',
  62.48131172906142,
  0.32558139534883723,
  0.23703041672706604,
  0.4767441898584366,
  0.5894454419612885,
  0.6413237899541855,
  0.31726374477148056],
 ['douban',
  'GATE',
  99.14092010795139,
  0.31216457960644006,
  0.22406082600355148,
  0.44812165200710297,
  0.5742397010326385,
  0.6211985498666763,
  0.3013870418071747],
 ['douban',
  'GCNRes',
  49.26177098497283,
  0.3211091234347048,
  0.28085867315530777,
  0.5608229041099548,
  0.677996426820755,
  0.7254025042057037,
  0.3772132396697998],
 ['douban',
  'GIN',
  108.52208957797848,
  0.4856887298747764,
  0.37924864888191223,
  0.6475849747657776,
  0.7737030386924744,
  0.8188729882240295,
  0.46715156733989716],
 ['douban',
  'GINE',
  94.49344547989313,
  0.33810375670840787,
  0.2661001831293106,
  0.5187835395336151,
  0.6578711867332458,
  0.7155635058879852,
  0.34978561103343964],
 ['douban',
  'GCN',
  36.172403858974576,
  0.26475849731663686,
  0.24597495794296265,
  0.5299642086029053,
  0.6663685142993927,
  0.730322003364563,
  0.3399896174669266],
 ['douban',
  'GAT',
  70.57091205602046,
  0.31216457960644006,
  0.2312164530158043,
  0.47182467579841614,
  0.5903399139642715,
  0.6310375779867172,
  0.31097232550382614],
 ['douban',
  'GATE',
  67.56853588100057,
  0.30143112701252234,
  0.22271913290023804,
  0.4440966099500656,
  0.5670840889215469,
  0.6118068099021912,
  0.29584281891584396]]

In [22]:
columns = ["Dataset", "Encoder", "Runtime", "Accuracy"] + [f"Hits@{k}" for k in list(hits.keys())] +  ["MRR"]
df_summary = pd.DataFrame(list_exp, columns=columns)
df_summary.sort_values(by=["Encoder"], inplace=True)
df_summary

,Dataset,Encoder,Runtime,Accuracy,Hits@1,Hits@10,Hits@30,Hits@50,MRR
16,douban,GAT,59.141835,0.317531,0.227639,0.463327,0.581843,0.621199,0.307654
22,douban,GAT,67.244569,0.320215,0.238372,0.478980,0.599732,0.650716,0.321084
52,douban,GAT,62.481312,0.325581,0.237030,0.476744,0.589445,0.641324,0.317264
4,douban,GAT,65.861179,0.311270,0.228533,0.452147,0.561270,0.605546,0.302080
46,douban,GAT,68.746882,0.312165,0.230769,0.457961,0.594365,0.626565,0.306422
28,douban,GAT,56.323633,0.324687,0.238819,0.477191,0.601521,0.645349,0.319289
40,douban,GAT,93.263683,0.320215,0.234347,0.463327,0.585868,0.631485,0.312310
58,douban,GAT,70.570912,0.312165,0.231216,0.471825,0.590340,0.631038,0.310972
34,douban,GAT,58.707185,0.315742,0.233453,0.463327,0.582290,0.630143,0.309771
10,douban,GAT,81.607195,0.328265,0.246422,0.478533,0.596154,0.630590,0.324404
23,douban,GATE,56.362912,0.327370,0.241950,0.477191,0.590340,0.632826,0.319150
29,douban,GATE,62.544645,0.307692,0.226744,0.458855,0.569767,0.616279,0.303694
41,douban,GATE,93.296990,0.345259,0.252236,0.466011,0.596601,0.641324,0.326777
47,douban,GATE,85.641092,0.293381,0.220036,0.461986,0.587657,0.629249,0.301229
53,douban,GATE,99.140920,0.312165,0.224061,0.448122,0.574240,0.621199,0.301387
17,douban,GATE,95.716395,0.336315,0.240608,0.469589,0.586762,0.628801,0.316372
35,douban,GATE,55.588668,0.305903,0.234347,0.470483,0.593470,0.645349,0.314452
59,douban,GATE,67.568536,0.301431,0.222719,0.444097,0.567084,0.611807,0.295843
5,douban,GATE,63.262920,0.343470,0.255367,0.485689,0.598390,0.646691,0.330110
11,douban,GATE,77.315914,0.307692,0.228980,0.465564,0.580054,0.630590,0.307699
45,douban,GCN,49.456521,0.273703,0.251342,0.524150,0.670841,0.725403,0.344410
57,douban,GCN,36.172404,0.264758,0.245975,0.529964,0.666369,0.730322,0.339990
33,douban,GCN,49.189189,0.273703,0.250894,0.523256,0.665921,0.722272,0.345286
21,douban,GCN,28.159054,0.269231,0.247764,0.528623,0.669946,0.728980,0.340558
51,douban,GCN,27.344525,0.259392,0.240608,0.523703,0.665921,0.725850,0.336276
15,douban,GCN,49.317715,0.265653,0.248658,0.522809,0.667263,0.725850,0.342480
3,douban,GCN,49.283825,0.272809,0.250000,0.528623,0.667710,0.727191,0.345068
9,douban,GCN,35.770541,0.265653,0.247317,0.525045,0.672182,0.728086,0.341952
27,douban,GCN,35.233085,0.260286,0.242397,0.529517,0.670841,0.729875,0.338999
39,douban,GCN,48.199006,0.273703,0.250000,0.522809,0.669946,0.723166,0.342763
18,douban,GCNRes,40.027504,0.325581,0.284884,0.554562,0.682469,0.728533,0.378521
42,douban,GCNRes,47.855181,0.328265,0.289803,0.562165,0.682916,0.730769,0.383345
48,douban,GCNRes,42.091969,0.325581,0.283989,0.560376,0.682469,0.733005,0.378734
54,douban,GCNRes,49.261771,0.321109,0.280859,0.560823,0.677996,0.725403,0.377213
6,douban,GCNRes,31.522314,0.315742,0.273256,0.557692,0.685599,0.739714,0.370565
36,douban,GCNRes,28.997822,0.304114,0.263864,0.568426,0.687835,0.740161,0.363947
0,douban,GCNRes,41.145938,0.322004,0.275492,0.558587,0.683810,0.730322,0.372831
30,douban,GCNRes,43.420784,0.312165,0.275492,0.554562,0.682021,0.725403,0.373217
12,douban,GCNRes,29.447383,0.311270,0.272809,0.554114,0.681127,0.732558,0.368847
24,douban,GCNRes,34.474198,0.312165,0.273703,0.566637,0.695438,0.743292,0.372227
37,douban,GIN,112.100852,0.472272,0.368068,0.631038,0.768784,0.813506,0.459010
19,douban,GIN,95.816030,0.474061,0.372093,0.639535,0.768336,0.817531,0.460544
55,douban,GIN,108.522090,0.485689,0.379249,0.647585,0.773703,0.818873,0.467152
1,douban,GIN,134.585638,0.480322,0.372093,0.643560,0.766995,0.816190,0.463137
49,douban,GIN,100.913512,0.472272,0.371646,0.633274,0.768784,0.807692,0.460263
25,douban,GIN,89.635274,0.490161,0.379696,0.645796,0.777281,0.817531,0.469563
13,douban,GIN,80.593541,0.474061,0.375224,0.634615,0.764311,0.820662,0.463147
43,douban,GIN,115.860523,0.475850,0.372987,0.637746,0.768336,0.817084,0.463358
7,douban,GIN,93.161282,0.488372,0.379696,0.644454,0.776386,0.825134,0.471050
31,douban,GIN,102.073629,0.487478,0.378354,0.643113,0.782200,0.824240,0.466854
44,douban,GINE,112.877227,0.337209,0.265206,0.518784,0.656977,0.717352,0.350914
8,douban,GINE,97.699117,0.330948,0.260733,0.519231,0.655635,0.717352,0.346207
50,douban,GINE,145.446686,0.398032,0.316637,0.570662,0.688730,0.741055,0.400317
14,douban,GINE,127.240848,0.356887,0.282200,0.537120,0.665474,0.724508,0.365123
2,douban,GINE,145.837195,0.383721,0.293381,0.553667,0.683363,0.739267,0.378907
20,douban,GINE,145.506660,0.368515,0.283095,0.542039,0.669499,0.722272,0.368796
56,douban,GINE,94.493445,0.338104,0.266100,0.518784,0.657871,0.715564,0.349786
32,douban,GINE,141.230949,0.339893,0.266100,0.519678,0.653399,0.714222,0.351281
26,douban,GINE,140.507750,0.354204,0.280411,0.546959,0.676208,0.737925,0.367422
38,douban,GINE,145.836593,0.357782,0.279964,0.535778,0.662791,0.723614,0.366724

In [23]:
df_text = df_summary.map(lambda x: f"{x}".replace(".", ","))
df_text

,Dataset,Encoder,Runtime,Accuracy,Hits@1,Hits@10,Hits@30,Hits@50,MRR
16,douban,GAT,"59,141835197922774","0,31753130590339895","0,2276386395096779","0,4633273631334305","0,5818425863981247","0,6211985647678375","0,30765416473150253"
22,douban,GAT,"67,24456865200773","0,32021466905187834","0,2383720949292183","0,47898030281066895","0,5997316539287567","0,650715559720993","0,32108350843191147"
52,douban,GAT,"62,48131172906142","0,32558139534883723","0,23703041672706604","0,4767441898584366","0,5894454419612885","0,6413237899541855","0,31726374477148056"
4,douban,GAT,"65,86117903899867","0,3112701252236136","0,2285330891609192","0,4521466940641403","0,5612701177597046","0,6055456250905991","0,30208031088113785"
46,douban,GAT,"68,74688189500012","0,31216457960644006","0,23076922446489334","0,45796065032482147","0,5943649411201477","0,6265652924776077","0,30642150342464447"
28,douban,GAT,"56,32363300397992","0,32468694096601075","0,23881932348012924","0,47719143331050873","0,6015205532312393","0,6453488320112228","0,31928853690624237"
40,douban,GAT,"93,26368343096692","0,32021466905187834","0,23434704542160034","0,4633273631334305","0,5858676135540009","0,6314847767353058","0,31230997294187546"
58,douban,GAT,"70,57091205602046","0,31216457960644006","0,2312164530158043","0,47182467579841614","0,5903399139642715","0,6310375779867172","0,31097232550382614"
34,douban,GAT,"58,70718479703646","0,315742397137746","0,23345259577035904","0,4633273631334305","0,5822898000478745","0,6301431059837341","0,3097710683941841"
10,douban,GAT,"81,60719460202381","0,3282647584973166","0,246422179043293","0,4785330891609192","0,5961538404226303","0,6305903494358063","0,32440412789583206"
23,douban,GATE,"56,36291240202263","0,32737030411449014","0,2419499158859253","0,47719141840934753","0,5903398990631104","0,6328264772891998","0,3191495016217232"
29,douban,GATE,"62,544644698966295","0,3076923076923077","0,226744182407856","0,45885510742664337","0,5697674453258514","0,6162790656089783","0,30369362235069275"
41,douban,GATE,"93,2969895619899","0,34525939177101966","0,25223614275455475","0,466010719537735","0,5966010838747025","0,6413237899541855","0,3267769068479538"
47,douban,GATE,"85,64109240402468","0,29338103756708406","0,22003577649593353","0,4619856923818588","0,5876565128564835","0,6292486637830734","0,3012288361787796"
53,douban,GATE,"99,14092010795139","0,31216457960644006","0,22406082600355148","0,44812165200710297","0,5742397010326385","0,6211985498666763","0,3013870418071747"
17,douban,GATE,"95,71639519301243","0,3363148479427549","0,24060823023319244","0,4695885479450226","0,586762085556984","0,6288014501333237","0,3163716271519661"
35,douban,GATE,"55,58866814500652","0,30590339892665475","0,23434704542160034","0,4704830050468445","0,5934704840183258","0,645348846912384","0,3144524171948433"
59,douban,GATE,"67,56853588100057","0,30143112701252234","0,22271913290023804","0,4440966099500656","0,5670840889215469","0,6118068099021912","0,29584281891584396"
5,douban,GATE,"63,26291971094906","0,3434704830053667","0,2553667202591896","0,4856887310743332","0,5983899831771851","0,6466905176639557","0,33010953664779663"
11,douban,GATE,"77,3159135010792","0,3076923076923077","0,22898032516241074","0,46556350588798523","0,5800536721944809","0,6305903494358063","0,3076993599534035"
45,douban,GCN,"49,456520744017325","0,2737030411449016","0,25134167820215225","0,5241502672433853","0,6708407700061798","0,7254025042057037","0,3444097340106964"
57,douban,GCN,"36,172403858974576","0,26475849731663686","0,24597495794296265","0,5299642086029053","0,6663685142993927","0,730322003364563","0,3399896174669266"
33,douban,GCN,"49,18918947794009","0,2737030411449016","0,2508944645524025","0,5232558250427246","0,6659212708473206","0,7222719192504883","0,3452857583761215"
21,douban,GCN,"28,15905365801882","0,2692307692307692","0,24776386469602585","0,5286225378513336","0,6699463427066803","0,7289803326129913","0,34055760502815247"
51,douban,GCN,"27,344524814048782","0,259391771019678","0,24060823023319244","0,5237030535936356","0,6659213006496429","0,7258497178554535","0,336276113986969"
15,douban,GCN,"49,31771487998776","0,26565295169946335","0,24865831434726715","0,5228085964918137","0,6672629714012146","0,7258497178554535","0,34248024225234985"
3,douban,GCN,"49,283824522048235","0,27280858676207514","0,25","0,5286225378513336","0,6677101850509644","0,7271914184093475","0,34506766498088837"
9,douban,GCN,"35,770540507975966","0,26565295169946335","0,2473166286945343","0,5250447243452072","0,6721824705600739","0,7280858755111694","0,3419524133205414"
27,douban,GCN,"35,23308474197984","0,26028622540250446","0,24239713698625565","0,5295169800519943","0,6708407998085022","0,7298747897148132","0,33899901807308197"
39,douban,GCN,"48,19900579703972","0,2737030411449016","0,2500000074505806","0,5228085964918137","0,6699463427066803","0,7231663763523102","0,34276337921619415"
18,douban,GCNRes,"40,027503510937095","0,32558139534883723","0,2848837152123451","0,5545617192983627","0,6824686825275421","0,7285330891609192","0,37852054834365845"
42,douban,GCNRes,"47,85518110205885","0,3282647584973166","0,289803221821785","0,5621645599603653","0,6829158961772919","0,7307692468166351","0,38334499299526215"
48,douban,GCNRes,"42,09196905500721","0,32558139534883723","0,2839892655611038","0,5603756755590439","0,6824686825275421","0,7330053746700287","0,3787339776754379"
54,douban,GCNRes,"49,26177098497283","0,3211091234347048","0,28085867315530777","0,5608229041099548","0,677996426820755","0,7254025042057037","0,3772132396697998"
6,douban,GCNRes,"31,522314138012007","0,315742397137746","0,273255817592144","0,5576923191547394","0,6855992674827576","0,7397137880325317","0,3705652058124542"
36,douban,GCNRes,"28,997821904020384","0,3041144901610018","0,26386404037475586","0,5684257596731186","0,6878354251384735","0,7401610016822815","0,36394691467285156"
0,douban,GCNRes,"41,14593847002834","0,3220035778175313","0,27549194544553757","0,5585867613554001","0,6838103830814362","0,730322003364563","0,3728313148021698"
30,douban,GCNRes,"43,42078360798769","0,31216457960644006","0,27549195289611816","0,5545617192983627","0,6820214688777924","0,7254025042057037","0,37321729958057404"
12,douban,GCNRes,"29,44738344103098","0,3112701252236136","0,27280858159065247","0,5541144758462906","0,6811270117759705","0,7325581312179565","0,3688468039035797"
24,douban,GCNRes,"34,47419836896006","0,31216457960644006","0,27370304614305496","0,566636860370636","0,6954382956027985","0,743291586637497","0,3722268044948578"
37,douban,GIN,"112,10085244395304","0,47227191413237923","0,36806797981262207","0,6310375779867172","0,7687835395336151","0,8135062754154205","0,45900997519493103"
19,douban,GIN,"95,81602980801836","0,4740608228980322","0,3720930218696594","0,6395348757505417","0,768336296081543","0,8175312876701355","0,46054360270500183"
55,douban,GIN,"108,52208957797848","0,4856887298747764","0,37924864888191223","0,6475849747657776","0,7737030386924744","0,8188729882240295","0,46715156733989716"
1,douban,GIN,"134,58563818701077","0,4803220035778175","0,3720930218696594","0,643559917807579","0,7669946253299713","0,8161896169185638","0,4631369262933731"
49,douban,GIN,"100,91351173701696","0,47227191413237923","0,37164580821990967","0,6332737058401108","0,7687835395336151","0,8076923191547394","0,46026308834552765"
25,douban,GIN,"89,63527378102299","0,49016100178890876","0,3796958774328232","0,6457960605621338","0,7772808372974396","0,8175313174724579","0,46956275403499603"
13,douban,GIN,"80,59354053798597","0,4740608228980322","0,3752236068248749","0,6346153914928436","0,7643112540245056","0,8206619024276733","0,46314747631549835"
43,douban,GIN,"115,86052292899694","0,47584973166368516","0,3729874789714813","0,6377459764480591","0,768336296081543","0,8170841038227081","0,4633578658103943"
7,douban,GIN,"93,16128183493856","0,4883720930232558","0,3796958923339844","0,6444543898105621","0,7763864099979401","0,8251341581344604","0,4710496515035629"
31,douban,GIN,"102,07362897193525","0,4874776386404293","0,37835419178009033","0,6431127041578293","0,7822003364562988","0,8242397010326385","0,46685388684272766"
44,douban,GINE,"112,87722695292905","0,3372093023255814","0,2652057260274887","0,5187835246324539","0,656976729631424","0,717352420091629","0,3509138226509094"
8,douban,GINE,"97,69911717309151","0,33094812164579607","0,2607334479689598","0,5192307680845261","0,6556350588798523","0,717352420091629","0,34620673954486847"
50,douban,GINE,"145,4466855879873","0,39803220035778175","0,3166368529200554","0,5706619024276733","0,6887298822402954","0,7410554587841034","0,4003170430660248"
14,douban,GINE,"127,24084780097473","0,35688729874776387","0,28220035135746","0,5371198654174805","0,6654740571975708","0,7245080471038818","0,36512307822704315"
2,douban,GINE,"145,83719494903926","0,38372093023255816","0,293381042778492","0,5536672621965408","0,683363139629364","0,7392665445804596","0,37890709936618805"
20,douban,GINE,"145,5066596189281","0,3685152057245081","0,2830948084592819","0,5420393645763397","0,6694991290569305","0,7222719192504883","0,36879587173461914"
56,douban,GINE,"94,49344547989313","0,33810375670840787","0,2661001831293106","0,5187835395336151","0,6578711867332458","0,7155635058879852","0,34978561103343964"
32,douban,GINE,"141,23094863910228","0,33989266547406083","0,26610017567873","0,5196779817342758","0,6533989310264587","0,7142218351364136","0,35128098726272583"
26,douban,GINE,"140,5077504250221","0,3542039355992844","0,2804114446043968","0,5469588488340378","0,6762075126171112","0,7379248440265656","0,3674219846725464"
38,douban,GINE,"145,83659301605076","0,35778175313059035","0,27996423095464706","0,5357781797647476","0,6627906858921051","0,7236135900020599","0,36672377586364746"

In [24]:
print(NUM_HIDDEN_LAYERS)
print(HIDDEN_DIM)
print(output_feature_size)

12
[1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024]
512