In [1]:
# Torch version
!python -c "import torch; print(torch.__version__)"

# Cuda version
!python -c "import torch; print(torch.version.cuda)"

2.6.0+cu124
12.4

In [2]:
from model_PyG import *
from utils import *

In [3]:
import json
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
import torch_geometric.transforms as T
import os
import umap

from mpl_toolkits.mplot3d import Axes3D
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from sklearn.metrics import silhouette_score
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler
from torch_geometric.data import InMemoryDataset, Data
from torch_geometric.utils import dense_to_sparse, negative_sampling
from torch.nn.functional import binary_cross_entropy_with_logits
from torch.optim import Adam

In [4]:
import torch_geometric
print(torch_geometric.__version__)

2.7.0

### Utils

In [5]:
def info(data):
	print("Validate:\t {}".format(data.validate(raise_on_error=True)))
	print("Num. nodes:\t {}".format(data.num_nodes))
	print("Num. edges:\t {}".format(data.num_edges))
	print("Num. features:\t {}".format(data.num_node_features))
	print("Has isolated:\t {}".format(data.has_isolated_nodes()))
	print("Has loops:\t {}".format(data.has_self_loops()))
	print("Is directed:\t {}".format(data.is_directed()))
	print("Is undirected:\t {}".format(data.is_undirected()))
	print("{}".format(data.edge_index))
	print("{}".format(data.x))
	print("{}".format(data.edge_attr))

def compute_num_neg_samples(edge_index, num_nodes, ratio):
	E = edge_index.size(1)
	max_neg = num_nodes * num_nodes - E
	return min(int(ratio * E), max_neg)

def neg_ratio_schedule(epoch, max_epoch):
	start = 5.0
	end = 1.0
	return start - (start - end) * (epoch / max_epoch)

class EarlyStopping:
	def __init__(self, patience=5, delta=0, warmup=5, verbose=False):
		self.patience = patience
		self.delta = delta
		self.warmup = warmup
		self.verbose = verbose
		self.best_loss = None
		self.no_improvement_count = 0
		self.stop_training = False
	
	def check_early_stop(self, loss, epoch):
		if epoch >= self.warmup:
			if self.best_loss is None or loss < self.best_loss - self.delta:
				self.best_loss = loss
				self.no_improvement_count = 0
			else:
				self.no_improvement_count += 1
				if self.no_improvement_count >= self.patience:
					self.stop_training = True
					if self.verbose:
						print("Stopping early as no improvement has been observed.")

### Parameters

In [6]:
file = open("exp.json")
experiment = json.load(file)
exp = experiment["exp"] # experiment["exp"] # Change to static, e.g. "exp1"

file = open("experiments/output/{}/parameters.json".format(exp))
params = json.load(file)

print("Exp:\t\t", exp)

raw_data_file = params["raw_data_file"]
print("Raw data:\t", raw_data_file)

methods = params["methods"]
print("Methods:\t", methods)

apply_transformation = params["apply_transformation"]
print("Apply transformation:", apply_transformation)

dimension = params["dimension"]
print("Dimension:\t", dimension)

groups_id = params["groups_id"]
print("Groups id:\t", groups_id)

subgroups_id = params["subgroups_id"]
print("Subgroups id:\t", subgroups_id)

encoders = ["GCNRes", "GCN", "GIN", "GINE"]

Exp:		 exp112
Raw data:	 Vanessa_september_2br_10ar_format
Methods:	 ['t-gae']
Apply transformation: True
Dimension:	 128
Groups id:	 ['SecoAmazonas', 'SecoSanMartin', 'SecoCusco', 'FrescoAmazonas', 'FrescoSanMartin', 'FrescoCusco']
Subgroups id:	 {'SecoAmazonas': ['1', '2'], 'SecoSanMartin': ['1', '2'], 'SecoCusco': ['1', '2'], 'FrescoAmazonas': ['1', '2'], 'FrescoSanMartin': ['1', '2'], 'FrescoCusco': ['1', '2']}

In [7]:
# Remove
# groups_id = ["LSNB", "BC", "RCC", "BPH", "PD"] # "OSA" Memory issue
# groups_id = ["AR", "Health", "CKD-Mild", "CKD-Severe", "LPRD"]

### Similarity analysis (KNN)

In [8]:
groups_id, subgroups_id

(['SecoAmazonas',
  'SecoSanMartin',
  'SecoCusco',
  'FrescoAmazonas',
  'FrescoSanMartin',
  'FrescoCusco'],
 {'SecoAmazonas': ['1', '2'],
  'SecoSanMartin': ['1', '2'],
  'SecoCusco': ['1', '2'],
  'FrescoAmazonas': ['1', '2'],
  'FrescoSanMartin': ['1', '2'],
  'FrescoCusco': ['1', '2']})

In [9]:
k = 1 # Change

for encoder in encoders:
	for group_id in groups_id:
		df_node_embeddings_concat = pd.read_csv(f"experiments/output/{exp}/node_embeddings/{encoder}_{group_id}.csv", dtype={"subgroup_id": "string"})
		# Id, 0, 1,	2, ..., subgroup_id

		subgroups_id_ = subgroups_id[group_id]
		print(subgroups_id_, len(subgroups_id_))

		# Calculate distance matrix (KNN)
		knn = NearestNeighbors(n_neighbors=k, metric="euclidean")

		df_node_embeddings = df_node_embeddings_concat[df_node_embeddings_concat["subgroup_id"] == subgroups_id_[0]]
		x = df_node_embeddings.iloc[:, 1:-1].values

		df_node_alignment = pd.DataFrame()
		df_node_alignment[f"{group_id}_{subgroups_id_[0]}"] = df_node_embeddings["Id"].values

		for subgroup_id in subgroups_id_[1:]:
			df_node_embeddings = df_node_embeddings_concat[df_node_embeddings_concat["subgroup_id"] == subgroup_id]
			y = df_node_embeddings.iloc[:, 1:-1].values

			knn.fit(y)
			distances, indices = knn.kneighbors(x)
			indices = indices.squeeze() # (N,)

			df_node_alignment[f"{group_id}_{subgroup_id}"] = df_node_embeddings["Id"].values[indices]
			
			""" df_node_alignment[f"distances"] = distances
			avg_distances = df_node_alignment["distances"].mean()
			df_node_alignment = df_node_alignment[df_node_alignment["distances"] <= avg_distances].iloc[:, :-1]
			df_node_alignment """
		
		# Find node alignment for all datasets
		df_node_alignment_filter = df_node_alignment[df_node_alignment.nunique(axis=1) == 1]
		# print(len(df_node_alignment_filter))
		# display(df_node_alignment_filter)
		print(f"{encoder}-{group_id}: {len(df_node_alignment_filter)}")

		# Save common node id as .
		# common_node_id = df_node_alignment_filter.iloc[:, 0].values
		# np.save(f"experiments/output/{exp}/common_nodes/{encoder}_{group_id}.npy", np.array(common_node_id))

		# Save common node id as .csv
		df_common_node_id = df_node_alignment_filter.iloc[:, [0]].copy()
		df_common_node_id.sort_values(by=df_common_node_id.columns[0], inplace=True)
		df_common_node_id.to_csv(f"experiments/output/{exp}/common_nodes/{encoder}_{group_id}.csv", index=False, header=False)

['1', '2'] 2
GCNRes-SecoAmazonas: 38
['1', '2'] 2
GCNRes-SecoSanMartin: 27
['1', '2'] 2
GCNRes-SecoCusco: 49
['1', '2'] 2
GCNRes-FrescoAmazonas: 23
['1', '2'] 2
GCNRes-FrescoSanMartin: 38
['1', '2'] 2
GCNRes-FrescoCusco: 47
['1', '2'] 2
GCN-SecoAmazonas: 29
['1', '2'] 2
GCN-SecoSanMartin: 29
['1', '2'] 2
GCN-SecoCusco: 25
['1', '2'] 2
GCN-FrescoAmazonas: 26
['1', '2'] 2
GCN-FrescoSanMartin: 31
['1', '2'] 2
GCN-FrescoCusco: 45
['1', '2'] 2
GIN-SecoAmazonas: 23
['1', '2'] 2
GIN-SecoSanMartin: 15
['1', '2'] 2
GIN-SecoCusco: 22
['1', '2'] 2
GIN-FrescoAmazonas: 21
['1', '2'] 2
GIN-FrescoSanMartin: 23
['1', '2'] 2
GIN-FrescoCusco: 37
['1', '2'] 2
GINE-SecoAmazonas: 14
['1', '2'] 2
GINE-SecoSanMartin: 17
['1', '2'] 2
GINE-SecoCusco: 26
['1', '2'] 2
GINE-FrescoAmazonas: 18
['1', '2'] 2
GINE-FrescoSanMartin: 27
['1', '2'] 2
GINE-FrescoCusco: 27

In [10]:
df_common_node_id

      FrescoCusco_1
12               52
609              61
1276             98
1334            115
31              149
49              239
1340            285
552             382
727             496
817             544
1424            603
563             619
1555            676
1528            680
1169            692
568             739
366             789
1538            795
1183           1181
1068           1211
1405           1259
510            1296
513            1332
521            1376
1136           1411
1196           1515
257            1556

In [11]:
df_node_alignment_filter

      FrescoCusco_1  FrescoCusco_2
12               52             52
31              149            149
49              239            239
257            1556           1556
366             789            789
510            1296           1296
513            1332           1332
521            1376           1376
552             382            382
563             619            619
568             739            739
609              61             61
727             496            496
817             544            544
1068           1211           1211
1136           1411           1411
1169            692            692
1183           1181           1181
1196           1515           1515
1276             98             98
1334            115            115
1340            285            285
1405           1259           1259
1424            603            603
1528            680            680
1538            795            795
1555            676            676

In [12]:
# Intersection and Union
list_common_node_id = []
for encoder in encoders:
	for group_id in groups_id:
		# Read common node
		# common_node_id = np.load(f"experiments/output/{exp}/common_nodes/{encoder}_{group_id}.npy")
		try:
			common_node_id = pd.read_csv(f"experiments/output/{exp}/common_nodes/{encoder}_{group_id}.csv", header=None)
			list_common_node_id.append(common_node_id[0].to_numpy())
		except:
			print("Error")

	common_node_id_union = list(set.union(*map(set, list_common_node_id)))
	common_node_id_intersection = list(set.intersection(*map(set, list_common_node_id)))
	print(f"{encoder}-union: {len(common_node_id_union)}")
	print(f"{encoder}-intersection: {len(common_node_id_intersection)}")

	# Save common node id
	# np.save(f"experiments/output/{exp}/common_nodes/{encoder}_union.npy", np.array(common_node_id_union))
	# np.save(f"experiments/output/{exp}/common_nodes/{encoder}_intersection.npy", np.array(common_node_id_intersection))

	df_common_node_id_union = pd.DataFrame(common_node_id_union)
	df_common_node_id_union.sort_values(by=df_common_node_id_union.columns[0], inplace=True)
	df_common_node_id_intersection = pd.DataFrame(common_node_id_intersection)
	if len(df_common_node_id_intersection) > 0:
		df_common_node_id_intersection.sort_values(by=df_common_node_id_intersection.columns[0], inplace=True)

	df_common_node_id_union.to_csv(f"experiments/output/{exp}/common_nodes/{encoder}_union.csv", index=False, header=False)
	df_common_node_id_intersection.to_csv(f"experiments/output/{exp}/common_nodes/{encoder}_intersection.csv", index=False, header=False)

GCNRes-union: 190
GCNRes-intersection: 1
GCN-union: 247
GCN-intersection: 1
GIN-union: 293
GIN-intersection: 1
GINE-union: 339
GINE-intersection: 1

In [13]:
df_common_node_id_union

        0
0       4
1       5
3       7
4      11
6      19
..    ...
230  1558
231  1559
234  1560
236  1565
238  1566

[339 rows x 1 columns]

In [14]:
df_node_alignment

      FrescoCusco_1  FrescoCusco_2
0                 1             43
1                 3             25
2                11            626
3                12            108
4                15            186
...             ...            ...
1565           1032            909
1566            420            676
1567            389            506
1568            690           1029
1569            419            600

[1570 rows x 2 columns]

### Similary analysis (Hungarian)

In [15]:
import math
import torch
from scipy.optimize import linear_sum_assignment


def sinkhorn_similarity(sim, tau=0.05, n_iter=20):
    """Log-domain Sinkhorn normalization of a similarity matrix [N1, N2] (soft assignment, in log space)."""
    n1, n2 = sim.shape
    log_p = sim / tau
    for _ in range(n_iter):
        log_p = log_p - torch.logsumexp(log_p, dim=1, keepdim=True) - math.log(n1)   # rows sum to 1/N1
        log_p = log_p - torch.logsumexp(log_p, dim=0, keepdim=True) - math.log(n2)   # columns sum to 1/N2
    return log_p        # higher = more likely; usable directly with hits_ks_scores / mrr_score

def hungarian_matching(sim, min_sim=None):
    """One-to-one assignment maximizing total similarity (rectangular matrices are fine)."""
    s = sim.cpu().numpy()
    r, c = linear_sum_assignment(-s)
    if min_sim is not None:                       # reject weak matches (partial overlap)
        keep = s[r, c] >= min_sim
        r, c = r[keep], c[keep]
    return r, c

In [16]:
def _mean_topk(a, b, k, chunk=2048):
	"""Para cada fila de a: media de las k mayores similitudes coseno con las filas de b."""
	out = []
	for i in range(0, a.size(0), chunk):
		out.append((a[i:i + chunk] @ b.T).topk(k, dim=1).values.mean(dim=1))
	return torch.cat(out)

@torch.no_grad()
def similarity_matrix(z1, z2, retrieval="cosine", csls_k=None):
    """Full similarity matrix [N1, N2] (higher = more similar), as PlanetAlign expects."""
    if retrieval == "cosine":
        a, b = F.normalize(z1, dim=1), F.normalize(z2, dim=1)
        sim = a @ b.T
        if csls_k:
            r_s = _mean_topk(a, b, csls_k)
            r_t = _mean_topk(b, a, csls_k)
            sim = 2 * sim - r_s.unsqueeze(1) - r_t.unsqueeze(0)
        return sim
    if retrieval == "l2":
        if csls_k:
            raise ValueError("csls_k is only supported with retrieval='cosine'")
        return -torch.cdist(z1, z2)  # distances -> similarities
    raise ValueError("retrieval must be 'cosine' or 'l2'")

In [17]:
# For cosine and L2

for retrieval in ["cosine", "l2"]:
	for encoder in encoders:
		for group_id in groups_id:
			print(encoder, group_id, retrieval)
			df_node_embeddings_concat = pd.read_csv(f"experiments/output/{exp}/node_embeddings/{encoder}_{group_id}.csv", dtype={"subgroup_id": "string"})
			# Id, 0, 1,	2, ..., subgroup_id

			df_node_embeddings1 = df_node_embeddings_concat[df_node_embeddings_concat["subgroup_id"] == "1"]
			df_node_embeddings2 = df_node_embeddings_concat[df_node_embeddings_concat["subgroup_id"] == "2"]

			z1 = df_node_embeddings1.iloc[:, 1:-1].values
			z2 = df_node_embeddings2.iloc[:, 1:-1].values

			sim = similarity_matrix(torch.tensor(z1), torch.tensor(z2), retrieval=retrieval, csls_k=None)
			match = hungarian_matching(sim, min_sim=None)

			list_1 = df_node_embeddings1.iloc[match[0]]["Id"].values
			list_2 = df_node_embeddings2.iloc[match[1]]["Id"].values

			df_node_alignment = pd.DataFrame([list_1, list_2])
			df_node_alignment= df_node_alignment.T

			df_node_alignment_filter = df_node_alignment[df_node_alignment.nunique(axis=1) == 1]

			# Save common node id as .csv
			df_common_node_id = df_node_alignment_filter.iloc[:, [0]].copy()
			df_common_node_id.sort_values(by=df_common_node_id.columns[0], inplace=True)
			df_common_node_id.to_csv(f"experiments/output/{exp}/common_nodes/{encoder}_{group_id}_{retrieval}.csv", index=False, header=False)

GCNRes SecoAmazonas cosine

GCNRes SecoSanMartin cosine
GCNRes SecoCusco cosine
GCNRes FrescoAmazonas cosine
GCNRes FrescoSanMartin cosine
GCNRes FrescoCusco cosine
GCN SecoAmazonas cosine
GCN SecoSanMartin cosine
GCN SecoCusco cosine
GCN FrescoAmazonas cosine
GCN FrescoSanMartin cosine
GCN FrescoCusco cosine
GIN SecoAmazonas cosine
GIN SecoSanMartin cosine
GIN SecoCusco cosine
GIN FrescoAmazonas cosine
GIN FrescoSanMartin cosine
GIN FrescoCusco cosine
GINE SecoAmazonas cosine
GINE SecoSanMartin cosine
GINE SecoCusco cosine
GINE FrescoAmazonas cosine
GINE FrescoSanMartin cosine
GINE FrescoCusco cosine
GCNRes SecoAmazonas l2
GCNRes SecoSanMartin l2
GCNRes SecoCusco l2
GCNRes FrescoAmazonas l2
GCNRes FrescoSanMartin l2
GCNRes FrescoCusco l2
GCN SecoAmazonas l2
GCN SecoSanMartin l2
GCN SecoCusco l2
GCN FrescoAmazonas l2
GCN FrescoSanMartin l2
GCN FrescoCusco l2
GIN SecoAmazonas l2
GIN SecoSanMartin l2
GIN SecoCusco l2
GIN FrescoAmazonas l2
GIN FrescoSanMartin l2
GIN FrescoCusco l2
GINE SecoAmazonas l2
GINE SecoSanMartin l2
GINE SecoCusco l2
GINE FrescoAmazonas l2
GINE FrescoSanMartin l2
GINE FrescoCusco l2

### Filter MS data

In [18]:
# Read raw data

""" df_join_raw = pd.read_csv(f"experiments/input/{exp}_raw.csv", index_col=0)
df_join_raw """

' df_join_raw = pd.read_csv(f"experiments/input/{exp}_raw.csv", index_col=0)\ndf_join_raw '

In [19]:
# Filter
""" for encoder in encoders:
	for group_id in groups_id:
		# Read common node
		common_node_id = np.load(f"experiments/output/{exp}/common_nodes/{encoder}_{group_id}.npy")
		print(f"{encoder}-{group_id}: {len(common_node_id)}/{len(df_join_raw)}")

		# Filter raw data
		df_join_raw_filter = df_join_raw.loc[common_node_id].iloc[:, [0, 1, 2]]
		df_join_raw_filter.to_csv(f"experiments/output/{exp}/filter_raw/{encoder}_{group_id}.csv", sep=";", decimal=",", index_label="Id")
		df_join_raw_filter """

' for encoder in encoders:\n\tfor group_id in groups_id:\n\t\t# Read common node\n\t\tcommon_node_id = np.load(f"experiments/output/{exp}/common_nodes/{encoder}_{group_id}.npy")\n\t\tprint(f"{encoder}-{group_id}: {len(common_node_id)}/{len(df_join_raw)}")\n\n\t\t# Filter raw data\n\t\tdf_join_raw_filter = df_join_raw.loc[common_node_id].iloc[:, [0, 1, 2]]\n\t\tdf_join_raw_filter.to_csv(f"experiments/output/{exp}/filter_raw/{encoder}_{group_id}.csv", sep=";", decimal=",", index_label="Id")\n\t\tdf_join_raw_filter '